//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface AJOKeyPath : NSObject
{
    NSString *_key;
    NSArray *_components;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *components; // @synthesize components=_components;
- (id)initWithKeyPath:(id)arg1;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;

@end

