//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AMapSearchObject.h"

@class NSString;

@interface AMapTMC : AMapSearchObject
{
    long long _distance;
    NSString *_status;
}

+ (id)ajo_mapping;
- (void).cxx_destruct;
@property(nonatomic) long long distance; // @synthesize distance=_distance;
- (id)init;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;

@end

