//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache, NSMutableDictionary;

@interface AMapResourceReader : NSObject
{
    NSMutableDictionary *_bundles;
    NSCache *_imageCache;
}

+ (id)HUDLogoImage;
+ (id)HUDLogoString;
+ (id)embeddedImageWithSourceString:(id)arg1;
+ (id)httpsCertificateData;
+ (id)httpsCertificateString;
+ (id)mapLogoImage;
+ (id)mapLogoString;
+ (id)publicKeyData;
+ (id)publicKeyString;
+ (id)sharedResourceReader;
- (void).cxx_destruct;
- (id)bundle:(id)arg1;
- (void)bundleInvalidNotification:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *bundles; // @synthesize bundles=_bundles;
@property(retain, nonatomic) NSCache *imageCache; // @synthesize imageCache=_imageCache;
- (id)imageNamed:(id)arg1 inBundle:(id)arg2;

@end

