//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AMapNetworkManager, NSDate, NSPredicate, NSTimer;

@interface AMapNearbySearchManager : NSObject
{
    AMapNetworkManager *_networkManager;
    NSDate *_lastUploadTime;
    NSTimer *_uploadTimer;
    NSPredicate *_userIDPredicate;
    _Bool _isAutoUploading;
    double _uploadTimeInterval;
    id <AMapNearbySearchManagerDelegate> _delegate;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)additionalParameters;
- (_Bool)clearUserInfoWithID:(id)arg1;
@property(nonatomic) __weak id <AMapNearbySearchManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)invokeClearActionDelegateWithError:(id)arg1;
- (void)invokeUploadActionDelegateWithError:(id)arg1;
@property(readonly, nonatomic) _Bool isAutoUploading; // @synthesize isAutoUploading=_isAutoUploading;
- (_Bool)isUploadTooFrequently;
- (_Bool)isUserIDValid:(id)arg1;
- (void)onUploadAction;
- (void)performClearingWithUserID:(id)arg1;
- (void)performUploadingWithUserInfo:(id)arg1;
@property(nonatomic) double uploadTimeInterval; // @synthesize uploadTimeInterval=_uploadTimeInterval;
- (void)startAutoUploadNearbyInfo;
- (void)stopAutoUploadNearbyInfo;
- (_Bool)uploadNearbyInfo:(id)arg1;

@end

