//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSOperationQueue, NSSet;

@interface AMapNetworkStackManager : NSObject
{
    NSOperationQueue *_operationQueue;
    NSMutableArray *_waitingStack;
    NSSet *_runloopModes;
}

+ (id)defaultManager;
+ (void)networkStackManagerEntry:(id)arg1;
+ (id)networkStackManagerThread;
- (void).cxx_destruct;
- (void)cancelAllOperations;
- (void)dealloc;
- (id)init;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)pushOperation:(id)arg1;
- (void)pushOperationsToQueue;
@property(retain, nonatomic) NSSet *runloopModes; // @synthesize runloopModes=_runloopModes;
@property(retain, nonatomic) NSMutableArray *waitingStack; // @synthesize waitingStack=_waitingStack;
- (void)startOperation:(id)arg1;
- (id)startOperationWithRequestReformer:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)tryPopWaitingStack;

@end

