//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AMapSearchObject.h"

@class NSString;

@interface AMapInputTipsSearchRequest : AMapSearchObject
{
    _Bool _cityLimit;
    NSString *_keywords;
    NSString *_city;
    NSString *_types;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(nonatomic) _Bool cityLimit; // @synthesize cityLimit=_cityLimit;
- (id)init;
@property(copy, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(copy, nonatomic) NSString *types; // @synthesize types=_types;

@end

