//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AMapCloudSearchBaseRequest.h"

@class NSString;

@interface AMapCloudPOILocalSearchRequest : AMapCloudSearchBaseRequest
{
    NSString *_keywords;
    NSString *_city;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
- (id)description;
@property(copy, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;

@end

