//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface AutoCheckContent : NSObject
{
    NSString *_opName;
    NSDictionary *args;
    NSString *_url;
    id _target;
    SEL _endSel;
    NSDictionary *_args;
    unsigned long long _reqId;
}

+ (id)buildCallBackDicWith:(int)arg1 msg:(id)arg2;
+ (void)callBackMethodWith:(id)arg1;
+ (void)feedBackWith:(_Bool)arg1 token:(id)arg2 resultCode:(unsigned long long)arg3;
- (void)addTarget:(id)arg1 end:(SEL)arg2;
@property(retain, nonatomic) NSDictionary *args; // @synthesize args=_args;
- (id)init;
@property(retain, nonatomic) NSString *opName; // @synthesize opName=_opName;
- (void)recordContent;
- (void)recordFail:(id)arg1;
- (void)recordSuccess:(id)arg1;
@property(nonatomic) unsigned long long reqId; // @synthesize reqId=_reqId;

@end

