//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface ChineseToPinyinResource : NSObject
{
    NSString *_directory;
    NSDictionary *_unicodeToHanyuPinyinTable;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (void)cacheObjec:(id)arg1 forKey:(id)arg2;
- (id)cachedObjectForKey:(id)arg1;
- (id)getHanyuPinyinRecordFromCharWithChar:(unsigned short)arg1;
- (id)getHanyuPinyinStringArrayWithChar:(unsigned short)arg1;
- (id)init;
- (void)initializeResource;
- (_Bool)isValidRecordWithNSString:(id)arg1;

@end

