//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer, NSString, UIColor, UIImage;

@interface CircleLoader : UIView
{
    _Bool _animationing;
    float _lineWidth;
    float _progressValue;
    UIColor *_progressTintColor;
    UIColor *_trackTintColor;
    UIImage *_centerImage;
    NSString *_promptTitle;
    CAShapeLayer *_trackLayer;
    CAShapeLayer *_progressLayer;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool animationing; // @synthesize animationing=_animationing;
@property(retain, nonatomic) UIImage *centerImage; // @synthesize centerImage=_centerImage;
- (void)drawBackgroundCircle:(_Bool)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)hide;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) float lineWidth; // @synthesize lineWidth=_lineWidth;
@property(retain, nonatomic) CAShapeLayer *progressLayer; // @synthesize progressLayer=_progressLayer;
@property(retain, nonatomic) UIColor *progressTintColor; // @synthesize progressTintColor=_progressTintColor;
@property(nonatomic) float progressValue; // @synthesize progressValue=_progressValue;
@property(retain, nonatomic) NSString *promptTitle; // @synthesize promptTitle=_promptTitle;
@property(retain, nonatomic) CAShapeLayer *trackLayer; // @synthesize trackLayer=_trackLayer;
@property(retain, nonatomic) UIColor *trackTintColor; // @synthesize trackTintColor=_trackTintColor;
- (void)startAnimation;

@end

