//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CVideoUserEventWrapper : NSObject
{
    struct CVideoUserEvent *m_pVideoUserEvent;
    unsigned int _videoUserId;
    unsigned long long _userId;
}

- (_Bool)attachVideoUser:(struct IVideoUser *)arg1;
- (void)attachVideoView:(id)arg1;
- (void)dealloc;
- (id)init;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
@property(nonatomic) unsigned int videoUserId; // @synthesize videoUserId=_videoUserId;

@end

