//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface DDLoggingContextSet : NSObject
{
    int lock;
    NSMutableSet *set;
}

- (void).cxx_destruct;
- (void)addToSet:(int)arg1;
- (id)currentSet;
- (id)init;
- (_Bool)isInSet:(int)arg1;
- (void)removeFromSet:(int)arg1;

@end

