//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DPLDeepLink.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSMutableDictionary, NSString, NSURL, NSURLComponents;

@interface DPLMutableDeepLink : DPLDeepLink <NSCopying, NSMutableCopying>
{
    NSMutableDictionary *_queryParameters;
    NSURLComponents *_URLComponents;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSURL *URL;
@property(retain, nonatomic) NSURLComponents *URLComponents; // @synthesize URLComponents=_URLComponents;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) NSMutableDictionary *extras;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)initWithString:(id)arg1;
- (id)mutableAppLinkData;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)mutableReferrerData;
@property(copy, nonatomic) NSMutableDictionary *queryParameters; // @synthesize queryParameters=_queryParameters;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
@property(copy, nonatomic) NSString *referrerAppName;
@property(copy, nonatomic) NSURL *referrerTargetURL;
@property(copy, nonatomic) NSURL *referrerURL;
@property(copy, nonatomic) NSURL *targetURL;
@property(copy, nonatomic) NSString *userAgent;

// Remaining properties
@property(copy, nonatomic) NSString *host; // @dynamic host;
@property(copy, nonatomic) NSString *path; // @dynamic path;
@property(copy, nonatomic) NSString *scheme; // @dynamic scheme;

@end

