//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableAttributedString, NSString, UILabel, UITextView, UIWindow, YNChatMessage;

@interface FullView : UIView
{
    _Bool _isShowing;
    YNChatMessage *_messages;
    UIWindow *_window;
    UIView *_alertView;
    UILabel *_contentLabel;
    UITextView *_titleLabel;
    NSMutableAttributedString *_attributedShowAmplifyText;
    NSString *_showText;
}

- (void).cxx_destruct;
- (void)alertShow;
@property(retain, nonatomic) UIView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) NSMutableAttributedString *attributedShowAmplifyText; // @synthesize attributedShowAmplifyText=_attributedShowAmplifyText;
- (void)buttonBack;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void)dealloc;
- (void)didEndAnimation;
- (void)endAinmationShow;
- (id)initWithTitle:(id)arg1 message:(id)arg2 otherButtonTitle:(id)arg3;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(retain, nonatomic) YNChatMessage *messages; // @synthesize messages=_messages;
@property(copy, nonatomic) NSString *showText; // @synthesize showText=_showText;
@property(retain, nonatomic) UITextView *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)startAniamationShow;

@end

