//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface GCDMulticastDelegateNode : NSObject
{
    id delegate;
    NSObject<OS_dispatch_queue> *delegateQueue;
}

- (void).cxx_destruct;
- (void)dealloc;
@property __weak id delegate; // @synthesize delegate;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2;

@end

