//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IntervalProcess, NSString, RandGuidPare;

@interface GlobalConstants : NSObject
{
    IntervalProcess *_process;
    NSString *_ssnList;
    RandGuidPare *pair;
    _Bool isFastCallBack;
    _Bool isStrongLogin;
    int appId;
    int areaId;
    int optype;
    NSString *currentGuid;
    NSString *currentKey;
    long long checkSmsTimeOut;
    long long checkSmsInterval;
    long long checkTotalTime;
    NSString *smsCode;
    NSString *currentSessionId;
    NSString *ptAccount;
    NSString *sndaId;
    NSString *tempKey;
    NSString *sessionKey;
    unsigned long long woaEventSignCode;
    NSString *currentInvokeId;
    NSString *methodName;
    unsigned long long reqId;
    unsigned long long timoutExLogin;
    unsigned long long remainExLogin;
    NSString *currentRandomKey;
    NSString *currentExtParam;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(nonatomic) int appId; // @synthesize appId;
@property(nonatomic) int areaId; // @synthesize areaId;
- (id)autorelease;
@property(nonatomic) long long checkSmsInterval; // @synthesize checkSmsInterval;
@property(nonatomic) long long checkSmsTimeOut; // @synthesize checkSmsTimeOut;
@property(nonatomic) long long checkTotalTime; // @synthesize checkTotalTime;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *currentExtParam; // @synthesize currentExtParam;
@property(readonly, nonatomic) NSString *currentGuid; // @synthesize currentGuid;
@property(retain, nonatomic) NSString *currentInvokeId; // @synthesize currentInvokeId;
@property(retain, nonatomic) NSString *currentKey; // @synthesize currentKey;
@property(readonly, nonatomic) NSString *currentRandomKey; // @synthesize currentRandomKey;
@property(retain, nonatomic) NSString *currentSessionId; // @synthesize currentSessionId;
- (id)description;
- (void)generateInvokeId;
@property(nonatomic) _Bool isFastCallBack; // @synthesize isFastCallBack;
@property(nonatomic) _Bool isStrongLogin; // @synthesize isStrongLogin;
@property(retain, nonatomic) NSString *methodName; // @synthesize methodName;
@property(nonatomic) int optype; // @synthesize optype;
@property(retain) RandGuidPare *pair; // @synthesize pair;
@property(retain, nonatomic) NSString *ptAccount; // @synthesize ptAccount;
- (oneway void)release;
@property(nonatomic) unsigned long long remainExLogin; // @synthesize remainExLogin;
@property(nonatomic) unsigned long long reqId; // @synthesize reqId;
- (id)retain;
- (unsigned long long)retainCount;
@property(retain, nonatomic) NSString *sessionKey; // @synthesize sessionKey;
- (void)setRandGuidPair:(id)arg1 guid:(id)arg2;
@property(retain, nonatomic) NSString *smsCode; // @synthesize smsCode;
@property(retain, nonatomic) NSString *sndaId; // @synthesize sndaId;
@property(retain, nonatomic) NSString *ssnList; // @synthesize ssnList=_ssnList;
@property(retain, nonatomic) NSString *tempKey; // @synthesize tempKey;
@property(nonatomic) unsigned long long timoutExLogin; // @synthesize timoutExLogin;
@property(nonatomic) unsigned long long woaEventSignCode; // @synthesize woaEventSignCode;
- (_Bool)startProcessWithInterval:(long long)arg1 processBlock:(CDUnknownBlockType)arg2;
- (void)stopProcess;

@end

