//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class UIImage;

@interface JSQMessagesBubbleImage : NSObject <NSCopying>
{
    UIImage *_messageBubbleImage;
    UIImage *_messageBubbleHighlightedImage;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)debugQuickLookObject;
- (id)description;
- (id)init;
- (id)initWithMessageBubbleImage:(id)arg1 highlightedImage:(id)arg2;
@property(readonly, nonatomic) UIImage *messageBubbleHighlightedImage; // @synthesize messageBubbleHighlightedImage=_messageBubbleHighlightedImage;
@property(readonly, nonatomic) UIImage *messageBubbleImage; // @synthesize messageBubbleImage=_messageBubbleImage;

@end

