//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class MessageMedia;

@interface MessageMediaBuilder : PBGeneratedMessageBuilder
{
    MessageMedia *resultMedia;
}

- (void).cxx_destruct;
- (id)build;
- (id)buildPartial;
- (id)clear;
- (id)clearExtension;
- (id)clearMediaId;
- (id)clearMimeType;
- (id)clearName;
- (id)clearPlayLength;
- (id)clearSize;
- (id)clearThumbUrl;
- (id)clearUrl;
- (id)clone;
- (id)defaultInstance;
- (id)extension;
- (_Bool)hasExtension;
- (_Bool)hasMediaId;
- (_Bool)hasMimeType;
- (_Bool)hasName;
- (_Bool)hasPlayLength;
- (_Bool)hasSize;
- (_Bool)hasThumbUrl;
- (_Bool)hasUrl;
- (id)init;
- (id)internalGetResult;
- (id)mediaId;
- (id)mergeFrom:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mimeType;
- (id)name;
- (unsigned int)playLength;
@property(retain) MessageMedia *resultMedia; // @synthesize resultMedia;
- (id)setExtension:(id)arg1;
- (id)setMediaId:(id)arg1;
- (id)setMimeType:(id)arg1;
- (id)setName:(id)arg1;
- (id)setPlayLength:(unsigned int)arg1;
- (id)setSize:(unsigned int)arg1;
- (id)setThumbUrl:(id)arg1;
- (id)setUrl:(id)arg1;
- (unsigned int)size;
- (id)thumbUrl;
- (id)url;

@end

