//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface ObjectiveCFileOptions : PBGeneratedMessage <GeneratedMessageProtocol>
{
    unsigned int hasRelaxCamelCase_:1;
    unsigned int hasPackage_:1;
    unsigned int hasClassPrefix_:1;
    unsigned int relaxCamelCase_:1;
    NSString *package;
    NSString *classPrefix;
}

+ (id)builder;
+ (id)builderWithPrototype:(id)arg1;
+ (id)defaultInstance;
+ (void)initialize;
+ (id)parseFromCodedInputStream:(id)arg1;
+ (id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromData:(id)arg1;
+ (id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromInputStream:(id)arg1;
+ (id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void).cxx_destruct;
- (id)builder;
@property(retain) NSString *classPrefix; // @synthesize classPrefix;
- (id)defaultInstance;
- (_Bool)hasClassPrefix;
- (_Bool)hasPackage;
- (_Bool)hasRelaxCamelCase;
@property(readonly) unsigned long long hash;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isInitialized;
@property(retain) NSString *package; // @synthesize package;
@property _Bool relaxCamelCase;
- (int)serializedSize;
- (void)setHasClassPrefix:(_Bool)arg1;
- (void)setHasPackage:(_Bool)arg1;
- (void)setHasRelaxCamelCase:(_Bool)arg1;
- (void)storeInDictionary:(id)arg1;
- (id)toBuilder;
- (void)writeDescriptionTo:(id)arg1 withIndent:(id)arg2;
- (void)writeToCodedOutputStream:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

