//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OCMRecorder.h"

@interface OCMStubRecorder : OCMRecorder
{
}

@property(readonly, nonatomic) CDUnknownBlockType _andCall; // @dynamic _andCall;
@property(readonly, nonatomic) CDUnknownBlockType _andDo; // @dynamic _andDo;
@property(readonly, nonatomic) CDUnknownBlockType _andForwardToRealObject; // @dynamic _andForwardToRealObject;
@property(readonly, nonatomic) CDUnknownBlockType _andPost; // @dynamic _andPost;
@property(readonly, nonatomic) CDUnknownBlockType _andReturn; // @dynamic _andReturn;
@property(readonly, nonatomic) CDUnknownBlockType _andThrow; // @dynamic _andThrow;
- (id)andCall:(SEL)arg1 onObject:(id)arg2;
- (id)andDo:(CDUnknownBlockType)arg1;
- (id)andForwardToRealObject;
- (id)andPost:(id)arg1;
- (id)andReturn:(id)arg1;
- (id)andReturnValue:(id)arg1;
- (id)andThrow:(id)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)init;
- (id)stub;

@end

