//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OCClassMockObject.h"

@class NSObject;

@interface OCPartialMockObject : OCClassMockObject
{
    NSObject *realObject;
}

- (void)addStub:(id)arg1;
- (void)assertClassIsSupported:(Class)arg1;
- (Class)classForRealObject;
- (void)dealloc;
- (id)description;
- (void)forwardInvocationForRealObject:(id)arg1;
- (id)forwardingTargetForSelectorForRealObject:(SEL)arg1;
- (void)handleUnRecordedInvocation:(id)arg1;
- (id)initWithObject:(id)arg1;
- (id)ocmock_replaced_forwardingTargetForSelector:(SEL)arg1;
- (void)prepareObjectForInstanceMethodMocking;
- (id)realObject;
- (void)setupForwarderForSelector:(SEL)arg1;
- (void)stopMocking;

@end

