//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OpenSSLRSAWrapper : NSObject
{
    struct rsa_st *_rsa;
    NSString *publicKeyBase64;
    NSString *privateKeyBase64;
}

+ (id)shareInstance;
- (id)decryptRSAKeyWithType:(int)arg1 data:(id)arg2;
- (id)encryptRSAKeyWithType:(int)arg1 plainText:(id)arg2;
- (_Bool)exportRSAKeys;
- (_Bool)generateRSAKeyPairWithKeySize:(long long)arg1;
- (int)getBlockSizeWithRSA_PADDING_TYPE:(int)arg1 keyType:(int)arg2;
- (_Bool)importRSAKeyWithType:(int)arg1;
- (_Bool)importRSAPrivateKey:(id)arg1;
- (_Bool)importRSAPublicKey:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSString *privateKeyBase64; // @synthesize privateKeyBase64;
@property(retain, nonatomic) NSString *publicKeyBase64; // @synthesize publicKeyBase64;
- (id)publicKeyBitsWithString:(id)arg1;

@end

