//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBExtendableMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSArray, NSMutableArray, NSString;

@interface PBFileOptions : PBExtendableMessage <GeneratedMessageProtocol>
{
    unsigned int hasJavaMultipleFiles_:1;
    unsigned int hasJavaGenerateEqualsAndHash_:1;
    unsigned int hasJavaStringCheckUtf8_:1;
    unsigned int hasCcGenericServices_:1;
    unsigned int hasJavaGenericServices_:1;
    unsigned int hasPyGenericServices_:1;
    unsigned int hasDeprecated_:1;
    unsigned int hasJavaPackage_:1;
    unsigned int hasJavaOuterClassname_:1;
    unsigned int hasGoPackage_:1;
    unsigned int hasOptimizeFor_:1;
    unsigned int javaMultipleFiles_:1;
    unsigned int javaGenerateEqualsAndHash_:1;
    unsigned int javaStringCheckUtf8_:1;
    unsigned int ccGenericServices_:1;
    unsigned int javaGenericServices_:1;
    unsigned int pyGenericServices_:1;
    unsigned int deprecated_:1;
    NSString *javaPackage;
    NSString *javaOuterClassname;
    NSString *goPackage;
    int optimizeFor;
    NSMutableArray *uninterpretedOptionArray;
}

+ (id)builder;
+ (id)builderWithPrototype:(id)arg1;
+ (id)defaultInstance;
+ (void)initialize;
+ (id)parseFromCodedInputStream:(id)arg1;
+ (id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromData:(id)arg1;
+ (id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromInputStream:(id)arg1;
+ (id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void).cxx_destruct;
- (id)builder;
@property _Bool ccGenericServices;
- (id)defaultInstance;
@property _Bool deprecated;
@property(retain) NSString *goPackage; // @synthesize goPackage;
- (_Bool)hasCcGenericServices;
- (_Bool)hasDeprecated;
- (_Bool)hasGoPackage;
- (_Bool)hasJavaGenerateEqualsAndHash;
- (_Bool)hasJavaGenericServices;
- (_Bool)hasJavaMultipleFiles;
- (_Bool)hasJavaOuterClassname;
- (_Bool)hasJavaPackage;
- (_Bool)hasJavaStringCheckUtf8;
- (_Bool)hasOptimizeFor;
- (_Bool)hasPyGenericServices;
@property(readonly) unsigned long long hash;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isInitialized;
@property _Bool javaGenerateEqualsAndHash;
@property _Bool javaGenericServices;
@property _Bool javaMultipleFiles;
@property(retain) NSString *javaOuterClassname; // @synthesize javaOuterClassname;
@property(retain) NSString *javaPackage; // @synthesize javaPackage;
@property _Bool javaStringCheckUtf8;
@property int optimizeFor; // @synthesize optimizeFor;
@property _Bool pyGenericServices;
- (int)serializedSize;
- (void)setHasCcGenericServices:(_Bool)arg1;
- (void)setHasDeprecated:(_Bool)arg1;
- (void)setHasGoPackage:(_Bool)arg1;
- (void)setHasJavaGenerateEqualsAndHash:(_Bool)arg1;
- (void)setHasJavaGenericServices:(_Bool)arg1;
- (void)setHasJavaMultipleFiles:(_Bool)arg1;
- (void)setHasJavaOuterClassname:(_Bool)arg1;
- (void)setHasJavaPackage:(_Bool)arg1;
- (void)setHasJavaStringCheckUtf8:(_Bool)arg1;
- (void)setHasOptimizeFor:(_Bool)arg1;
- (void)setHasPyGenericServices:(_Bool)arg1;
@property(retain) NSMutableArray *uninterpretedOptionArray; // @synthesize uninterpretedOptionArray;
- (void)storeInDictionary:(id)arg1;
- (id)toBuilder;
@property(readonly) NSArray *uninterpretedOption; // @dynamic uninterpretedOption;
- (id)uninterpretedOptionAtIndex:(unsigned long long)arg1;
- (void)writeDescriptionTo:(id)arg1 withIndent:(id)arg2;
- (void)writeToCodedOutputStream:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

