//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBExtendableMessageBuilder.h"

@class PBFieldOptions;

@interface PBFieldOptionsBuilder : PBExtendableMessageBuilder
{
    PBFieldOptions *resultFieldOptions;
}

- (void).cxx_destruct;
- (id)addUninterpretedOption:(id)arg1;
- (id)build;
- (id)buildPartial;
- (id)clear;
- (id)clearCtype;
- (id)clearDeprecated;
- (id)clearExperimentalMapKey;
- (id)clearLazy;
- (id)clearPacked;
- (id)clearUninterpretedOption;
- (id)clearWeak;
- (id)clone;
- (int)ctype;
- (id)defaultInstance;
- (_Bool)deprecated;
- (id)experimentalMapKey;
- (_Bool)hasCtype;
- (_Bool)hasDeprecated;
- (_Bool)hasExperimentalMapKey;
- (_Bool)hasLazy;
- (_Bool)hasPacked;
- (_Bool)hasWeak;
- (id)init;
- (id)internalGetResult;
- (_Bool)lazy;
- (id)mergeFrom:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (_Bool)packed;
@property(retain) PBFieldOptions *resultFieldOptions; // @synthesize resultFieldOptions;
- (id)setCtype:(int)arg1;
- (id)setDeprecated:(_Bool)arg1;
- (id)setExperimentalMapKey:(id)arg1;
- (id)setLazy:(_Bool)arg1;
- (id)setPacked:(_Bool)arg1;
- (id)setUninterpretedOptionArray:(id)arg1;
- (id)setWeak:(_Bool)arg1;
- (id)uninterpretedOption;
- (id)uninterpretedOptionAtIndex:(unsigned long long)arg1;
- (_Bool)weak;

@end

