//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class PBFieldDescriptorProto;

@interface PBFieldDescriptorProtoBuilder : PBGeneratedMessageBuilder
{
    PBFieldDescriptorProto *resultFieldDescriptorProto;
}

- (void).cxx_destruct;
- (id)build;
- (id)buildPartial;
- (id)clear;
- (id)clearDefaultValue;
- (id)clearExtendee;
- (id)clearLabel;
- (id)clearName;
- (id)clearNumber;
- (id)clearOneofIndex;
- (id)clearOptions;
- (id)clearType;
- (id)clearTypeName;
- (id)clone;
- (id)defaultInstance;
- (id)defaultValue;
- (id)extendee;
- (_Bool)hasDefaultValue;
- (_Bool)hasExtendee;
- (_Bool)hasLabel;
- (_Bool)hasName;
- (_Bool)hasNumber;
- (_Bool)hasOneofIndex;
- (_Bool)hasOptions;
- (_Bool)hasType;
- (_Bool)hasTypeName;
- (id)init;
- (id)internalGetResult;
- (int)label;
- (id)mergeFrom:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mergeOptions:(id)arg1;
- (id)name;
- (int)number;
- (int)oneofIndex;
- (id)options;
@property(retain) PBFieldDescriptorProto *resultFieldDescriptorProto; // @synthesize resultFieldDescriptorProto;
- (id)setDefaultValue:(id)arg1;
- (id)setExtendee:(id)arg1;
- (id)setLabel:(int)arg1;
- (id)setName:(id)arg1;
- (id)setNumber:(int)arg1;
- (id)setOneofIndex:(int)arg1;
- (id)setOptions:(id)arg1;
- (id)setOptionsBuilder:(id)arg1;
- (id)setType:(int)arg1;
- (id)setTypeName:(id)arg1;
- (int)type;
- (id)typeName;

@end

