//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBAbstractMessageBuilder.h"

@interface PBGeneratedMessageBuilder : PBAbstractMessageBuilder
{
}

- (void)checkInitialized;
- (void)checkInitializedParsed;
- (id)internalGetResult;
- (_Bool)isInitialized;
- (id)mergeUnknownFields:(id)arg1;
- (_Bool)parseUnknownField:(id)arg1 unknownFields:(id)arg2 extensionRegistry:(id)arg3 tag:(int)arg4;
- (id)setUnknownFields:(id)arg1;
- (id)unknownFields;

@end

