//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class PBServiceDescriptorProto;

@interface PBServiceDescriptorProtoBuilder : PBGeneratedMessageBuilder
{
    PBServiceDescriptorProto *resultServiceDescriptorProto;
}

- (void).cxx_destruct;
- (id)addMethod:(id)arg1;
- (id)build;
- (id)buildPartial;
- (id)clear;
- (id)clearMethod;
- (id)clearName;
- (id)clearOptions;
- (id)clone;
- (id)defaultInstance;
- (_Bool)hasName;
- (_Bool)hasOptions;
- (id)init;
- (id)internalGetResult;
- (id)mergeFrom:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mergeOptions:(id)arg1;
- (id)method;
- (id)methodAtIndex:(unsigned long long)arg1;
- (id)name;
- (id)options;
@property(retain) PBServiceDescriptorProto *resultServiceDescriptorProto; // @synthesize resultServiceDescriptorProto;
- (id)setMethodArray:(id)arg1;
- (id)setName:(id)arg1;
- (id)setOptions:(id)arg1;
- (id)setOptionsBuilder:(id)arg1;

@end

