//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface PersistentUtil : NSObject
{
    NSMutableDictionary *persistDic;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (id)autorelease;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getMobileSessionKey;
- (id)getPubKeyVersion;
- (id)getSignature;
- (void)initData;
- (void)initSeq;
- (id)objectForKey:(id)arg1;
- (oneway void)release;
- (id)retain;
- (unsigned long long)retainCount;
- (void)saveData;
- (void)saveMobileSessionKey:(id)arg1;
- (void)savePubKeyVersion:(id)arg1;
- (void)saveSignature:(id)arg1;
- (long long)seqInc;
- (void)setValue:(id)arg1 forKey:(id)arg2;

@end

