//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class Ping;

@interface PingBuilder : PBGeneratedMessageBuilder
{
    Ping *resultPing;
}

- (void).cxx_destruct;
- (id)build;
- (id)buildPartial;
- (id)clear;
- (id)clearMid;
- (id)clone;
- (id)defaultInstance;
- (_Bool)hasMid;
- (id)init;
- (id)internalGetResult;
- (id)mergeFrom:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mid;
@property(retain) Ping *resultPing; // @synthesize resultPing;
- (id)setMid:(id)arg1;

@end

