//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNZone.h"

@class NSLock, NSMutableDictionary, NSString, QNDnsManager, QNSessionManager;

@interface QNAutoZone : QNZone
{
    NSString *server;
    NSMutableDictionary *cache;
    NSLock *lock;
    QNSessionManager *sesionManager;
    QNDnsManager *dns;
}

- (void).cxx_destruct;
- (id)initWithDns:(id)arg1;
- (void)preQuery:(id)arg1 on:(CDUnknownBlockType)arg2;
- (id)up:(id)arg1 isHttps:(_Bool)arg2 frozenDomain:(id)arg3;

@end

