//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QNPipelineConfig;

@interface QNPipeline : NSObject
{
    id <QNHttpDelegate> _httpManager;
    QNPipelineConfig *_config;
}

+ (id)dateFormatter;
- (void).cxx_destruct;
@property(retain, nonatomic) QNPipelineConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) id <QNHttpDelegate> httpManager; // @synthesize httpManager=_httpManager;
- (id)init:(id)arg1;
- (void)pumpRepo:(id)arg1 event:(id)arg2 token:(id)arg3 handler:(CDUnknownBlockType)arg4;
- (void)pumpRepo:(id)arg1 events:(id)arg2 token:(id)arg3 handler:(CDUnknownBlockType)arg4;
- (void)pumpRepo:(id)arg1 string:(id)arg2 token:(id)arg3 handler:(CDUnknownBlockType)arg4;
- (id)url:(id)arg1;

@end

