//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, QNZoneInfo;

@interface QNZone : NSObject
{
    NSArray *_upDomainList;
    QNZoneInfo *_zoneInfo;
}

- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) NSArray *upDomainList; // @synthesize upDomainList=_upDomainList;
@property(retain, nonatomic) QNZoneInfo *zoneInfo; // @synthesize zoneInfo=_zoneInfo;
- (id)up:(id)arg1 isHttps:(_Bool)arg2 frozenDomain:(id)arg3;
- (id)upDomainList:(id)arg1;
- (id)upHost:(id)arg1 isHttps:(_Bool)arg2 lastUpHost:(id)arg3;

@end

