//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RandGuidPare : NSObject
{
    NSString *rand;
    NSString *guid;
}

@property(retain, nonatomic) NSString *guid; // @synthesize guid;
@property(retain, nonatomic) NSString *rand; // @synthesize rand;

@end

