//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UITextField, UIView;

@interface SBInputWithButtonCell : UITableViewCell
{
    UITextField *_tfInput;
    UIButton *_btnGetValidCode;
    id <SBInputWithButtonCellDelegate> _delegate;
    UIView *_bgView;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIButton *btnGetValidCode; // @synthesize btnGetValidCode=_btnGetValidCode;
- (void)clearInputContent;
@property(nonatomic) __weak id <SBInputWithButtonCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didGetValidCodeBtnTapped;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)loadUI;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UITextField *tfInput; // @synthesize tfInput=_tfInput;
- (void)setUILayout;

@end

