//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SDPBankCardListModel : NSObject
{
    NSString *_cardNo;
    NSString *_agreementNo;
    NSString *_cardType;
    NSString *_bankCode;
    NSString *_desc;
    NSString *_enabled;
    NSString *_instMobile;
    NSString *_needSendSms;
    NSString *_isDefault;
    NSString *_paymentType;
    long long _seqNum;
}

+ (id)modelWithDictionary:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *agreementNo; // @synthesize agreementNo=_agreementNo;
@property(copy, nonatomic) NSString *bankCode; // @synthesize bankCode=_bankCode;
@property(copy, nonatomic) NSString *cardNo; // @synthesize cardNo=_cardNo;
@property(copy, nonatomic) NSString *cardType; // @synthesize cardType=_cardType;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *enabled; // @synthesize enabled=_enabled;
- (id)initWithDictionary:(id)arg1;
@property(copy, nonatomic) NSString *instMobile; // @synthesize instMobile=_instMobile;
@property(copy, nonatomic) NSString *isDefault; // @synthesize isDefault=_isDefault;
@property(copy, nonatomic) NSString *needSendSms; // @synthesize needSendSms=_needSendSms;
@property(copy, nonatomic) NSString *paymentType; // @synthesize paymentType=_paymentType;
@property(nonatomic) long long seqNum; // @synthesize seqNum=_seqNum;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;

@end

