//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface SDPBindCardInfoAlertView : UIView
{
    long long RowWidth;
    long long RowHeight;
    id <SDPBindCardInfoAlertViewDelegate> _delegate;
    UILabel *_titleLabel;
    UIImageView *_iconImageView;
    UILabel *_infoLabel;
    NSString *_titleStr;
    NSString *_iconName;
    NSString *_infoStr;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SDPBindCardInfoAlertViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) NSString *infoStr; // @synthesize infoStr=_infoStr;
- (id)initWithFrame:(struct CGRect)arg1 withTitle:(id)arg2 iconImage:(id)arg3 info:(id)arg4;
- (void)lianShangCustomerService;
- (void)setLabelSpaceAndDistinguishPhoneNumLabel:(id)arg1 labelStr:(id)arg2;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSString *titleStr; // @synthesize titleStr=_titleStr;

@end

