//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

@class NSMutableArray, SDPBillModel, UILabel, UIScrollView, UIView;

@interface SDPBillDetailController : SDPBaseViewController
{
    SDPBillModel *_model;
    UIScrollView *_scrollView;
    UIView *_headerView;
    UIView *_contentView;
    NSMutableArray *_contents;
    UILabel *_moneyLabel;
}

- (void).cxx_destruct;
- (void)btnAction:(id)arg1;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSMutableArray *contents; // @synthesize contents=_contents;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) SDPBillModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *moneyLabel; // @synthesize moneyLabel=_moneyLabel;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)setup;
- (void)viewDidLoad;

@end

