//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

#import "NSURLSessionDelegate.h"
#import "SPSafeKeyBoardDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSString, NSURLSession, SPPayPwdVariableSizeView, SPSafeKeyBoard, UILabel;

@interface SDPConfirmPayPwdFromModifyViewController : SDPBaseViewController <UIAlertViewDelegate, SPSafeKeyBoardDelegate, NSURLSessionDelegate>
{
    NSString *confirmTicket;
    _Bool _isLoading;
    NSString *originalTicket;
    NSString *firstTicket;
    NSString *_requestNo;
    CDUnknownBlockType _confirmPayPwdFaileBlock;
    CDUnknownBlockType _setPayPwdSuccessBlock;
    UILabel *_tipLabel1;
    SPPayPwdVariableSizeView *_payPwdView;
    SPSafeKeyBoard *_safeKeyBoardView;
    NSURLSession *_keyBoardURLSession;
}

- (void).cxx_destruct;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(copy, nonatomic) CDUnknownBlockType confirmPayPwdFaileBlock; // @synthesize confirmPayPwdFaileBlock=_confirmPayPwdFaileBlock;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)didTapLeftBarButtonItem;
@property(retain, nonatomic) NSString *firstTicket; // @synthesize firstTicket;
- (void)gotoSetPayPwd;
- (void)handleDataWith:(id)arg1;
- (void)handlePayPwdRequestErrorInfoWithMessage:(id)arg1;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) NSURLSession *keyBoardURLSession; // @synthesize keyBoardURLSession=_keyBoardURLSession;
- (void)keyboard:(id)arg1 changeCharacters:(id)arg2;
- (void)keyboard:(id)arg1 deleteCharacters:(id)arg2;
- (void)keyboard:(id)arg1 didFinishedEditing:(id)arg2;
- (void)loadView;
@property(retain, nonatomic) NSString *originalTicket; // @synthesize originalTicket;
@property(retain, nonatomic) SPPayPwdVariableSizeView *payPwdView; // @synthesize payPwdView=_payPwdView;
@property(retain, nonatomic) NSString *requestNo; // @synthesize requestNo=_requestNo;
@property(retain, nonatomic) SPSafeKeyBoard *safeKeyBoardView; // @synthesize safeKeyBoardView=_safeKeyBoardView;
@property(copy, nonatomic) CDUnknownBlockType setPayPwdSuccessBlock; // @synthesize setPayPwdSuccessBlock=_setPayPwdSuccessBlock;
@property(retain, nonatomic) UILabel *tipLabel1; // @synthesize tipLabel1=_tipLabel1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

