//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableArray, NSString, UIButton, UITableView, UITextField, UITextRange, UIView;

@interface SDPChoosePersonViewController : SDPBaseViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate>
{
    NSString *previousTextFieldContent;
    UITextRange *previousSelection;
    _Bool isRetouch;
    _Bool _isPhoneNumEmpty;
    UITextField *_tfPhone;
    UIButton *_btnNext;
    UITableView *_tvRecent;
    UIView *_viewRecentBg;
    NSMutableArray *_contactsArray;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *btnNext; // @synthesize btnNext=_btnNext;
@property(retain, nonatomic) NSMutableArray *contactsArray; // @synthesize contactsArray=_contactsArray;
- (void)didBtnNextTapped:(id)arg1;
- (void)doQueryContactsRequest;
- (void)doQueryPayeeRequest:(id)arg1;
- (void)formatPhoneNumber:(id)arg1;
@property(nonatomic) _Bool isPhoneNumEmpty; // @synthesize isPhoneNumEmpty=_isPhoneNumEmpty;
- (_Bool)loadData;
- (void)setNextBtnState;
- (void)setRetouch;
@property(nonatomic) __weak UITextField *tfPhone; // @synthesize tfPhone=_tfPhone;
@property(nonatomic) __weak UITableView *tvRecent; // @synthesize tvRecent=_tvRecent;
@property(nonatomic) __weak UIView *viewRecentBg; // @synthesize viewRecentBg=_viewRecentBg;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

