//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

@class NSLayoutConstraint, UIButton, UIImageView, UILabel, UIView;

@interface SDPChangeViewController : SDPBaseViewController
{
    _Bool _fromPortal;
    UIView *_viewIphoneXHair;
    NSLayoutConstraint *_bottomLabelConstraint;
    NSLayoutConstraint *_hairHeightConstraint;
    UIButton *_btnBack;
    UIView *_viewTop;
    UILabel *_labelChange;
    UIImageView *_ivTop;
    UIButton *_btnCharge;
    UIButton *_btnWithdraw;
    long long _statusBarStyle;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *bottomLabelConstraint; // @synthesize bottomLabelConstraint=_bottomLabelConstraint;
@property(nonatomic) __weak UIButton *btnBack; // @synthesize btnBack=_btnBack;
@property(nonatomic) __weak UIButton *btnCharge; // @synthesize btnCharge=_btnCharge;
@property(nonatomic) __weak UIButton *btnWithdraw; // @synthesize btnWithdraw=_btnWithdraw;
- (void)didBtnBackTapped:(id)arg1;
- (void)didBtnChargeTapped:(id)arg1;
- (void)didBtnWithdrawTapped:(id)arg1;
- (void)doQueryBalanceRequest;
@property(nonatomic) _Bool fromPortal; // @synthesize fromPortal=_fromPortal;
@property(nonatomic) __weak NSLayoutConstraint *hairHeightConstraint; // @synthesize hairHeightConstraint=_hairHeightConstraint;
@property(nonatomic) __weak UIImageView *ivTop; // @synthesize ivTop=_ivTop;
@property(nonatomic) __weak UILabel *labelChange; // @synthesize labelChange=_labelChange;
- (_Bool)prefersNavigationBarHidden;
@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
@property(nonatomic) __weak UIView *viewIphoneXHair; // @synthesize viewIphoneXHair=_viewIphoneXHair;
@property(nonatomic) __weak UIView *viewTop; // @synthesize viewTop=_viewTop;
- (void)startReport;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

