//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIApplicationDelegate.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSMutableArray, NSString, UIWindow;

@interface SDPDatePickerView : UIView <UIPickerViewDataSource, UIPickerViewDelegate, UIApplicationDelegate>
{
    UIView *contentView;
    CDUnknownBlockType backBlock;
    NSMutableArray *yearArray;
    NSMutableArray *monthArray;
    long long currentYear;
    long long currentMonth;
    NSString *restr;
    NSString *selectedYear;
    NSString *selectecMonth;
}

- (void).cxx_destruct;
- (void)dismiss;
- (id)initDatePackerWithResponse:(CDUnknownBlockType)arg1;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (void)setViewInterface;
- (void)show;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

