//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SDPEnvManager : NSObject
{
    _Bool _isLogEnabled;
    _Bool _isTest;
    NSString *_wifiAppID;
    NSString *_sdp_baseURL;
    NSString *_sdp_getRequestTokenURL;
    NSString *_sdp_billList;
    NSString *_sdp_billEmpty;
    NSString *_sdp_checkstand;
    NSString *_sdp_accountLevel;
    NSString *_sdp_safeKeyBoardEnv;
    NSString *_sdp_safeKeyBoardPath;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(nonatomic) _Bool isLogEnabled; // @synthesize isLogEnabled=_isLogEnabled;
@property(nonatomic) _Bool isTest; // @synthesize isTest=_isTest;
@property(retain, nonatomic) NSString *sdp_accountLevel; // @synthesize sdp_accountLevel=_sdp_accountLevel;
@property(retain, nonatomic) NSString *sdp_baseURL; // @synthesize sdp_baseURL=_sdp_baseURL;
@property(retain, nonatomic) NSString *sdp_billEmpty; // @synthesize sdp_billEmpty=_sdp_billEmpty;
@property(retain, nonatomic) NSString *sdp_billList; // @synthesize sdp_billList=_sdp_billList;
@property(retain, nonatomic) NSString *sdp_checkstand; // @synthesize sdp_checkstand=_sdp_checkstand;
@property(retain, nonatomic) NSString *sdp_getRequestTokenURL; // @synthesize sdp_getRequestTokenURL=_sdp_getRequestTokenURL;
@property(retain, nonatomic) NSString *sdp_safeKeyBoardEnv; // @synthesize sdp_safeKeyBoardEnv=_sdp_safeKeyBoardEnv;
@property(retain, nonatomic) NSString *sdp_safeKeyBoardPath; // @synthesize sdp_safeKeyBoardPath=_sdp_safeKeyBoardPath;
@property(retain, nonatomic) NSString *wifiAppID; // @synthesize wifiAppID=_wifiAppID;

@end

