//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPBaseView.h"

@class UIButton, UIImageView, UIView;

@interface SDPIDCardNumInputKeyBoardView : SPBaseView
{
    id <SPIDCardNumInputKeyBoardViewDelegate> _delegate;
    UIButton *_button0;
    UIButton *_button1;
    UIButton *_button2;
    UIButton *_button3;
    UIButton *_button4;
    UIButton *_button5;
    UIButton *_button6;
    UIButton *_button7;
    UIButton *_button8;
    UIButton *_button9;
    UIButton *_buttonDelete;
    UIButton *_buttonX;
    UIImageView *_hLineImageView1;
    UIImageView *_hLineImageView2;
    UIImageView *_hLineImageView3;
    UIImageView *_hLineImageView4;
    UIImageView *_vLineImageView1;
    UIImageView *_vLineImageView2;
    UIView *_bottomView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIButton *button0; // @synthesize button0=_button0;
@property(retain, nonatomic) UIButton *button1; // @synthesize button1=_button1;
@property(retain, nonatomic) UIButton *button2; // @synthesize button2=_button2;
@property(retain, nonatomic) UIButton *button3; // @synthesize button3=_button3;
@property(retain, nonatomic) UIButton *button4; // @synthesize button4=_button4;
@property(retain, nonatomic) UIButton *button5; // @synthesize button5=_button5;
@property(retain, nonatomic) UIButton *button6; // @synthesize button6=_button6;
@property(retain, nonatomic) UIButton *button7; // @synthesize button7=_button7;
@property(retain, nonatomic) UIButton *button8; // @synthesize button8=_button8;
@property(retain, nonatomic) UIButton *button9; // @synthesize button9=_button9;
- (void)buttonClicked:(id)arg1;
@property(retain, nonatomic) UIButton *buttonDelete; // @synthesize buttonDelete=_buttonDelete;
@property(retain, nonatomic) UIButton *buttonX; // @synthesize buttonX=_buttonX;
@property(nonatomic) id <SPIDCardNumInputKeyBoardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *hLineImageView1; // @synthesize hLineImageView1=_hLineImageView1;
@property(retain, nonatomic) UIImageView *hLineImageView2; // @synthesize hLineImageView2=_hLineImageView2;
@property(retain, nonatomic) UIImageView *hLineImageView3; // @synthesize hLineImageView3=_hLineImageView3;
@property(retain, nonatomic) UIImageView *hLineImageView4; // @synthesize hLineImageView4=_hLineImageView4;
- (id)init;
- (void)loadKeyBoardView;
@property(retain, nonatomic) UIImageView *vLineImageView1; // @synthesize vLineImageView1=_vLineImageView1;
@property(retain, nonatomic) UIImageView *vLineImageView2; // @synthesize vLineImageView2=_vLineImageView2;

@end

