//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UILabel, UITextField;

@interface SDPInputMoneyView : UIView <UITextFieldDelegate>
{
    UITextField *_textField;
    UILabel *_tipLabel;
    UIButton *_tipBtn;
    UIButton *_errorBtn;
    NSString *_moneyStr;
    CDUnknownBlockType _btnEnable;
    unsigned long long _inputType;
    UIView *_lineView;
    UILabel *_moneyLabel;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType btnEnable; // @synthesize btnEnable=_btnEnable;
@property(retain, nonatomic) UIButton *errorBtn; // @synthesize errorBtn=_errorBtn;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) unsigned long long inputType; // @synthesize inputType=_inputType;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *moneyLabel; // @synthesize moneyLabel=_moneyLabel;
@property(retain, nonatomic) NSString *moneyStr; // @synthesize moneyStr=_moneyStr;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) UIButton *tipBtn; // @synthesize tipBtn=_tipBtn;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
- (void)setup;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldClear:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

