//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SDPLoginModel : NSObject
{
    _Bool _isInvalid;
    _Bool _isUserLogin;
    NSString *_sdpLianXinToken;
    NSString *_loginName;
    NSString *_sdpMobile;
    NSString *_sdpUhid;
    NSString *_sdpNickName;
    NSString *_sdpSex;
    NSString *_sdpAvatarImageUrl;
    NSString *_sdpOutToken;
    NSString *_sdpAccessToken;
    NSString *_sdpMemberId;
    NSString *_sdpResultCode;
    NSString *_sdpResultMessage;
    NSString *_sdpLongi;
    NSString *_sdpLati;
    NSString *_btnName;
    NSString *_user_merchantOrderNo;
    NSString *_user_merchantNo;
    NSString *_user_appId;
    NSString *_walletFirstView;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *btnName; // @synthesize btnName=_btnName;
- (void)clearLoginInfo;
@property(nonatomic) _Bool isInvalid; // @synthesize isInvalid=_isInvalid;
@property(nonatomic) _Bool isUserLogin; // @synthesize isUserLogin=_isUserLogin;
@property(copy, nonatomic) NSString *loginName; // @synthesize loginName=_loginName;
@property(copy, nonatomic) NSString *sdpAccessToken; // @synthesize sdpAccessToken=_sdpAccessToken;
@property(copy, nonatomic) NSString *sdpAvatarImageUrl; // @synthesize sdpAvatarImageUrl=_sdpAvatarImageUrl;
@property(copy, nonatomic) NSString *sdpLati; // @synthesize sdpLati=_sdpLati;
@property(copy, nonatomic) NSString *sdpLianXinToken; // @synthesize sdpLianXinToken=_sdpLianXinToken;
@property(copy, nonatomic) NSString *sdpLongi; // @synthesize sdpLongi=_sdpLongi;
@property(copy, nonatomic) NSString *sdpMemberId; // @synthesize sdpMemberId=_sdpMemberId;
@property(copy, nonatomic) NSString *sdpMobile; // @synthesize sdpMobile=_sdpMobile;
@property(copy, nonatomic) NSString *sdpNickName; // @synthesize sdpNickName=_sdpNickName;
@property(copy, nonatomic) NSString *sdpOutToken; // @synthesize sdpOutToken=_sdpOutToken;
@property(copy, nonatomic) NSString *sdpResultCode; // @synthesize sdpResultCode=_sdpResultCode;
@property(copy, nonatomic) NSString *sdpResultMessage; // @synthesize sdpResultMessage=_sdpResultMessage;
@property(copy, nonatomic) NSString *sdpSex; // @synthesize sdpSex=_sdpSex;
@property(copy, nonatomic) NSString *sdpUhid; // @synthesize sdpUhid=_sdpUhid;
@property(copy, nonatomic) NSString *user_appId; // @synthesize user_appId=_user_appId;
@property(copy, nonatomic) NSString *user_merchantNo; // @synthesize user_merchantNo=_user_merchantNo;
@property(copy, nonatomic) NSString *user_merchantOrderNo; // @synthesize user_merchantOrderNo=_user_merchantOrderNo;
@property(copy, nonatomic) NSString *walletFirstView; // @synthesize walletFirstView=_walletFirstView;

@end

