//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSString, UIView;

@interface SDPNavigationController : UINavigationController <UINavigationControllerDelegate, UIGestureRecognizerDelegate>
{
    _Bool _isSwiping;
    UIView *_blurBackView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *blurBackView; // @synthesize blurBackView=_blurBackView;
- (id)convertViewToImage:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) _Bool isSwiping; // @synthesize isSwiping=_isSwiping;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)setupXXX;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

