//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"

@class NSMutableDictionary, NSString, NSURLRequest, NSURLSession;

@interface SDPNetwork : NSObject <NSURLSessionDelegate>
{
    NSString *_cert;
    NSString *_sdpCertSerialNo;
    NSURLSession *_session;
    NSMutableDictionary *_parameters;
    NSMutableDictionary *_checkstandParameters;
    NSURLRequest *_request;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)POST:(id)arg1 parameters:(id)arg2 isCheckstand:(_Bool)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) NSString *cert; // @synthesize cert=_cert;
@property(retain, nonatomic) NSMutableDictionary *checkstandParameters; // @synthesize checkstandParameters=_checkstandParameters;
- (id)dataTaskWithHTTPMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 isCheckstand:(_Bool)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)dealloc;
- (id)getKey:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSMutableDictionary *parameters; // @synthesize parameters=_parameters;
- (id)parametersToDataIsCheckstand:(_Bool)arg1;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (id)requestWithMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 isCheckstand:(_Bool)arg4;
@property(copy, nonatomic) NSString *sdpCertSerialNo; // @synthesize sdpCertSerialNo=_sdpCertSerialNo;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

