//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface SDPPayManagerHeaderCell : UITableViewCell
{
    UIImageView *_ivHead;
    UILabel *_labelName;
    UILabel *_labelPhone;
    UIImageView *_ivAuthStatus;
    UIImageView *_ivArrow;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)configUIWithName:(id)arg1 phone:(id)arg2 isAuthed:(_Bool)arg3;
@property(nonatomic) __weak UIImageView *ivArrow; // @synthesize ivArrow=_ivArrow;
@property(nonatomic) __weak UIImageView *ivAuthStatus; // @synthesize ivAuthStatus=_ivAuthStatus;
@property(nonatomic) __weak UIImageView *ivHead; // @synthesize ivHead=_ivHead;
@property(nonatomic) __weak UILabel *labelName; // @synthesize labelName=_labelName;
@property(nonatomic) __weak UILabel *labelPhone; // @synthesize labelPhone=_labelPhone;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

