//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

#import "SDPCareerViewControllerDelegate.h"
#import "SDPCommonTextFieldDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, SDPCommonDatePickerView, SDPCommonTextField, SDPKeyboardScrollView, SDPSaveInfoModel, UILabel;

@interface SDPPersonalInfoViewController : SDPBaseViewController <SDPCommonTextFieldDelegate, UITextFieldDelegate, SDPCareerViewControllerDelegate>
{
    id <SDPPersonalInfoViewControllerDelegate> _delegate;
    SDPKeyboardScrollView *_svBg;
    UILabel *_labelName;
    UILabel *_labelSex;
    SDPCommonTextField *_tfPhone;
    UILabel *_labelStyle;
    UILabel *_labelNum;
    SDPCommonTextField *_tfDate;
    UILabel *_labelCountry;
    SDPCommonTextField *_tfArea;
    SDPCommonTextField *_tfJob;
    SDPCommonDatePickerView *_datePickerView;
    SDPSaveInfoModel *_infoModel;
}

- (void).cxx_destruct;
- (void)clearInputString:(id)arg1;
- (void)configTextField;
- (void)configUIWithModel:(id)arg1;
@property(retain, nonatomic) SDPCommonDatePickerView *datePickerView; // @synthesize datePickerView=_datePickerView;
@property(nonatomic) __weak id <SDPPersonalInfoViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didSelectCareer:(id)arg1;
- (void)didTapLeftBarButtonItem;
- (void)didTapRightBarButtonItem;
- (void)doQuerySafeInfoRequest;
- (void)doSaveSafeInfoRequest;
@property(retain, nonatomic) SDPSaveInfoModel *infoModel; // @synthesize infoModel=_infoModel;
- (void)keyboardWillHide:(id)arg1;
@property(nonatomic) __weak UILabel *labelCountry; // @synthesize labelCountry=_labelCountry;
@property(nonatomic) __weak UILabel *labelName; // @synthesize labelName=_labelName;
@property(nonatomic) __weak UILabel *labelNum; // @synthesize labelNum=_labelNum;
@property(nonatomic) __weak UILabel *labelSex; // @synthesize labelSex=_labelSex;
@property(nonatomic) __weak UILabel *labelStyle; // @synthesize labelStyle=_labelStyle;
@property(nonatomic) __weak SDPKeyboardScrollView *svBg; // @synthesize svBg=_svBg;
@property(nonatomic) __weak SDPCommonTextField *tfArea; // @synthesize tfArea=_tfArea;
@property(nonatomic) __weak SDPCommonTextField *tfDate; // @synthesize tfDate=_tfDate;
@property(nonatomic) __weak SDPCommonTextField *tfJob; // @synthesize tfJob=_tfJob;
@property(nonatomic) __weak SDPCommonTextField *tfPhone; // @synthesize tfPhone=_tfPhone;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

