//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView;

@interface SDPPayAddBankCardCell : UITableViewCell
{
    UIImageView *_ivIcon;
    UIImageView *_ivArrow;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *ivArrow; // @synthesize ivArrow=_ivArrow;
@property(nonatomic) __weak UIImageView *ivIcon; // @synthesize ivIcon=_ivIcon;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

