//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

#import "CLLocationManagerDelegate.h"
#import "SDPPortalBottomCollectionViewCellDelegate.h"
#import "SDPPortalHeaderCollectionViewCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIScrollViewDelegate.h"

@class CLLocationManager, NSLayoutConstraint, NSMutableArray, NSString, UIButton, UICollectionView, UILabel, UIView;

@interface SDPPortalViewController : SDPBaseViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIScrollViewDelegate, SDPPortalHeaderCollectionViewCellDelegate, SDPPortalBottomCollectionViewCellDelegate, CLLocationManagerDelegate>
{
    _Bool _isFromH5;
    _Bool _needRedPoint;
    NSString *_source;
    UIView *_viewNaviBg;
    UIView *_viewToolBg;
    NSLayoutConstraint *_toolBgHeightConstraint;
    UIButton *_btnBack;
    UILabel *_labelTitle;
    UIButton *_btnMore;
    UICollectionView *_collectionViewPortal;
    NSMutableArray *_subAppsArray;
    NSMutableArray *_bannerArray;
    UIView *_viewRedPoint;
    NSLayoutConstraint *_naviHeight;
    CLLocationManager *_locationManager;
    NSString *_requestTokenNo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *bannerArray; // @synthesize bannerArray=_bannerArray;
@property(nonatomic) __weak UIButton *btnBack; // @synthesize btnBack=_btnBack;
@property(nonatomic) __weak UIButton *btnMore; // @synthesize btnMore=_btnMore;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(nonatomic) __weak UICollectionView *collectionViewPortal; // @synthesize collectionViewPortal=_collectionViewPortal;
- (void)configeUI;
- (void)dealloc;
- (void)didBtnBackTapped:(id)arg1;
- (void)didBtnBankCardTapped;
- (void)didBtnBillTapped;
- (void)didBtnChangeTapped;
- (void)didBtnMoreTapped:(id)arg1;
- (void)didSelectBannerItemWithUrl:(id)arg1;
- (void)doInfoRequest;
- (void)doQueryAccountStatusInfosRequest;
- (void)handleGatherEventIdHomePageUV;
- (void)handleGatherEventIdThirdLoginRespose;
- (void)handleLoginAlert;
- (void)handleLoginUserCountAndNoLoginUserCountAndHomePageUVGather;
- (void)handleNoticationGatherEventIdHomePageUV;
- (void)handleUserIsNeddLogin;
- (id)init;
@property(nonatomic) _Bool isFromH5; // @synthesize isFromH5=_isFromH5;
- (_Bool)isShowAD;
@property(nonatomic) __weak UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
@property(nonatomic) __weak NSLayoutConstraint *naviHeight; // @synthesize naviHeight=_naviHeight;
@property(nonatomic) _Bool needRedPoint; // @synthesize needRedPoint=_needRedPoint;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersNavigationBarHidden;
- (void)pushChoosePersonViewController;
- (void)pushPayManagerVC;
- (void)pushRechargeViewController;
- (void)pushWithdrawDepositController;
- (void)reloadReportInfo;
@property(copy, nonatomic) NSString *requestTokenNo; // @synthesize requestTokenNo=_requestTokenNo;
- (void)scrollViewDidScroll:(id)arg1;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSMutableArray *subAppsArray; // @synthesize subAppsArray=_subAppsArray;
@property(nonatomic) __weak NSLayoutConstraint *toolBgHeightConstraint; // @synthesize toolBgHeightConstraint=_toolBgHeightConstraint;
@property(nonatomic) __weak UIView *viewNaviBg; // @synthesize viewNaviBg=_viewNaviBg;
@property(nonatomic) __weak UIView *viewRedPoint; // @synthesize viewRedPoint=_viewRedPoint;
@property(nonatomic) __weak UIView *viewToolBg; // @synthesize viewToolBg=_viewToolBg;
- (void)showADView;
- (void)startReport;
- (void)startUpdateLocation;
- (void)updateRedPoint;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)wifiLoginFailure;
- (void)wifiLoginSuccess;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

