//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSDictionary, NSString, SDPOrderInfo, UIWindow;

@interface SDPPayManger : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *_locationManager;
    SDPOrderInfo *_orderInfo;
    NSString *_appScheme;
    CDUnknownBlockType _completion;
    NSString *_receveRequestTime;
    NSString *_cashierType;
    NSDictionary *_receveBillResultDic;
    UIWindow *_window;
    UIWindow *_originWindow;
    NSDictionary *_receiveOrderDict;
    NSDictionary *_receiveOrderErrorDict;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appScheme; // @synthesize appScheme=_appScheme;
@property(copy, nonatomic) NSString *cashierType; // @synthesize cashierType=_cashierType;
- (void)checkUserLogin:(CDUnknownBlockType)arg1;
- (void)choosePaymentMethod:(id)arg1 requestTime:(id)arg2 callback:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void)deallocWindow;
- (void)handleRevicerRequestParametersDatas;
- (void)handleRevieceBillRequest;
- (void)hide;
- (void)hideViewAnimated:(_Bool)arg1;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
@property(retain, nonatomic) SDPOrderInfo *orderInfo; // @synthesize orderInfo=_orderInfo;
@property(retain, nonatomic) UIWindow *originWindow; // @synthesize originWindow=_originWindow;
- (void)payOrder:(id)arg1 fromScheme:(id)arg2 callback:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSDictionary *receiveOrderDict; // @synthesize receiveOrderDict=_receiveOrderDict;
@property(retain, nonatomic) NSDictionary *receiveOrderErrorDict; // @synthesize receiveOrderErrorDict=_receiveOrderErrorDict;
@property(retain, nonatomic) NSDictionary *receveBillResultDic; // @synthesize receveBillResultDic=_receveBillResultDic;
@property(copy, nonatomic) NSString *receveRequestTime; // @synthesize receveRequestTime=_receveRequestTime;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)showWithCashierType:(id)arg1 orderInfo:(id)arg2 amountDic:(id)arg3 isDiscount:(_Bool)arg4 callback:(CDUnknownBlockType)arg5;
- (void)startUpdateLocation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

