//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface SDPPayMethodDisableCell : UITableViewCell
{
    UIImageView *_ivIcon;
    UILabel *_labelName;
    UILabel *_labelDesc;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)configDisableCellUIWithPaymentType:(id)arg1 payMethodModel:(id)arg2;
@property(nonatomic) __weak UIImageView *ivIcon; // @synthesize ivIcon=_ivIcon;
@property(nonatomic) __weak UILabel *labelDesc; // @synthesize labelDesc=_labelDesc;
@property(nonatomic) __weak UILabel *labelName; // @synthesize labelName=_labelName;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

