//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

#import "SDPInputPayPwdViewDelegate.h"
#import "SDPPickerViewDelegate.h"
#import "SPSafeKeyBoardDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableArray, NSString, SDPBankCardListModel, SDPKeyboardScrollView, SDPPickerView, UIButton, UITextField;

@interface SDPRechargeViewController : SDPBaseViewController <SPSafeKeyBoardDelegate, SDPPickerViewDelegate, UITextFieldDelegate, SDPInputPayPwdViewDelegate>
{
    SDPKeyboardScrollView *_scrollView;
    UIButton *_bankNameBtn;
    UITextField *_tfAmount;
    UIButton *_nextBtn;
    SDPPickerView *_bankNamePickerView;
    NSMutableArray *_cardListArray;
    NSMutableArray *_cardNameArray;
    SDPBankCardListModel *_currentSelectedModel;
}

- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) __weak UIButton *bankNameBtn; // @synthesize bankNameBtn=_bankNameBtn;
@property(retain, nonatomic) SDPPickerView *bankNamePickerView; // @synthesize bankNamePickerView=_bankNamePickerView;
@property(retain, nonatomic) NSMutableArray *cardListArray; // @synthesize cardListArray=_cardListArray;
@property(retain, nonatomic) NSMutableArray *cardNameArray; // @synthesize cardNameArray=_cardNameArray;
- (void)chooseBankCard:(id)arg1;
- (void)clickNextBtn:(id)arg1;
@property(retain, nonatomic) SDPBankCardListModel *currentSelectedModel; // @synthesize currentSelectedModel=_currentSelectedModel;
- (void)didReceiveMemoryWarning;
- (void)doQueryInfosRequest;
- (void)findBackPayPwdWithPayPwdStatus:(_Bool)arg1;
- (void)handleDepositGatherParametersInfoWithDepositId:(id)arg1 resposeCode:(id)arg2 resposeMessage:(id)arg3 needGatherEnd:(_Bool)arg4;
- (void)handleModelDataWithModel:(id)arg1;
- (void)handlePayPwdErrorWithCode:(id)arg1 message:(id)arg2;
- (void)keyboardWillHide:(id)arg1;
- (_Bool)loadData;
@property(nonatomic) __weak UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
- (void)onClickCancelBtnWithPickerView:(id)arg1;
- (void)onClickDoneBtnWithPickerView:(id)arg1 bankCardListModel:(id)arg2;
- (void)onCloseRightButtonWithPassword:(id)arg1;
- (void)payPasswordEncryptionFailurewithCode:(id)arg1 message:(id)arg2 payMethodModel:(id)arg3;
- (void)paySuccess:(id)arg1 payMethodModel:(id)arg2;
- (void)pushBindCardPersonalInfoVC;
- (void)pushFindPayPwdBindCardFirstViewControllerWithPayPwdStatus:(_Bool)arg1;
- (void)pushFindPayPwdCardListViewControllerWithPayPwdStatus:(_Bool)arg1;
- (void)pushRechargeFormNewCardResult:(id)arg1 cardNo:(id)arg2;
- (void)pushVerifyPayPwdViewController;
- (void)queryBindedCardRequest:(id)arg1;
- (void)realNameStateNotNull;
@property(nonatomic) __weak SDPKeyboardScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UITextField *tfAmount; // @synthesize tfAmount=_tfAmount;
- (void)showInputPayPwdView;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

