//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface SDPSelectBankView : UIView
{
    UILabel *_bankLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *bankLabel; // @synthesize bankLabel=_bankLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setup;

@end

