//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SDPBaseViewController.h"

#import "NSURLSessionDelegate.h"
#import "SPSafeKeyBoardDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSString, NSURLSession, SPPayPwdVariableSizeView, SPSafeKeyBoard, UILabel, UIView;

@interface SDPSetNewPayPwdForFindViewController : SDPBaseViewController <UIAlertViewDelegate, SPSafeKeyBoardDelegate, NSURLSessionDelegate>
{
    _Bool _isPushView;
    _Bool _isLoading;
    unsigned long long _bindCardType;
    NSString *_setPayPwdRequestNo;
    CDUnknownBlockType _setPayPwdSuccessBlock;
    CDUnknownBlockType _setPayPwdCancelBlock;
    UILabel *_tipLabel1;
    SPPayPwdVariableSizeView *_payPwdView;
    UIView *_pwdDifferentAlertView;
    UILabel *_pwdDifferentLabel;
    SPSafeKeyBoard *_safeKeyBoardView;
    NSURLSession *_keyBoardURLSession;
}

- (void).cxx_destruct;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) unsigned long long bindCardType; // @synthesize bindCardType=_bindCardType;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)didTapLeftBarButtonItem;
- (void)handleDataWith:(id)arg1;
- (void)handlePayPwdRequestErrorInfoWithMessage:(id)arg1;
- (void)handleSetPayPwdCancelEvent;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool isPushView; // @synthesize isPushView=_isPushView;
@property(retain, nonatomic) NSURLSession *keyBoardURLSession; // @synthesize keyBoardURLSession=_keyBoardURLSession;
- (void)keyboard:(id)arg1 changeCharacters:(id)arg2;
- (void)keyboard:(id)arg1 deleteCharacters:(id)arg2;
- (void)keyboard:(id)arg1 didFinishedEditing:(id)arg2;
- (void)loadView;
@property(retain, nonatomic) SPPayPwdVariableSizeView *payPwdView; // @synthesize payPwdView=_payPwdView;
- (void)pushConfirmPwdControllerWithNewTicket:(id)arg1;
@property(retain, nonatomic) UIView *pwdDifferentAlertView; // @synthesize pwdDifferentAlertView=_pwdDifferentAlertView;
@property(retain, nonatomic) UILabel *pwdDifferentLabel; // @synthesize pwdDifferentLabel=_pwdDifferentLabel;
@property(retain, nonatomic) SPSafeKeyBoard *safeKeyBoardView; // @synthesize safeKeyBoardView=_safeKeyBoardView;
@property(copy, nonatomic) CDUnknownBlockType setPayPwdCancelBlock; // @synthesize setPayPwdCancelBlock=_setPayPwdCancelBlock;
@property(retain, nonatomic) NSString *setPayPwdRequestNo; // @synthesize setPayPwdRequestNo=_setPayPwdRequestNo;
@property(copy, nonatomic) CDUnknownBlockType setPayPwdSuccessBlock; // @synthesize setPayPwdSuccessBlock=_setPayPwdSuccessBlock;
@property(retain, nonatomic) UILabel *tipLabel1; // @synthesize tipLabel1=_tipLabel1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

