//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSDictionary, NSString;

@interface SDPUserInfoModel : NSObject <NSCoding>
{
    NSString *_cert;
    NSString *_certSerialNo;
    NSString *_outToken;
    NSString *_uhId;
    NSString *_thirdToken;
    NSString *_payPwdState;
    NSString *_certNo;
    NSString *_trueName;
    NSString *_realNameState;
    NSString *_availableBalance;
    NSString *_frozenBalance;
    NSArray *_allBankArray;
    NSDictionary *_paymentTool;
    long long _identityStatus;
}

+ (id)sharedContextModel;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *allBankArray; // @synthesize allBankArray=_allBankArray;
@property(copy, nonatomic) NSString *availableBalance; // @synthesize availableBalance=_availableBalance;
@property(retain, nonatomic) NSString *cert; // @synthesize cert=_cert;
@property(copy, nonatomic) NSString *certNo; // @synthesize certNo=_certNo;
@property(retain, nonatomic) NSString *certSerialNo; // @synthesize certSerialNo=_certSerialNo;
- (void)encodeWithCoder:(id)arg1;
@property(copy, nonatomic) NSString *frozenBalance; // @synthesize frozenBalance=_frozenBalance;
@property(nonatomic) long long identityStatus; // @synthesize identityStatus=_identityStatus;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSString *outToken; // @synthesize outToken=_outToken;
@property(retain, nonatomic) NSString *payPwdState; // @synthesize payPwdState=_payPwdState;
@property(retain, nonatomic) NSDictionary *paymentTool; // @synthesize paymentTool=_paymentTool;
@property(retain, nonatomic) NSString *realNameState; // @synthesize realNameState=_realNameState;
@property(retain, nonatomic) NSString *thirdToken; // @synthesize thirdToken=_thirdToken;
@property(copy, nonatomic) NSString *trueName; // @synthesize trueName=_trueName;
@property(retain, nonatomic) NSString *uhId; // @synthesize uhId=_uhId;

@end

