//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSArray, NSString, UIColor, UILabel, UIResponder;

@interface SLKTextView : UITextView
{
    _Bool _didNotResignFirstResponder;
    _Bool _loupeVisible;
    _Bool _typingSuggestionEnabled;
    _Bool _undoManagerEnabled;
    _Bool _didFlashScrollIndicators;
    UIResponder *overrideNextResponder;
    unsigned long long _maxNumberOfLines;
    unsigned long long _pastableMediaTypes;
    UILabel *_placeholderLabel;
    NSArray *_keyboardCommands;
    long long _verticalMoveDirection;
    struct CGRect _verticalMoveStartCaretRect;
    struct CGRect _verticalMoveLastCaretRect;
}

+ (_Bool)requiresConstraintBasedLayout;
- (void).cxx_destruct;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canResignFirstResponder;
- (id)closestPositionToPosition:(id)arg1 inDirection:(long long)arg2;
- (void)commonInit;
- (void)dealloc;
- (void)didBeginEditing:(id)arg1;
- (void)didChangeText:(id)arg1;
- (void)didEndEditing:(id)arg1;
@property(nonatomic) _Bool didFlashScrollIndicators; // @synthesize didFlashScrollIndicators=_didFlashScrollIndicators;
@property(nonatomic) _Bool didNotResignFirstResponder; // @synthesize didNotResignFirstResponder=_didNotResignFirstResponder;
- (void)didPressAnyArrowKey:(id)arg1;
- (void)didPressCommandZKeys:(id)arg1;
- (void)didPressLineBreakKeys:(id)arg1;
- (void)flashScrollIndicatorsIfNeeded;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (struct CGSize)intrinsicContentSize;
@property(readonly, nonatomic) _Bool isExpanding;
@property(nonatomic, getter=isLoupeVisible) _Bool loupeVisible; // @synthesize loupeVisible=_loupeVisible;
- (_Bool)isNewVerticalMovementForPosition:(id)arg1 inDirection:(long long)arg2;
- (_Bool)isPasteboardItemSupported;
@property(nonatomic, getter=isTypingSuggestionEnabled) _Bool typingSuggestionEnabled; // @synthesize typingSuggestionEnabled=_typingSuggestionEnabled;
- (id)keyCommands;
@property(retain, nonatomic) NSArray *keyboardCommands; // @synthesize keyboardCommands=_keyboardCommands;
- (void)layoutSubviews;
@property(nonatomic) unsigned long long maxNumberOfLines; // @synthesize maxNumberOfLines=_maxNumberOfLines;
- (void)motionEnded:(long long)arg1 withEvent:(id)arg2;
- (void)moveCursorTodirection:(long long)arg1;
- (id)nextResponder;
@property(readonly, nonatomic) unsigned long long numberOfLines;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) __weak UIResponder *overrideNextResponder; // @synthesize overrideNextResponder;
@property(nonatomic) unsigned long long pastableMediaTypes; // @synthesize pastableMediaTypes=_pastableMediaTypes;
- (void)paste:(id)arg1;
- (id)pasteboardContentType;
- (id)pastedItem;
@property(copy, nonatomic) NSString *placeholder;
@property(copy, nonatomic) UIColor *placeholderColor;
@property(retain, nonatomic) UILabel *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
- (struct CGRect)placeholderRectThatFits:(struct CGRect)arg1;
- (void)prepareForUndo:(id)arg1;
- (void)redoo:(id)arg1;
- (void)refreshFirstResponder;
- (void)refreshInputViews;
- (_Bool)resignFirstResponder;
- (void)scrollToBottom;
- (struct _NSRange)selectedRange;
- (void)setAttributedText:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setText:(id)arg1;
- (void)setTextAlignment:(long long)arg1;
@property(nonatomic) _Bool undoManagerEnabled; // @synthesize undoManagerEnabled=_undoManagerEnabled;
@property(nonatomic) long long verticalMoveDirection; // @synthesize verticalMoveDirection=_verticalMoveDirection;
@property(nonatomic) struct CGRect verticalMoveLastCaretRect; // @synthesize verticalMoveLastCaretRect=_verticalMoveLastCaretRect;
@property(nonatomic) struct CGRect verticalMoveStartCaretRect; // @synthesize verticalMoveStartCaretRect=_verticalMoveStartCaretRect;
- (_Bool)shouldHidePlaceholder;
- (void)slk_insertNewLineBreak;
- (struct _NSRange)slk_insertText:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)slk_insertTextAtCaretRange:(id)arg1;
- (void)slk_scrollToBottomAnimated:(_Bool)arg1;
- (void)slk_scrollToCaretPositonAnimated:(_Bool)arg1;
- (id)slk_wordAtCaretRange:(struct _NSRange *)arg1;
- (id)slk_wordAtRange:(struct _NSRange)arg1 rangeInText:(struct _NSRange *)arg2;
- (id)supportedMediaTypes;
- (void)undoo:(id)arg1;

@end

