//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SPSafeKeyBoard;

@protocol SPSafeKeyBoardDelegate <NSObject>

@optional
- (void)keyboard:(SPSafeKeyBoard *)arg1 changeCharacters:(NSString *)arg2;
- (void)keyboard:(SPSafeKeyBoard *)arg1 deleteCharacters:(NSString *)arg2;
- (void)keyboard:(SPSafeKeyBoard *)arg1 didFinishedEditing:(NSString *)arg2;
- (void)keyboardDidHided:(SPSafeKeyBoard *)arg1;
@end

