//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface TFHppleElement : NSObject
{
    NSDictionary *node;
    _Bool isXML;
    NSString *encoding;
    TFHppleElement *parent;
}

+ (id)hppleElementWithNode:(id)arg1 isXML:(_Bool)arg2 withEncoding:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *attributes;
@property(readonly, nonatomic) NSArray *children;
- (id)childrenWithClassName:(id)arg1;
- (id)childrenWithTagName:(id)arg1;
@property(readonly, copy, nonatomic) NSString *content;
- (id)description;
@property(readonly, nonatomic) TFHppleElement *firstChild;
- (id)firstChildWithClassName:(id)arg1;
- (id)firstChildWithTagName:(id)arg1;
- (id)firstTextChild;
- (_Bool)hasChildren;
- (id)initWithNode:(id)arg1 isXML:(_Bool)arg2 withEncoding:(id)arg3;
- (_Bool)isTextNode;
- (id)objectForKey:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
@property(nonatomic) TFHppleElement *parent; // @synthesize parent;
- (id)peekAtSearchWithXPathQuery:(id)arg1;
@property(readonly, copy, nonatomic) NSString *raw;
- (id)searchWithXPathQuery:(id)arg1;
@property(readonly, copy, nonatomic) NSString *tagName;
- (id)text;

@end

