//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (JSQMessages)
+ (id)jsq_messageBubbleBlueColor;
+ (id)jsq_messageBubbleGreenColor;
+ (id)jsq_messageBubbleLightGrayColor;
+ (id)jsq_messageBubbleRedColor;
- (id)jsq_colorByDarkeningColorWithValue:(double)arg1;
@end

