//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (YNImageViewCreateHelper)
+ (id)yn_CreateImageViewWithFrame:(struct CGRect)arg1 translatesToConstraints:(_Bool)arg2 image:(id)arg3;
@end

