//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface UILabel (Widget)
+ (id)sdp_labelWithText:(id)arg1 textFont:(id)arg2 textColor:(id)arg3 constrainedToSize:(struct CGSize)arg4 lineBreakMode:(long long)arg5 textAlignment:(long long)arg6;
@end

