//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (VOIP)
- (_Bool)checkNetworkAvailableBeforeUseVoip;
- (void)hideAllToast;
- (void)showAudioDisableAlert;
- (void)showCallFailedToast;
- (void)showCallInUsingClickVoipAlert;
- (void)showConnectionTimeoutToast;
- (void)showEndAnomalyToast;
- (void)showHangupToast:(_Bool)arg1;
- (void)showLineBusyToast;
- (void)showNotFriendToast;
- (void)showOtherBusyToast;
- (void)showToast:(id)arg1;
- (void)showToastWithDuration:(double)arg1 andText:(id)arg2;
- (void)showUnableToRestartCallToast;
- (void)showUnstableConnectionToast;
- (void)showVideoDisableAlert;
- (void)showVoipInUsingAlert;
- (void)showVoipInUsingToast;
- (void)showVoipSwitchToVoiceToast:(_Bool)arg1;
- (_Bool)voipInUsing;
- (_Bool)voipInUsingWithOther:(id)arg1;
@end

