//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (Alert)
- (void)showAlertWithTitle:(id)arg1 message:(id)arg2 cancelTitle:(id)arg3 destructiveTitle:(id)arg4 otherTitles:(id)arg5 actionHandler:(CDUnknownBlockType)arg6;
- (void)showToastInView:(id)arg1;
- (void)showToastInWindow:(id)arg1;
@end

