//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Widget)
- (struct CGRect)sdp_applicationFrame;
@property(nonatomic) double sdp_centerX;
@property(nonatomic) double sdp_centerY;
- (void)sdp_dismissKeyBoard;
- (id)sdp_findFirstResponderBeneathView:(id)arg1;
- (id)sdp_findRootViewController;
@property(nonatomic) double sdp_height;
- (id)sdp_keyboardCancelButtonView;
@property(nonatomic) double sdp_maxX;
@property(nonatomic) double sdp_maxY;
@property(nonatomic) double sdp_minX;
@property(nonatomic) double sdp_minY;
@property(nonatomic) struct CGPoint sdp_origin;
- (struct CGRect)sdp_screenBounds;
@property(nonatomic) struct CGSize sdp_size;
- (void)sdp_viewWithBottomLine;
- (void)sdp_viewWithBottomLineOffset:(double)arg1;
- (void)sdp_viewWithLeftLine;
- (void)sdp_viewWithLeftLineOffset:(double)arg1;
- (void)sdp_viewWithRightLine;
- (void)sdp_viewWithRightLineOffset:(double)arg1;
- (void)sdp_viewWithTopLine;
- (void)sdp_viewWithTopLineOffset:(double)arg1;
@property(nonatomic) double sdp_width;
@property(nonatomic) double sdp_x;
@property(nonatomic) double sdp_y;
@end

