//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UserExtraInfo : NSObject
{
    _Bool _isJailBreak;
    NSString *_platform;
    NSString *_deviceName;
    NSString *_versionName;
    NSString *_versionCode;
    NSString *_nationalCode;
    NSString *_imei;
    NSString *_imsi;
    NSString *_osVersion;
    NSString *_resolution;
    NSString *_carrier;
    NSString *_deviceId;
    NSString *_isSimulator;
    NSString *_channelId;
    NSString *_localIp;
    NSString *_lbStr;
    NSString *_teamid;
    NSString *_bundleid;
    NSString *_idfa;
    NSString *_idfv;
}

+ (void)clear;
+ (id)shareUserExtraInfo;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *bundleid; // @synthesize bundleid=_bundleid;
@property(retain, nonatomic) NSString *carrier; // @synthesize carrier=_carrier;
@property(retain, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
- (void)checkUploadUserDfpInfoIsForce:(_Bool)arg1 withBLock:(CDUnknownBlockType)arg2;
- (id)countryCodeByCarrier;
@property(retain, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(retain, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
- (id)fetchCountCode;
- (void)forceUploadUserExtraInfoWithBLock:(CDUnknownBlockType)arg1;
- (id)getDeviceIPAdress;
@property(retain, nonatomic) NSString *idfa; // @synthesize idfa=_idfa;
@property(retain, nonatomic) NSString *idfv; // @synthesize idfv=_idfv;
@property(retain, nonatomic) NSString *imei; // @synthesize imei=_imei;
@property(retain, nonatomic) NSString *imsi; // @synthesize imsi=_imsi;
- (id)init;
@property(nonatomic) _Bool isJailBreak; // @synthesize isJailBreak=_isJailBreak;
@property(retain, nonatomic) NSString *isSimulator; // @synthesize isSimulator=_isSimulator;
@property(copy, nonatomic) NSString *lbStr; // @synthesize lbStr=_lbStr;
@property(retain, nonatomic) NSString *localIp; // @synthesize localIp=_localIp;
@property(retain, nonatomic) NSString *nationalCode; // @synthesize nationalCode=_nationalCode;
@property(retain, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(retain, nonatomic) NSString *platform; // @synthesize platform=_platform;
@property(retain, nonatomic) NSString *resolution; // @synthesize resolution=_resolution;
@property(copy, nonatomic) NSString *teamid; // @synthesize teamid=_teamid;
@property(retain, nonatomic) NSString *versionCode; // @synthesize versionCode=_versionCode;
@property(retain, nonatomic) NSString *versionName; // @synthesize versionName=_versionName;
- (void)uploadUserDfpInfoWithBLock:(CDUnknownBlockType)arg1;
- (void)uploadUserExtraInfoWithBLock:(CDUnknownBlockType)arg1;
- (id)userAgent;
- (id)userAgentJsonFormat;
- (id)userAndDeviceInfo;
- (id)userBSSID;
- (id)userDfpInfo;
- (id)userExtraInfo;
- (id)userInfoAdsJsonFormat;
- (id)userSSID;
- (_Bool)yn_isJailBreak;

@end

