//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UINavigationBarDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIWebViewDelegate.h"
#import "WKAuthWebViewProgressDelegate.h"

@class NSMutableArray, NSString, NSURL, UIBarButtonItem, UIColor, UIPanGestureRecognizer, UIView, UIWebView, WKAuthWebViewProgress, WKAuthWebViewProgressView;

@interface WKAuthWebViewController : UIViewController <UIWebViewDelegate, UINavigationControllerDelegate, UINavigationBarDelegate, WKAuthWebViewProgressDelegate>
{
    _Bool _isSwipingBack;
    NSURL *_url;
    UIWebView *_webView;
    UIColor *_progressViewColor;
    UIBarButtonItem *_customBackBarItem;
    UIBarButtonItem *_closeButtonItem;
    WKAuthWebViewProgress *_progressProxy;
    WKAuthWebViewProgressView *_progressView;
    NSMutableArray *_snapShotsArray;
    UIView *_currentSnapShotView;
    UIView *_prevSnapShotView;
    UIView *_swipingBackgoundView;
    UIPanGestureRecognizer *_swipePanGesture;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIBarButtonItem *closeButtonItem; // @synthesize closeButtonItem=_closeButtonItem;
- (void)closeItemClicked;
@property(retain, nonatomic) UIView *currentSnapShotView; // @synthesize currentSnapShotView=_currentSnapShotView;
@property(retain, nonatomic) UIBarButtonItem *customBackBarItem; // @synthesize customBackBarItem=_customBackBarItem;
- (void)customBackItemClicked;
- (void)endPopSnapShotView;
- (id)initWithUrl:(id)arg1;
@property(nonatomic) _Bool isSwipingBack; // @synthesize isSwipingBack=_isSwipingBack;
- (void)popSnapShotViewWithPanGestureDistance:(double)arg1;
- (long long)preferredStatusBarStyle;
@property(retain, nonatomic) UIView *prevSnapShotView; // @synthesize prevSnapShotView=_prevSnapShotView;
@property(retain, nonatomic) WKAuthWebViewProgress *progressProxy; // @synthesize progressProxy=_progressProxy;
@property(retain, nonatomic) WKAuthWebViewProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIColor *progressViewColor; // @synthesize progressViewColor=_progressViewColor;
- (void)pushCurrentSnapshotViewWithRequest:(id)arg1;
- (void)reloadWebView;
@property(retain, nonatomic) NSMutableArray *snapShotsArray; // @synthesize snapShotsArray=_snapShotsArray;
@property(retain, nonatomic) UIPanGestureRecognizer *swipePanGesture; // @synthesize swipePanGesture=_swipePanGesture;
@property(retain, nonatomic) UIView *swipingBackgoundView; // @synthesize swipingBackgoundView=_swipingBackgoundView;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void)startPopSnapshotView;
- (void)swipePanGestureHandler:(id)arg1;
- (void)updateNavigationItems;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewProgress:(id)arg1 updateProgress:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

