//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WoaRequestBody : NSObject
{
    int _type;
    NSString *verfiCode;
    NSString *_url;
    id <woaCallBackDelegate> _delegate;
    NSString *_guid;
    NSString *_key;
    unsigned long long _optCmd;
}

- (id)buildCallBackDicWith:(int)arg1 msg:(id)arg2;
- (id)buildResDicWithErrorCode:(unsigned long long)arg1 msg:(id)arg2;
- (id)buildSessionId;
- (void)callBackMethodWith:(id)arg1;
@property(nonatomic) id <woaCallBackDelegate> delegate; // @synthesize delegate=_delegate;
- (void)getGuid;
- (void)getGuidFail;
- (void)getGuidFinish;
- (id)getResDicWithErrorCode:(unsigned long long)arg1;
- (void)guidRequestFail:(id)arg1;
- (void)guidRequestSuccess:(id)arg1;
@property(nonatomic) int type; // @synthesize type=_type;
- (void)startRequest;

@end

