//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WoaRequestBody.h"

@class NSString;

@interface WOAUserNameRegisterRequest : WoaRequestBody
{
    NSString *_userName;
    NSString *_pwd;
}

- (void)getGuidFinish;
- (id)init;
@property(retain, nonatomic) NSString *pwd; // @synthesize pwd=_pwd;
- (void)requestFail:(id)arg1;
- (void)requestSuccess:(id)arg1;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void)startRequest;

@end

