//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UICKeyChainStore;

@interface YNAccountManager : NSObject
{
    _Bool _isEnterViaLoginFlow;
    _Bool _isUserRegistered;
    _Bool _isNeedShowRecommendFriends;
    _Bool _isNeedShowWecomeView;
    _Bool _isNeedMendUserProfile;
    _Bool _hintStyle;
    _Bool _showUserStyle;
    NSString *_uid;
    NSString *_zhangxinID;
    NSString *_phoneNumber;
    NSString *_sessionID;
    NSString *_refreshKey;
    NSString *_productID;
    NSString *_chatSessionID;
    NSString *_userAvatarURL;
    NSString *_smsid;
    NSString *_uuid;
    NSString *_inputPhoneNumber;
    NSString *_woaSessionID;
    NSString *_countryCode;
    NSString *_userName;
    NSString *_passWord;
    NSString *_sessionId;
    NSString *_tempUid;
    UICKeyChainStore *_keychain;
    UICKeyChainStore *_sharedKeychain;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (id)backupDBDirectoryPath;
- (id)barcodeString;
@property(retain, nonatomic) NSString *chatSessionID; // @synthesize chatSessionID=_chatSessionID;
- (void)clearAccountInfo;
- (void)clearTempAccountInfo;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
- (id)encrptedUidWithTimeStamp;
- (_Bool)hasUncompletedRegister;
@property(nonatomic) _Bool hintStyle; // @synthesize hintStyle=_hintStyle;
- (id)init;
@property(retain, nonatomic) NSString *inputPhoneNumber; // @synthesize inputPhoneNumber=_inputPhoneNumber;
@property(nonatomic) _Bool isEnterViaLoginFlow; // @synthesize isEnterViaLoginFlow=_isEnterViaLoginFlow;
@property(nonatomic) _Bool isNeedMendUserProfile; // @synthesize isNeedMendUserProfile=_isNeedMendUserProfile;
@property(nonatomic) _Bool isNeedShowRecommendFriends; // @synthesize isNeedShowRecommendFriends=_isNeedShowRecommendFriends;
@property(nonatomic) _Bool isNeedShowWecomeView; // @synthesize isNeedShowWecomeView=_isNeedShowWecomeView;
@property(nonatomic) _Bool isUserFristLogin;
@property(nonatomic) _Bool isUserRegistered; // @synthesize isUserRegistered=_isUserRegistered;
@property(readonly, nonatomic) UICKeyChainStore *keychain; // @synthesize keychain=_keychain;
- (void)logoutAccountInfo;
- (void)migrateAccountDirectory;
- (void)migrationAccountInfo;
@property(retain, nonatomic) NSString *passWord; // @synthesize passWord=_passWord;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) NSString *productID; // @synthesize productID=_productID;
- (void)readAccountInfo;
@property(retain, nonatomic) NSString *refreshKey; // @synthesize refreshKey=_refreshKey;
- (void)saveAccountInfo;
- (void)saveTempAccountInfo;
@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) _Bool showUserStyle; // @synthesize showUserStyle=_showUserStyle;
@property(retain, nonatomic) NSString *smsid; // @synthesize smsid=_smsid;
@property(retain, nonatomic) NSString *tempUid; // @synthesize tempUid=_tempUid;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(retain, nonatomic) NSString *userAvatarURL; // @synthesize userAvatarURL=_userAvatarURL;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) NSString *woaSessionID; // @synthesize woaSessionID=_woaSessionID;
@property(retain, nonatomic) NSString *zhangxinID; // @synthesize zhangxinID=_zhangxinID;
@property(readonly, nonatomic) UICKeyChainStore *sharedKeychain; // @synthesize sharedKeychain=_sharedKeychain;
- (void)synchronizeSharedAccountInfo;
- (id)uidWithTimeStamp;
- (id)userDirectoryPath;

@end

