//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNScrollContainerViewController.h"

#import "YNRegisterManagerDelegate.h"

@class NSString, UIButton, UILabel, UIView, YNFriend, YNRegisterTopView;

@interface YNAccountDidRegisterController : YNScrollContainerViewController <YNRegisterManagerDelegate>
{
    long long statusBarStyle;
    YNFriend *_friendModel;
    YNRegisterTopView *_topView;
    UIView *_contentView;
    UIButton *_avatarButton;
    UILabel *_nameLabel;
    UILabel *_instructionLabel;
    UIButton *_isMineButton;
    UIButton *_notMineButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *avatarButton; // @synthesize avatarButton=_avatarButton;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void)dealloc;
- (void)didFinishedRegisterYNAccount:(_Bool)arg1;
- (void)faileToRegisterYNAccountWith:(id)arg1;
- (void)faileToVerifyCodeYNAccountWith:(id)arg1;
@property(retain, nonatomic) YNFriend *friendModel; // @synthesize friendModel=_friendModel;
- (id)init;
@property(retain, nonatomic) UILabel *instructionLabel; // @synthesize instructionLabel=_instructionLabel;
@property(retain, nonatomic) UIButton *isMineButton; // @synthesize isMineButton=_isMineButton;
- (void)isMineButtonAction:(id)arg1;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIButton *notMineButton; // @synthesize notMineButton=_notMineButton;
- (void)notMineButtonAction:(id)arg1;
@property(retain, nonatomic) YNRegisterTopView *topView; // @synthesize topView=_topView;
- (void)setupViewConstraints;
- (void)varificationCancelButtonClicked:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

