//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel, YNAvatarView;

@interface YNAddFriendBannerView : UIView
{
    YNAvatarView *_avatarView;
    UIButton *_avatarBtn;
    UILabel *_titleLabel;
    UIButton *_addButton;
    UIView *_bottomLine;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *addButton; // @synthesize addButton=_addButton;
@property(retain, nonatomic) UIButton *avatarBtn; // @synthesize avatarBtn=_avatarBtn;
@property(retain, nonatomic) YNAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setupViewConstraints;

@end

