//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSAttributedString, NSMutableArray, NSString, UILabel, UITableView, UIView, YNAlertAnimation;

@interface YNAlertController : YNViewController <UIViewControllerTransitioningDelegate, UITableViewDataSource, UITableViewDelegate>
{
    UIView *_containerView;
    long long _titleAlignment;
    long long _messageAlignment;
    NSAttributedString *_attributedTitle;
    NSAttributedString *_attributedMessage;
    NSMutableArray *_actions;
    YNAlertAnimation *_animation;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UITableView *_tableView;
    double _maxHeight;
    unsigned long long _maxActionCount;
}

+ (id)alertControllerWithAttributedTitle:(id)arg1 attributedMessage:(id)arg2;
+ (id)alertControllerWithTitle:(id)arg1 message:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *actions; // @synthesize actions=_actions;
- (void)addAction:(id)arg1;
@property(retain, nonatomic) YNAlertAnimation *animation; // @synthesize animation=_animation;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(retain, nonatomic) NSAttributedString *attributedMessage; // @synthesize attributedMessage=_attributedMessage;
@property(retain, nonatomic) NSAttributedString *attributedTitle; // @synthesize attributedTitle=_attributedTitle;
- (void)configureView;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void)dealloc;
- (id)initWithAttributedTitle:(id)arg1 attributedMessage:(id)arg2;
@property(nonatomic) unsigned long long maxActionCount; // @synthesize maxActionCount=_maxActionCount;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(nonatomic) long long messageAlignment; // @synthesize messageAlignment=_messageAlignment;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long titleAlignment; // @synthesize titleAlignment=_titleAlignment;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

