//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class UIView;

@interface YNAlertWindow : UIWindow
{
    UIView *_alertView;
}

+ (id)currentAlertWindow;
+ (id)windowWithController:(id)arg1;
+ (id)windowWithView:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *alertView; // @synthesize alertView=_alertView;
- (void)becomeKeyWindow;
- (void)dealloc;
- (void)dismiss;
- (id)init;
- (void)resignKeyWindow;
- (void)show;
- (void)tapAction:(id)arg1;

@end

