//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YNAudioManager;

@protocol YNAudioManagerDelegate <NSObject>

@optional
- (void)audioManager:(YNAudioManager *)arg1 didRecordTime:(long long)arg2;
- (void)audioManager:(YNAudioManager *)arg1 didRecordTooLongAudio:(long long)arg2;
- (void)audioManager:(YNAudioManager *)arg1 didVolumeChanged:(double)arg2;
- (void)audioManager:(YNAudioManager *)arg1 playingPosition:(double)arg2;
- (void)audioManagerAudioSessionBeginInterruption:(YNAudioManager *)arg1;
- (void)audioManagerAudioSessionEndInterruption:(YNAudioManager *)arg1;
- (void)audioManagerDidFinishedPlayAudio:(YNAudioManager *)arg1;
- (void)audioManagerDidStartRecording:(YNAudioManager *)arg1;
@end

