//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "YNAudioManagerDelegate.h"

@class NSString, NSTimer, UIActivityIndicatorView, UIImageView, UILabel;

@interface YNAudioRecordingView : UIView <YNAudioManagerDelegate, UIGestureRecognizerDelegate>
{
    _Bool _hasRecordEnoughTimeToSend;
    _Bool _hasShowInWindow;
    int _status;
    id <YNAudioRecordingViewDelegate> _delegate;
    UIView *_middleView;
    UIImageView *_recordingImageView;
    UIImageView *_lineImageView;
    UIImageView *_middleImageView;
    UIImageView *_revokeImageView;
    UILabel *_infoLabel;
    UILabel *_alertLabel;
    UILabel *_countDownLabel;
    NSTimer *_tooShordTimer;
    UIActivityIndicatorView *_activityIndicatorView;
    NSString *_currentRecordVolumeImageName;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UILabel *alertLabel; // @synthesize alertLabel=_alertLabel;
- (void)audioManager:(id)arg1 didRecordTime:(long long)arg2;
- (void)audioManager:(id)arg1 didRecordTooLongAudio:(long long)arg2;
- (void)audioManagerAudioSessionBeginInterruption:(id)arg1;
- (void)audioManagerDidStartRecording:(id)arg1;
@property(retain, nonatomic) UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(retain, nonatomic) NSString *currentRecordVolumeImageName; // @synthesize currentRecordVolumeImageName=_currentRecordVolumeImageName;
- (void)dealloc;
@property(nonatomic) __weak id <YNAudioRecordingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)hasRecordEnoughTime;
@property(nonatomic) _Bool hasRecordEnoughTimeToSend; // @synthesize hasRecordEnoughTimeToSend=_hasRecordEnoughTimeToSend;
@property(nonatomic) _Bool hasShowInWindow; // @synthesize hasShowInWindow=_hasShowInWindow;
- (void)hide;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)interruptionHide;
@property(retain, nonatomic) UIImageView *lineImageView; // @synthesize lineImageView=_lineImageView;
@property(retain, nonatomic) UIImageView *middleImageView; // @synthesize middleImageView=_middleImageView;
@property(retain, nonatomic) UIView *middleView; // @synthesize middleView=_middleView;
- (id)recordVolumeLevelImageNameForLaver:(double)arg1;
@property(retain, nonatomic) UIImageView *recordingImageView; // @synthesize recordingImageView=_recordingImageView;
- (void)removeFromSuperviewAndStopRecord;
@property(retain, nonatomic) UIImageView *revokeImageView; // @synthesize revokeImageView=_revokeImageView;
@property(nonatomic) int status; // @synthesize status=_status;
@property(retain, nonatomic) NSTimer *tooShordTimer; // @synthesize tooShordTimer=_tooShordTimer;
- (void)setupViewConstraints;
- (void)show;
- (void)showMiddleView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

