//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, YNBadgeView;

@interface YNAvatarView : UIView
{
    UIImageView *_avatarImageView;
    YNBadgeView *_badgeView;
    UIView *_smallBadgeView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) YNBadgeView *badgeView; // @synthesize badgeView=_badgeView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)isShowSmallBadge:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setBadgeText:(id)arg1;
@property(retain, nonatomic) UIView *smallBadgeView; // @synthesize smallBadgeView=_smallBadgeView;
- (void)showBadge:(_Bool)arg1;
- (void)updateBadgeFrame;

@end

