//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIActivityIndicatorView, UIImageView, UILabel;

@interface YNBaseNavActivityIndicatorTitleView : UIView
{
    _Bool _isPlayEarphoneMode;
    UIActivityIndicatorView *_activityIndicatorView;
    UILabel *_titleLabel;
    NSLayoutConstraint *_constraintLocation;
    UIImageView *_describeImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) NSLayoutConstraint *constraintLocation; // @synthesize constraintLocation=_constraintLocation;
@property(retain, nonatomic) UIImageView *describeImageView; // @synthesize describeImageView=_describeImageView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isPlayEarphoneMode; // @synthesize isPlayEarphoneMode=_isPlayEarphoneMode;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setupViewConstraints;

@end

