//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface YNBadgeView : UIView
{
    UILabel *_textLabel;
    double _minimumWidth;
    double _maximumWidth;
}

- (void).cxx_destruct;
- (void)hideWhenZero;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(nonatomic) double minimumWidth; // @synthesize minimumWidth=_minimumWidth;
- (void)setText:(id)arg1;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void)setup;
- (struct CGSize)sizeForString:(id)arg1;
- (void)updateBadgeFrame;

@end

