//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNTableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface YNBaseInfoTableViewCell : YNTableViewCell
{
    _Bool _isNew;
    UILabel *_infoLabel;
    UIImageView *_reminderImageView;
    UIView *_topLine;
    UIView *_bottomLine;
}

+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
@property(retain, nonatomic) UIImageView *reminderImageView; // @synthesize reminderImageView=_reminderImageView;
@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
- (void)setupViewConstraints;

@end

