//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNTableViewCell.h"

@class NSLayoutConstraint, UIButton, UILabel;

@interface YNBaseTagInfoTableViewCell : YNTableViewCell
{
    _Bool _isNew;
    UILabel *_tagLabel;
    UILabel *_infoLabel;
    UIButton *_reminderButton;
    NSLayoutConstraint *_infoLabelLConstraint;
}

+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain) NSLayoutConstraint *infoLabelLConstraint; // @synthesize infoLabelLConstraint=_infoLabelLConstraint;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
@property(retain, nonatomic) UIButton *reminderButton; // @synthesize reminderButton=_reminderButton;
- (void)setAccessoryType:(long long)arg1;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
- (void)setupViewConstraints;

@end

