//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MASConstraint, NSString, UIFont, UIImageView, UILabel;

@interface YNBeseNavStateTitleView : UIView
{
    UIView *_backgroundView;
    UILabel *_titleLabel;
    double _maxWidth;
    double _allWidth;
    _Bool _isNotDisturb;
    _Bool _isPlayEarphoneMode;
    NSString *_title;
    NSString *_describeTitle;
    NSString *_subTitle;
    UILabel *_numberLabel;
    UIImageView *_describeImageView;
    UILabel *_subTitleLabel;
    double _maxX;
    UIFont *_titleFont;
    MASConstraint *_titleLabelTopConstraint;
    MASConstraint *_titleLabelCenterYConstraint;
}

- (void).cxx_destruct;
- (void)adjustBackgroundViewLayout;
- (void)adjustBounds;
- (void)adjustSubTitleLabelLayout;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)dealloc;
@property(retain, nonatomic) UIImageView *describeImageView; // @synthesize describeImageView=_describeImageView;
@property(retain, nonatomic) NSString *describeTitle; // @synthesize describeTitle=_describeTitle;
- (double)getAttributedStringWidth:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
@property(nonatomic) _Bool isNotDisturb; // @synthesize isNotDisturb=_isNotDisturb;
@property(nonatomic) _Bool isPlayEarphoneMode; // @synthesize isPlayEarphoneMode=_isPlayEarphoneMode;
- (void)layoutSubviews;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) double maxX; // @synthesize maxX=_maxX;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MASConstraint *titleLabelCenterYConstraint; // @synthesize titleLabelCenterYConstraint=_titleLabelCenterYConstraint;
@property(retain, nonatomic) MASConstraint *titleLabelTopConstraint; // @synthesize titleLabelTopConstraint=_titleLabelTopConstraint;
- (void)setupViewConstraints;
- (void)updateConstraintsWithLeftButtonMaxX:(double)arg1 maxWidth:(double)arg2 title:(id)arg3 describeTitle:(id)arg4 subTitle:(id)arg5 isNotDisturb:(_Bool)arg6 isPlayEarphoneMode:(_Bool)arg7;
- (id)updateDescribeImageView;
- (void)updateLayout;

@end

