//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNPersonListViewController.h"

@interface YNBlockedListViewController : YNPersonListViewController
{
}

- (_Bool)canEditRows;
- (void)commitEditingStyleForObject:(id)arg1;
- (void)dealloc;
- (void)didEditedFriend:(id)arg1;
- (void)didFinishedSyncFriends:(id)arg1;
- (void)didSelectCellWithObject:(id)arg1;
- (_Bool)filterObject:(id)arg1 withSearchString:(id)arg2;
- (void)friendsManagerDidChangeBlackList:(id)arg1;
- (id)prepareDataSource;
- (id)rightButtonTitle;
- (void)viewDidLoad;

@end

