//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "YNBottleBoardViewDelegate.h"
#import "YNBottleMainBackgroudViewDelegate.h"
#import "YNChatCenterDelegate.h"
#import "YNPickBottleViewControllerDelegate.h"
#import "YNSendBottleViewControllerDelegate.h"
#import "YNSlideWelcomeViewControllerDelegate.h"

@class NSString, YNBottleBoardView, YNBottleMainBackgroudView, YNBottleRequestParameter, YNLocationManager;

@interface YNBottleMainViewController : YNBaseViewController <YNBottleMainBackgroudViewDelegate, YNBottleBoardViewDelegate, YNSendBottleViewControllerDelegate, YNPickBottleViewControllerDelegate, YNChatCenterDelegate, YNSlideWelcomeViewControllerDelegate>
{
    _Bool _fromAutoPush;
    _Bool _bSlideSending;
    _Bool _isNotTimesPick;
    _Bool _isNotTimesThrow;
    YNBottleRequestParameter *_requestParameter;
    YNBottleMainBackgroudView *_bottleBackgroudView;
    YNBottleBoardView *_bottleBoardView;
    YNLocationManager *_locationManager;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool bSlideSending; // @synthesize bSlideSending=_bSlideSending;
@property(retain, nonatomic) YNBottleMainBackgroudView *bottleBackgroudView; // @synthesize bottleBackgroudView=_bottleBackgroudView;
@property(retain, nonatomic) YNBottleBoardView *bottleBoardView; // @synthesize bottleBoardView=_bottleBoardView;
- (void)bottleMainBackgroudViewClicked;
- (void)changeNavBarHidden:(_Bool)arg1;
- (void)checkAndJumpToTongFuDunVc:(id)arg1;
- (void)dealloc;
- (void)drawView;
@property(nonatomic) _Bool fromAutoPush; // @synthesize fromAutoPush=_fromAutoPush;
- (void)getLbsInfo;
- (id)init;
- (void)initNaviBarItem;
@property _Bool isNotTimesPick; // @synthesize isNotTimesPick=_isNotTimesPick;
@property _Bool isNotTimesThrow; // @synthesize isNotTimesThrow=_isNotTimesThrow;
- (void)jumpNearbyPage;
- (void)jumpToPickBottleVC;
- (void)jumpToSendBottleVC;
@property(retain, nonatomic) YNLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void)myBottleButtonClicked;
- (void)onSucessToNext:(id)arg1;
- (void)pickBottleViewControllerEndUse:(id)arg1;
- (void)pickBottleViewControllerNotTimes:(id)arg1;
- (void)pickBottleViewControllerOpenUrl:(id)arg1 withUrl:(id)arg2;
- (void)pickBottleViewControllerPickFail:(id)arg1 withAlertMsg:(id)arg2;
- (void)pickButtonClicked;
- (void)refreshConversation;
- (void)refreshMyBottleUnread;
@property(retain, nonatomic) YNBottleRequestParameter *requestParameter; // @synthesize requestParameter=_requestParameter;
- (void)resetCoversationConfig;
- (void)rightBarButtonItemClick:(id)arg1;
- (void)sendBottleViewControllerEndUse:(id)arg1;
- (void)sendBottleViewControllerNotTimes:(id)arg1;
- (void)sendBottleViewControllerSendFail:(id)arg1 withErrorMsg:(id)arg2;
- (void)setNavBarHidden;
- (void)showPickNotTimesAlert;
- (void)showThrowNotTimesAlert;
- (void)throwButtonClicked;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

