//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface YNBrowserNavigationBarStyle : NSObject
{
    _Bool _statusBarStyleBlack;
    _Bool _rightMenuHidden;
    UIColor *_barColor;
    UIColor *_barTextColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *barColor; // @synthesize barColor=_barColor;
@property(retain, nonatomic) UIColor *barTextColor; // @synthesize barTextColor=_barTextColor;
@property(nonatomic) _Bool rightMenuHidden; // @synthesize rightMenuHidden=_rightMenuHidden;
@property(nonatomic) _Bool statusBarStyleBlack; // @synthesize statusBarStyleBlack=_statusBarStyleBlack;

@end

