//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "ZMVCameraViewControllerDelegate.h"

@class NSString, ZMVCameraViewController;

@interface YNCameraViewController : YNBaseViewController <ZMVCameraViewControllerDelegate>
{
    _Bool _onlyPhoto;
    id <YNCameraViewControllerDelegate> _delegate;
    ZMVCameraViewController *_cameraVC;
}

- (void).cxx_destruct;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
@property(nonatomic) __weak ZMVCameraViewController *cameraVC; // @synthesize cameraVC=_cameraVC;
- (void)cameraVC:(id)arg1 photoCompleteWithStr:(id)arg2;
- (void)cameraVC:(id)arg1 videoCompleteWithStr:(id)arg2 imageStr:(id)arg3;
- (void)clickReturnBtnCameraVC:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <YNCameraViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithOnlyPhoto:(_Bool)arg1;
@property(nonatomic) _Bool onlyPhoto; // @synthesize onlyPhoto=_onlyPhoto;
- (void)photoDidPreviewWithCameraVC:(id)arg1;
- (void)previewReturnRecordWithCameraVC:(id)arg1;
- (void)showCameraDisableAlert;
- (void)showToast;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

