//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIButton, UIGestureRecognizer, UIImageView, UITapGestureRecognizer, YNChatActionMessageCell, YNChatCellViewModel, YNChatFileMessageCell, YNChatFriendCardMessageCell, YNChatLocationMessage, YNChatLocationMessageCell, YNChatNewAudioMessageCell, YNChatRichTextMessageCell, YNChatTableViewBaseCell, YNChatVoipMessageCell, YNLinkParseResult;

@protocol YNChatTableViewBaseCellDelegate <NSObject>
- (void)didClickLocationMessageCell:(YNChatLocationMessageCell *)arg1 withLocationMessage:(YNChatLocationMessage *)arg2;
- (void)didClickedDownloadCancelButton:(UIButton *)arg1 cell:(YNChatTableViewBaseCell *)arg2 withChatSource:(YNChatCellViewModel *)arg3;
- (void)didClickedSendRetryButton:(UIButton *)arg1 cell:(YNChatTableViewBaseCell *)arg2 withChatSource:(YNChatCellViewModel *)arg3;
- (void)didClickedUrlInCell:(YNChatTableViewBaseCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 withLink:(YNLinkParseResult *)arg3;
- (void)didDragAudioProgressBarIncell:(YNChatNewAudioMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 withProgress:(double)arg3;
- (void)didLongPressedCell:(YNChatTableViewBaseCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 gesture:(UIGestureRecognizer *)arg3;
- (void)didLongPressedUrlInCell:(YNChatTableViewBaseCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 withLink:(YNLinkParseResult *)arg3;
- (void)didLongedUserAvatarInCell:(YNChatTableViewBaseCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2;
- (void)didPauseAudioPlayIncell:(YNChatNewAudioMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2;
- (void)didSingleTapCell:(YNChatTableViewBaseCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2;
- (void)didTapTwoCell:(YNChatTableViewBaseCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 gesture:(UITapGestureRecognizer *)arg3;
- (void)didTapedActionUrlInCell:(YNChatActionMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 url:(NSString *)arg3;
- (void)didTapedChatFriendCardMessageCell:(YNChatFriendCardMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2;
- (void)didTapedFileMessageInCell:(YNChatFileMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2;
- (void)didTapedImageView:(UIImageView *)arg1 cell:(YNChatTableViewBaseCell *)arg2 withChatSource:(YNChatCellViewModel *)arg3;
- (void)didTapedPlayRecordIncell:(YNChatNewAudioMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2;
- (void)didTapedRichTextMessageCell:(YNChatRichTextMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 url:(NSString *)arg3;
- (void)didTapedUserAvatarInCell:(YNChatTableViewBaseCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2;
- (void)didTapedVoipMessageCell:(YNChatVoipMessageCell *)arg1 withChatSource:(YNChatCellViewModel *)arg2 voipCallType:(unsigned long long)arg3;
@end

