//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, YNChatRoomNameSettingViewController;

@protocol YNChatRoomNameSettingViewControllerDelegate <NSObject>
- (void)didCancelChangeChatRoomName:(YNChatRoomNameSettingViewController *)arg1;
- (void)didFinishedChangeChatRoomName:(YNChatRoomNameSettingViewController *)arg1 chatRoomName:(NSString *)arg2;
@end

