//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNChatMessage.h"

@interface YNChatFileMessage : YNChatMessage
{
}

- (_Bool)canBeSend;
- (void)clearCacheResource;
- (void)clearMediaResource;
- (void)copyMessageResourceToMessage:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)deleteLocalFile;
- (void)deleteLocalImageData;
- (id)fileIconImageNameIsBigImage:(_Bool)arg1;
- (id)fileRecourcePath;
- (id)fileRecourceUploadTempPath;
- (id)forwardShowText;
- (id)getLastPathComponent;
- (id)getPostfixIconStr;
- (id)initWithFMResultSet:(id)arg1;
- (_Bool)isArrayContainIndexString:(id)arg1 array:(id)arg2;
- (_Bool)isZipFile;
- (void)prepareForForwardMedia;
- (void)prepareForUploadMedia:(CDUnknownBlockType)arg1;
- (id)reportInfo;
- (_Bool)resourceExists;
- (void)setFileName:(id)arg1;
- (void)setFilePath:(id)arg1;
- (void)setFileSize:(double)arg1;
- (void)setFileUrl:(id)arg1;
- (void)setHasUploadPartData:(_Bool)arg1;
- (void)setLocalMD5:(id)arg1;
- (void)setLongURL:(id)arg1;
- (void)setMd5:(id)arg1;
- (id)showText;
- (id)showTextLocalizationKey;
- (id)textWithSending;
- (id)toProtobufMessageBuilder;
- (void)updateWithMessage:(id)arg1;

@end

