//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UIImageView, UILabel, YNAvatarView;

@interface YNChatInfoMemberItemCell : UICollectionViewCell
{
    id <YNChatInfoMemberItemCellDelegate> _delegate;
    YNAvatarView *_avatarImageView;
    UIImageView *_avatarMaskImageView;
    UILabel *_nameLabel;
    UIButton *_operationButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) YNAvatarView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIImageView *avatarMaskImageView; // @synthesize avatarMaskImageView=_avatarMaskImageView;
- (void)configureWithItem:(id)arg1;
@property(nonatomic) __weak id <YNChatInfoMemberItemCellDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)itemTapAction:(id)arg1;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIButton *operationButton; // @synthesize operationButton=_operationButton;
- (void)setupViewConstraints;

@end

