//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "FloatViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "YNChatRoomCreateFriendsPickerTopViewDelegate.h"
#import "YNChatRoomListViewControllerDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, YNChatRoomCreateFriendsPickerTopView, YNChatRoomFloatView, YNSendFriendApplyManage, YNTableView;

@interface YNChatRoomCreateFriendsPickerViewController : YNBaseViewController <UITableViewDelegate, UITableViewDataSource, YNChatRoomCreateFriendsPickerTopViewDelegate, YNChatRoomListViewControllerDelegate, UIAlertViewDelegate, FloatViewDelegate>
{
    YNSendFriendApplyManage *sendFriendApplyManage;
    _Bool _includeMe;
    _Bool _selectFriendsChanged;
    id <YNChatRoomCreateFriendsPickerViewControllerDelegate> _delegate;
    NSMutableArray *_excluedFriendsUid;
    long long _VCInfo;
    unsigned long long _roomCount;
    YNTableView *_tableView;
    NSMutableArray *_friendsArray;
    NSMutableDictionary *_friendsDataSource;
    NSMutableArray *_sectionsArray;
    NSMutableArray *_selectedFriendsArray;
    YNChatRoomCreateFriendsPickerTopView *_topSearchView;
    NSArray *_failFriendArray;
    NSString *_currentRequstId;
    YNChatRoomFloatView *_flaotView;
}

- (void).cxx_destruct;
@property(nonatomic) long long VCInfo; // @synthesize VCInfo=_VCInfo;
- (void)addFriendsFinished;
- (void)chatRoomCreateFriendPickerCancelClicked:(id)arg1;
- (void)chatRoomFriendPickerOKClicked:(id)arg1;
@property(retain, nonatomic) NSString *currentRequstId; // @synthesize currentRequstId=_currentRequstId;
- (void)dealloc;
@property(nonatomic) __weak id <YNChatRoomCreateFriendsPickerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didClickedCancel:(id)arg1;
- (void)didDeletedResourceAtIndex:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)didSelectedChatRoom:(id)arg1 chatRoom:(id)arg2;
- (void)didSelectedResourceAtIndex:(long long)arg1;
@property(retain, nonatomic) NSMutableArray *excluedFriendsUid; // @synthesize excluedFriendsUid=_excluedFriendsUid;
@property(retain, nonatomic) NSArray *failFriendArray; // @synthesize failFriendArray=_failFriendArray;
@property(retain, nonatomic) YNChatRoomFloatView *flaotView; // @synthesize flaotView=_flaotView;
- (id)friendAtIndex:(id)arg1;
@property(retain, nonatomic) NSMutableArray *friendsArray; // @synthesize friendsArray=_friendsArray;
@property(retain, nonatomic) NSMutableDictionary *friendsDataSource; // @synthesize friendsDataSource=_friendsDataSource;
@property(nonatomic) _Bool includeMe; // @synthesize includeMe=_includeMe;
- (void)initFriendsDataSource;
- (void)initNaviBarItem;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)removeFoatView;
- (id)resouceForSearchText:(id)arg1;
@property(nonatomic) unsigned long long roomCount; // @synthesize roomCount=_roomCount;
- (id)sectionIndexTitlesForTableView:(id)arg1;
@property(retain, nonatomic) NSMutableArray *sectionsArray; // @synthesize sectionsArray=_sectionsArray;
- (void)selectChatRoom;
@property(nonatomic) _Bool selectFriendsChanged; // @synthesize selectFriendsChanged=_selectFriendsChanged;
@property(retain, nonatomic) NSMutableArray *selectedFriendsArray; // @synthesize selectedFriendsArray=_selectedFriendsArray;
@property(retain, nonatomic) YNTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) YNChatRoomCreateFriendsPickerTopView *topSearchView; // @synthesize topSearchView=_topSearchView;
- (void)setupViewConstraints;
- (void)showAddFriendsToChatRoomFailAlertWithFriendArray:(id)arg1;
- (void)showSendFriendApplyWithFriendArray:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)transitionString:(id)arg1;
- (void)updateButtonStatus;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

