//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNChatMessage.h"

@interface YNChatRoomCardMessage : YNChatMessage
{
}

+ (id)extensionDictionaryForChatRoom:(id)arg1;
- (id)cardCode;
- (id)chatRoomCardModel;
- (void)confitureFromInfo;
- (id)notificationBody;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)reportInfo;
- (void)setExtensionDic:(id)arg1;
- (id)showText;
- (id)textWithSending;
- (id)toProtobufMessageBuilder;

@end

