//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface YNChatConversationInfo : NSObject
{
    NSString *_ownerId;
    NSMutableDictionary *_info;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *info; // @synthesize info=_info;
- (id)initWithFMResultSet:(id)arg1;
- (id)initWithOwnerId:(id)arg1;
@property(retain, nonatomic) NSString *ownerId; // @synthesize ownerId=_ownerId;

@end

