//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SwipeViewDataSource.h"
#import "SwipeViewDelegate.h"
#import "YNChatInputSwitchViewDelegate.h"

@class NSArray, NSMutableArray, NSString, SwipeView;

@interface YNChatInputSwitchView : UIView <SwipeViewDelegate, SwipeViewDataSource, YNChatInputSwitchViewDelegate>
{
    _Bool _isShowInputSwitch;
    id <YNChatInputSwitchViewDelegate> _delegate;
    SwipeView *_swipePageView;
    NSArray *_inputSourceTypes;
    NSMutableArray *_chatInputSourceArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *chatInputSourceArray; // @synthesize chatInputSourceArray=_chatInputSourceArray;
@property(nonatomic) __weak id <YNChatInputSwitchViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didClickedInputSwitchView:(id)arg1 withType:(int)arg2;
- (id)getChatInputItemSourceForType:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSArray *inputSourceTypes; // @synthesize inputSourceTypes=_inputSourceTypes;
@property(nonatomic) _Bool isShowInputSwitch; // @synthesize isShowInputSwitch=_isShowInputSwitch;
- (void)layoutSubviews;
- (long long)numberOfItemsInSwipeView:(id)arg1;
- (void)reloadData;
@property(retain, nonatomic) SwipeView *swipePageView; // @synthesize swipePageView=_swipePageView;
- (void)setupViewConstraints;
- (id)swipeView:(id)arg1 viewForItemAtIndex:(long long)arg2 reusingView:(id)arg3;
- (struct CGSize)swipeViewItemSize:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

