//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

@class YNChatMessage;

@interface YNChatMediaBaseController : YNBaseViewController
{
    id <YNChatMediaBaseControllerDelegate> _delegate;
    YNChatMessage *_message;
}

+ (id)mediaViewControllerByMessage:(id)arg1;
- (void).cxx_destruct;
- (void)clickAndPanPlayBtn:(_Bool)arg1;
@property(nonatomic) __weak id <YNChatMediaBaseControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (id)getDisplayImageView;
- (id)initWithMessage:(id)arg1;
- (void)mediaViewWillActive;
- (void)mediaViewWillResignActive;
@property(retain, nonatomic) YNChatMessage *message; // @synthesize message=_message;
- (void)notifyOtherAppActiveState;
- (void)startDownloadMeidaFile;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

