//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface YNChatFirstEnterView : UIView
{
    UIButton *_applyButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *applyButton; // @synthesize applyButton=_applyButton;
- (id)initWithFrame:(struct CGRect)arg1;

@end

