//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "YNChatInfoMemberProtocol.h"

@class NSMutableDictionary, NSString, YNFriend;

@interface YNChatRoomMember : NSObject <YNChatInfoMemberProtocol, NSCopying>
{
    _Bool _isSelect;
    int _type;
    YNFriend *_myFriend;
    NSString *_chatRoomID;
    NSString *_uid;
    long long _index;
    NSString *_avatarImageUrl;
    NSString *_avatarThumbnailImageUrl;
    NSString *_nickName;
    NSString *_nameForChatRoom;
    NSString *_short_piny;
    NSString *_long_piny;
    NSString *_updateTime;
    NSString *_addBy;
    NSMutableDictionary *_info;
    NSString *_zhangxinID;
    NSString *_sectionLetter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *addBy; // @synthesize addBy=_addBy;
@property(retain, nonatomic) NSString *avatarImageUrl; // @synthesize avatarImageUrl=_avatarImageUrl;
@property(retain, nonatomic) NSString *avatarThumbnailImageUrl; // @synthesize avatarThumbnailImageUrl=_avatarThumbnailImageUrl;
@property(retain, nonatomic) NSString *chatRoomID; // @synthesize chatRoomID=_chatRoomID;
- (void)configureWithDic:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) NSMutableDictionary *info; // @synthesize info=_info;
- (id)init;
- (void)initPinyinProperty;
- (id)initWithChatRoomID:(id)arg1;
- (id)initWithFMResultSet:(id)arg1;
@property(nonatomic) _Bool isSelect; // @synthesize isSelect=_isSelect;
@property(retain, nonatomic) NSString *long_piny; // @synthesize long_piny=_long_piny;
@property(retain, nonatomic) YNFriend *myFriend; // @synthesize myFriend=_myFriend;
@property(retain, nonatomic) NSString *nameForChatRoom; // @synthesize nameForChatRoom=_nameForChatRoom;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
- (id)remindShowName;
@property(retain, nonatomic) NSString *sectionLetter; // @synthesize sectionLetter=_sectionLetter;
@property(retain, nonatomic) NSString *short_piny; // @synthesize short_piny=_short_piny;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(retain, nonatomic) NSString *updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) NSString *zhangxinID; // @synthesize zhangxinID=_zhangxinID;
- (id)showName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

