//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface YNChatMaskImageView : UIImageView
{
    _Bool _isSendByMe;
    UIImageView *_maskImageView;
    UIImageView *_chatImageMaskView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *chatImageMaskView; // @synthesize chatImageMaskView=_chatImageMaskView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isSendByMe; // @synthesize isSendByMe=_isSendByMe;
@property(retain, nonatomic) UIImageView *maskImageView; // @synthesize maskImageView=_maskImageView;
- (void)setImage:(id)arg1;
- (void)updateLayout;

@end

