//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTextAttachment, YNChatTextMessageBubbleView, YNLinkParseResult;

@protocol YNChatTextMessageBubbleViewDelegate <NSObject>
- (void)didInteractWithTextAttachment:(NSTextAttachment *)arg1 inRange:(struct _NSRange)arg2;
- (void)textBubbleView:(YNChatTextMessageBubbleView *)arg1 didClickedLink:(YNLinkParseResult *)arg2;
- (void)textBubbleView:(YNChatTextMessageBubbleView *)arg1 didLongPressedLink:(YNLinkParseResult *)arg2;
@end

