//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YNChatEditToolbar;

@protocol YNChatEditToolbarDelegate <NSObject>

@optional
- (void)editToolbar:(YNChatEditToolbar *)arg1 didClickedCollect:(id)arg2;
- (void)editToolbar:(YNChatEditToolbar *)arg1 didClickedDelete:(id)arg2;
- (void)editToolbar:(YNChatEditToolbar *)arg1 didClickedForward:(id)arg2;
- (void)editToolbar:(YNChatEditToolbar *)arg1 didClickedMore:(id)arg2;
@end

