//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer;

@interface YNCircleProgressView : UIView
{
    CAShapeLayer *_borderLayer;
    CAShapeLayer *_progressLayer;
    double _radius;
}

- (void).cxx_destruct;
- (id)borderPathWithRadius:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)progressPathWithRadius:(double)arg1 progressValue:(double)arg2;
- (void)updateProgress:(double)arg1;

@end

