//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView, UILabel;

@interface YNCountryCodeSelecteButton : UIButton
{
    UILabel *_countryTagLabel;
    UILabel *_countryNameLabel;
    UIImageView *_accessoryImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *accessoryImageView; // @synthesize accessoryImageView=_accessoryImageView;
@property(retain, nonatomic) UILabel *countryNameLabel; // @synthesize countryNameLabel=_countryNameLabel;
@property(retain, nonatomic) UILabel *countryTagLabel; // @synthesize countryTagLabel=_countryTagLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setupViewConstraints;

@end

