//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YNContactFriendInfo : NSObject
{
    NSString *_firstNickname;
    NSString *_firstPhone;
    NSString *_firstIconUrl;
    NSString *_total;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *firstIconUrl; // @synthesize firstIconUrl=_firstIconUrl;
@property(retain, nonatomic) NSString *firstNickname; // @synthesize firstNickname=_firstNickname;
@property(retain, nonatomic) NSString *firstPhone; // @synthesize firstPhone=_firstPhone;
@property(retain, nonatomic) NSString *total; // @synthesize total=_total;

@end

