//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Message, NSMutableDictionary, NSString, YNChatMessage, YNCommunicationManager;

@protocol YNCommunicationManagerDelegate <NSObject>

@optional
- (void)YNCommunicationManagerDidConnectForFirstTimeAfterLaunch:(YNCommunicationManager *)arg1;
- (void)YNCommunicationManagerRequireLogout:(YNCommunicationManager *)arg1;
- (void)YNCommunicationManagerRequireSync:(YNCommunicationManager *)arg1;
- (void)YNCommunicationManagerUnableToConnect:(YNCommunicationManager *)arg1;
- (void)didReceivedSyncServerTimeStamp:(double)arg1;
- (void)handleMessage:(Message *)arg1;
- (void)messageDidError:(NSString *)arg1 error:(NSString *)arg2;
- (void)messageDidInputingIQ:(NSString *)arg1;
- (void)messageDidOnlineIQ:(NSMutableDictionary *)arg1;
- (void)messageDidSendFailure:(YNChatMessage *)arg1;
- (void)messageDidSendSuccess:(YNChatMessage *)arg1;
- (void)serverStatusChanged:(YNCommunicationManager *)arg1 withStatus:(int)arg2;
@end

