//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseConfig.h"

@class NSString;

@interface YNContactConfig : YNBaseConfig
{
    NSString *_nearbyBannerTip;
    NSString *_threadBannerTip;
}

- (void).cxx_destruct;
- (void)handleConfigData:(id)arg1;
@property(copy) NSString *nearbyBannerTip; // @synthesize nearbyBannerTip=_nearbyBannerTip;
@property(copy) NSString *threadBannerTip; // @synthesize threadBannerTip=_threadBannerTip;

@end

