//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "YNContactsCardShowMoreCollectionCellDelegate.h"
#import "YNContactsFriendsRecCardCollectionCellDelegate.h"

@class NSMutableArray, NSString, UICollectionView, UILabel;

@interface YNContactsFriendsRecommendCardView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, YNContactsFriendsRecCardCollectionCellDelegate, YNContactsCardShowMoreCollectionCellDelegate>
{
    _Bool _needToScroll;
    id <YNContactsFriendsRecommendCardViewDelegate> _delegate;
    UICollectionView *_cardCollectionView;
    long long _scrollToRow;
    UILabel *_lbRecTitle;
    NSMutableArray *_recFriendConversations;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UICollectionView *cardCollectionView; // @synthesize cardCollectionView=_cardCollectionView;
- (void)closeCardWithConversation:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)configureWithConversations:(id)arg1;
@property(nonatomic) __weak id <YNContactsFriendsRecommendCardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)gotoFriendsRecommendViewController;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *lbRecTitle; // @synthesize lbRecTitle=_lbRecTitle;
@property(nonatomic) _Bool needToScroll; // @synthesize needToScroll=_needToScroll;
@property(retain, nonatomic) NSMutableArray *recFriendConversations; // @synthesize recFriendConversations=_recFriendConversations;
@property(nonatomic) long long scrollToRow; // @synthesize scrollToRow=_scrollToRow;
- (void)showFriendApplyWithConversation:(id)arg1;
- (void)updateUnreadConversationNum:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

