//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UIImageView, UILabel, YNChatConversation;

@interface YNContactsFriendsRecCardCollectionCell : UICollectionViewCell
{
    id <YNContactsFriendsRecCardCollectionCellDelegate> _delegate;
    YNChatConversation *_conversation;
    unsigned long long _buttonType;
    UIImageView *_imvAvatar;
    UILabel *_lbNickName;
    UILabel *_lbSource;
    UIButton *_btnClose;
    UIButton *_btnAddNewFriend;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *btnAddNewFriend; // @synthesize btnAddNewFriend=_btnAddNewFriend;
@property(retain, nonatomic) UIButton *btnClose; // @synthesize btnClose=_btnClose;
@property(nonatomic) unsigned long long buttonType; // @synthesize buttonType=_buttonType;
- (void)closeCard;
- (void)configureWithConversation:(id)arg1;
@property(retain, nonatomic) YNChatConversation *conversation; // @synthesize conversation=_conversation;
@property(nonatomic) __weak id <YNContactsFriendsRecCardCollectionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *imvAvatar; // @synthesize imvAvatar=_imvAvatar;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *lbNickName; // @synthesize lbNickName=_lbNickName;
@property(retain, nonatomic) UILabel *lbSource; // @synthesize lbSource=_lbSource;
- (void)showSendFriendApplyViewController;

@end

