//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSRegularExpression.h"

@interface YNDataDetector : NSRegularExpression
{
    unsigned long long _type;
}

+ (id)detectorWithType:(unsigned long long)arg1;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;

@end

