//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

@class YNMeidaDisplayViewModel;

@interface YNDefaultMediaBaseViewController : YNBaseViewController
{
    id <YNDefaultMediaBaseViewControllerDelegate> _delegate;
    YNMeidaDisplayViewModel *_mediaViewModel;
}

+ (id)mediaViewControllerByMediaViewModel:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak id <YNDefaultMediaBaseViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (id)getDisplayImageView;
- (id)initWithMediaViewModel:(id)arg1;
@property(retain, nonatomic) YNMeidaDisplayViewModel *mediaViewModel; // @synthesize mediaViewModel=_mediaViewModel;
- (void)viewDidLoad;

@end

