//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNTableViewCell.h"

@class UILabel;

@interface YNDetailRemarkViewCell : YNTableViewCell
{
    UILabel *_tagLabel;
    UILabel *_infoLabel;
}

+ (id)cellIdentifier;
+ (double)heightForSignature:(id)arg1 withTableViewWidth:(float)arg2;
- (void).cxx_destruct;
- (void)awakeFromNib;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
- (void)setupViewConstraints;

@end

