//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YNDomainInfo : NSObject
{
    NSString *_domain;
    NSString *_ip;
    NSString *_port;
    unsigned long long _timestamp;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *domain; // @synthesize domain=_domain;
- (id)initWithFMResult:(id)arg1;
@property(retain, nonatomic) NSString *ip; // @synthesize ip=_ip;
- (id)parameterize;
@property(retain, nonatomic) NSString *port; // @synthesize port=_port;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;

@end

