//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "YNEmotionKeyboardGroupSelectViewDelegate.h"
#import "YNEmotionPageViewDelegate.h"
#import "YNStickerManagerDelegate.h"
#import "YNStickerManagerViewControllerDelegate.h"

@class NSArray, NSString, UIResponder<UITextInput>, YNEmotionKeyboardGroupSelectView, YNEmotionKeyboardViewCellPressedPopupView, YNEmotionPageView, YNStickerKeyboardViewCellPressedPopupView;

@interface YNEmotionKeyboardView : UIView <YNEmotionKeyboardGroupSelectViewDelegate, YNEmotionPageViewDelegate, YNStickerManagerViewControllerDelegate, YNStickerManagerDelegate>
{
    _Bool _isShowEmotiom;
    id <YNEmotionKeyboardViewDelegate> _delegate;
    UIResponder<UITextInput> *_textInput;
    NSArray *_emotionTypes;
    NSArray *_keyItemGroups;
    YNEmotionPageView *_pageView;
    YNEmotionKeyboardGroupSelectView *_groupSelectView;
    YNEmotionKeyboardViewCellPressedPopupView *_popupView;
    YNStickerKeyboardViewCellPressedPopupView *_stickerPopupView;
}

- (void).cxx_destruct;
- (void)YNEmotionPageView:(id)arg1 didScrollToEmotionGroup:(long long)arg2;
- (void)backspace;
- (void)checkIsAtCustomEmotionGroup;
- (void)dealloc;
@property(nonatomic) __weak id <YNEmotionKeyboardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)emotionDidChangeText:(id)arg1;
- (void)emotionGroupSelectView:(id)arg1 didClickedSendButton:(id)arg2;
- (void)emotionGroupSelectView:(id)arg1 didSelectIndex:(long long)arg2;
@property(retain, nonatomic) NSArray *emotionTypes; // @synthesize emotionTypes=_emotionTypes;
@property(retain, nonatomic) YNEmotionKeyboardGroupSelectView *groupSelectView; // @synthesize groupSelectView=_groupSelectView;
- (id)init;
- (void)initEmotionKeybaordKeyItem;
- (id)initWithEmotionTypes:(id)arg1;
- (void)initialize;
- (void)inputText:(id)arg1;
- (_Bool)isDeleteCharSetTextInputbar;
@property(nonatomic) _Bool isShowEmotiom; // @synthesize isShowEmotiom=_isShowEmotiom;
@property(retain, nonatomic) NSArray *keyItemGroups; // @synthesize keyItemGroups=_keyItemGroups;
- (void)keyItemTapped:(id)arg1;
- (struct CGRect)keyboardRect;
- (id)loadCustomStickerKeyItems;
@property(retain, nonatomic) YNEmotionPageView *pageView; // @synthesize pageView=_pageView;
@property(retain, nonatomic) YNEmotionKeyboardViewCellPressedPopupView *popupView; // @synthesize popupView=_popupView;
- (void)replaceTextInRange:(id)arg1 withText:(id)arg2;
- (void)replaceTextPostNotificationInRange:(id)arg1 withText:(id)arg2;
- (void)resetSendButtonText:(id)arg1;
@property(retain, nonatomic) YNStickerKeyboardViewCellPressedPopupView *stickerPopupView; // @synthesize stickerPopupView=_stickerPopupView;
- (void)setSubviewsHidden:(_Bool)arg1;
@property(nonatomic) __weak UIResponder<UITextInput> *textInput; // @synthesize textInput=_textInput;
- (void)setup;
- (void)setupViewConstraints;
- (void)showEmotionKeyboarCellPressedPopViewForCell:(id)arg1 inGounp:(id)arg2;
- (void)showStickerManagerPage;
- (void)stickerManager:(id)arg1 didAddSticker:(id)arg2;
- (void)stickerManager:(id)arg1 didUpdateSticker:(id)arg2;
- (void)stickerManagerVC:(id)arg1 didAddSticker:(id)arg2;
- (void)stickerManagerVCDidUpdateStickers:(id)arg1;
- (_Bool)textInputShouldReplaceTextInRange:(id)arg1 replacementText:(id)arg2;
- (void)updateSendButtonStatus:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

