//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, YNCustomSticker;

@interface YNEmotionKeyboardKeyItem : NSObject
{
    unsigned long long _itemType;
    NSString *_imageName;
    NSString *_textToInput;
    YNCustomSticker *_relatedSticker;
}

- (void).cxx_destruct;
- (id)image;
@property(copy, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
- (id)init;
@property(nonatomic) unsigned long long itemType; // @synthesize itemType=_itemType;
@property(retain, nonatomic) YNCustomSticker *relatedSticker; // @synthesize relatedSticker=_relatedSticker;
@property(copy, nonatomic) NSString *textToInput; // @synthesize textToInput=_textToInput;

@end

