//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YNForwardWindowSize : NSObject
{
    double _width;
    double _minHeight;
    double _maxHeight;
}

- (id)init;
@property(readonly, nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(readonly, nonatomic) double minHeight; // @synthesize minHeight=_minHeight;
@property(readonly, nonatomic) double width; // @synthesize width=_width;

@end

