//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNForwardBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "YNBrowserViewControllerDelegate.h"

@class NSArray, NSString, UILabel, YNChatRoom, YNDisplayLocationView;

@interface YNForwardContentPreviewController : YNForwardBaseViewController <YNBrowserViewControllerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    int _previewType;
    int _forwardType;
    NSArray *_messasges;
    YNChatRoom *_chatRoom;
    NSArray *_memberItems;
    UILabel *_titleLabel;
    YNDisplayLocationView *_locationView;
    struct CGSize _initialSize;
}

- (void).cxx_destruct;
- (void)addDeaulftViewWithText:(id)arg1;
- (void)addSubViewWithScale:(id)arg1;
- (void)back:(id)arg1;
- (void)browser:(id)arg1 didChangeTitle:(id)arg2;
@property(retain, nonatomic) YNChatRoom *chatRoom; // @synthesize chatRoom=_chatRoom;
@property(nonatomic) int forwardType; // @synthesize forwardType=_forwardType;
- (void)initContentViewForChatRoomMember;
- (void)initContentViewForMessage;
- (void)initSubViews;
- (id)initWithChatRoom:(id)arg1;
- (id)initWithMessages:(id)arg1 forwardType:(int)arg2;
@property(nonatomic) struct CGSize initialSize; // @synthesize initialSize=_initialSize;
@property(retain, nonatomic) YNDisplayLocationView *locationView; // @synthesize locationView=_locationView;
@property(retain, nonatomic) NSArray *memberItems; // @synthesize memberItems=_memberItems;
@property(retain, nonatomic) NSArray *messasges; // @synthesize messasges=_messasges;
@property(nonatomic) int previewType; // @synthesize previewType=_previewType;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

