//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, NSMutableArray;

@interface YNGifImageTicker : NSObject
{
    CADisplayLink *_timer;
    NSMutableArray *_gifImageViews;
}

+ (id)sharedTicker;
- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) NSMutableArray *gifImageViews; // @synthesize gifImageViews=_gifImageViews;
- (id)init;
- (void)startTimer;
- (void)stopTimer;
- (void)tick;
- (void)tickView:(id)arg1;
- (void)unTickView:(id)arg1;

@end

