//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNChatCellViewModel.h"

@interface YNImageCellViewModel : YNChatCellViewModel
{
}

+ (Class)cellForClass;
+ (id)cellForIdentifier;
- (_Bool)canBeSelected;
- (double)heightForChatCell;

@end

