//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "SLKTextInputbarDelegate.h"
#import "UITextViewDelegate.h"
#import "YNEmotionKeyboardViewDelegate.h"

@class NSString, SLKTextInputbar, UITextView, UIWindow, YNEmotionKeyboardView;

@interface YNInputBarViewController : YNBaseViewController <SLKTextInputbarDelegate, YNEmotionKeyboardViewDelegate, UITextViewDelegate>
{
    _Bool _alwaysShowInputBar;
    double _currentTotalHeight;
    SLKTextInputbar *_textInputBar;
    YNEmotionKeyboardView *_emotionKeyboard;
    double _bottomOffset;
    double _currentInputBarHeight;
    UIWindow *_currentWindow;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool alwaysShowInputBar; // @synthesize alwaysShowInputBar=_alwaysShowInputBar;
- (double)appropriateInputbarHeight;
@property(nonatomic) double bottomOffset; // @synthesize bottomOffset=_bottomOffset;
@property(nonatomic) double currentInputBarHeight; // @synthesize currentInputBarHeight=_currentInputBarHeight;
@property(readonly, nonatomic) double currentTotalHeight; // @synthesize currentTotalHeight=_currentTotalHeight;
@property(retain, nonatomic) UIWindow *currentWindow; // @synthesize currentWindow=_currentWindow;
- (void)dealloc;
- (double)deltaInputbarHeight;
- (void)didChangeInputBarContentSize:(double)arg1 totalHeight:(double)arg2;
- (void)didChangeInputBarTotalHeight:(double)arg1;
- (void)didChangeTextViewContentSize:(id)arg1;
- (void)didTapSendButtonWithText:(id)arg1;
@property(retain, nonatomic) YNEmotionKeyboardView *emotionKeyboard; // @synthesize emotionKeyboard=_emotionKeyboard;
- (void)emotionKeyboardView:(id)arg1 didClickedSendButton:(id)arg2;
- (void)emotionKeyboardView:(id)arg1 didSelectEmotionKeyItem:(id)arg2;
- (void)hiddenInputBar;
- (void)initInputBar:(int)arg1;
- (void)initInputBar:(int)arg1 alwaysShowInputBar:(_Bool)arg2;
@property(nonatomic) _Bool inputBarEnabled;
- (double)inputBarHeightForLines:(unsigned long long)arg1;
@property(nonatomic) __weak UITextView *inputBarTextView;
@property(readonly, nonatomic) _Bool isShowInputBar;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (double)minimumInputbarHeight;
- (void)resetPlaceholder:(id)arg1;
- (void)resetSendButtonText:(id)arg1;
@property(retain, nonatomic) SLKTextInputbar *textInputBar; // @synthesize textInputBar=_textInputBar;
- (_Bool)shouldClearTextAfterTapSendButton;
- (void)showInputBar;
- (void)textInputbar:(id)arg1 didChangeInputType:(int)arg2;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)viewDidLoad;
- (_Bool)willSendText:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

