//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class NSString;

@interface YNInstructTextField : UITextField
{
    NSString *_instructStr;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *instructStr; // @synthesize instructStr=_instructStr;
- (struct CGRect)leftViewRectForBounds:(struct CGRect)arg1;

@end

