//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBundle, NSString;

@interface YNLanguage : NSObject
{
    NSBundle *_languageBundle;
    NSString *_currentLanguage;
}

+ (id)currentSystemLanguage;
+ (id)getCurrentRegion;
+ (_Bool)isChineseLanguage;
+ (id)shareLanguage;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *currentLanguage; // @synthesize currentLanguage=_currentLanguage;
- (void)initUserLanguage;
- (id)locatizedStringForkey:(id)arg1;
- (void)switchLanguage:(id)arg1;

@end

