//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNScrollContainerViewController.h"

#import "RegisterCountryCodePickerDelegate.h"
#import "UITextFieldDelegate.h"
#import "YNRegisterManagerDelegate.h"
#import "YNWOARegsterManagerDelegate.h"

@class NSString, UIButton, UILabel, YNCountryCodeSelecteButton, YNPhoneNumberInputView, YNRegisterTopView;

@interface YNLoginWithCodeViewController : YNScrollContainerViewController <RegisterCountryCodePickerDelegate, UITextFieldDelegate, YNRegisterManagerDelegate, YNWOARegsterManagerDelegate>
{
    NSString *_phoneNumber;
    UILabel *_instructLabel;
    YNCountryCodeSelecteButton *_countryCodeSelectButton;
    UIButton *_nextButton;
    YNRegisterTopView *_topView;
    YNPhoneNumberInputView *_phoneNumberInputView;
}

- (void).cxx_destruct;
- (void)countryCodeButtonTouched:(id)arg1;
@property(retain, nonatomic) YNCountryCodeSelecteButton *countryCodeSelectButton; // @synthesize countryCodeSelectButton=_countryCodeSelectButton;
- (void)dealloc;
- (void)faileToLoginYNAccountWith:(id)arg1;
- (id)formatNumber:(id)arg1;
- (long long)getLength:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (id)init;
@property(retain, nonatomic) UILabel *instructLabel; // @synthesize instructLabel=_instructLabel;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)loginWithPhoneCancelButtonClicked:(id)arg1;
- (void)mobileReceiveSMSLoginFaileWithError:(id)arg1 message:(id)arg2;
- (void)mobileReceiveSMSLoginSuccessSmsid:(id)arg1;
@property(retain, nonatomic) UIButton *nextButton; // @synthesize nextButton=_nextButton;
- (void)nextButtonClicked:(id)arg1;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) YNPhoneNumberInputView *phoneNumberInputView; // @synthesize phoneNumberInputView=_phoneNumberInputView;
- (void)registerCountryCodePicker:(id)arg1 didSelectedWithCountryName:(id)arg2 countryCode:(id)arg3;
- (void)registerCountryCodePickerDidSelectedCancel:(id)arg1;
- (void)registerKeyboardNotification;
@property(retain, nonatomic) YNRegisterTopView *topView; // @synthesize topView=_topView;
- (void)setupViewConstraints;
- (void)showMainView;
- (void)signANewAccountWithPhone;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)unRegisterKeyboardNotification;
- (void)updateButtonStatus;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

