//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNScrollContainerViewController.h"

@class UIButton, UITextField;

@interface YNMainLoginViewController : YNScrollContainerViewController
{
    UIButton *_loginButton;
    UITextField *_accountTextField;
    UITextField *_passwordTextFiled;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UITextField *accountTextField; // @synthesize accountTextField=_accountTextField;
@property(retain, nonatomic) UIButton *loginButton; // @synthesize loginButton=_loginButton;
@property(retain, nonatomic) UITextField *passwordTextFiled; // @synthesize passwordTextFiled=_passwordTextFiled;
- (void)setupViewConstraints;
- (void)viewDidLoad;

@end

