//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface YNMeidaDisplayViewModel : NSObject
{
    unsigned long long _type;
    UIImage *_placeholderImage;
    NSString *_thumbnailImageUrl;
    NSString *_bigImageUrl;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *bigImageUrl; // @synthesize bigImageUrl=_bigImageUrl;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(retain, nonatomic) NSString *thumbnailImageUrl; // @synthesize thumbnailImageUrl=_thumbnailImageUrl;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;

@end

