//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNTableViewCell.h"

@class NSMutableArray;

@interface YNMiniProgramsNearbyEnterCell : YNTableViewCell
{
    NSMutableArray *_preViewImg;
}

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) NSMutableArray *preViewImg; // @synthesize preViewImg=_preViewImg;
- (void)setImgs:(id)arg1;

@end

