//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface YNMomentFeedImageGridView : UIView
{
    NSMutableArray *_imageViewList;
    id <YNMomentFeedImageGridViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <YNMomentFeedImageGridViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)generateImageViewWithFrame:(struct CGRect)arg1;
- (void)handleTapGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setImageInfos:(id)arg1 imageSize:(struct CGSize)arg2 numberInRow:(long long)arg3;

@end

