//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNTableViewCell.h"

@class NSMutableArray, UIImageView, UILabel, UIView, YNAvatarView, YNMomentMsgModel;

@interface YNMomentMsgListCell : YNTableViewCell
{
    id <YNMomentMsgListCellDelegate> _delegate;
    YNAvatarView *_avatarImageView;
    UILabel *_nameLabel;
    UILabel *_commentLabel;
    UIImageView *_likeImg;
    UILabel *_timeLabel;
    UIImageView *_feedImageView;
    UILabel *_feedContentLabel;
    UIView *_topLine;
    UIView *_bottomLine;
    UIImageView *_videoImgIcon;
    double _enterMsgListTime;
    YNMomentMsgModel *_msgModel;
    NSMutableArray *_commonLinksArray;
}

+ (id)attributedShowText:(id)arg1 withColor:(id)arg2 withFont:(id)arg3 withEmojiSize:(double)arg4 toCommonLinksArray:(id)arg5;
+ (id)commentLabelColor;
+ (id)commentLabelFont;
+ (id)deleteCommentLabelbgdColor;
+ (id)getCellIdentifierByType:(id)arg1;
+ (double)getCommentLabelHeight:(id)arg1;
+ (double)getMsgCellHeight:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) YNAvatarView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
- (void)commentTextTapped:(id)arg1;
@property(retain, nonatomic) NSMutableArray *commonLinksArray; // @synthesize commonLinksArray=_commonLinksArray;
@property(nonatomic) __weak id <YNMomentMsgListCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double enterMsgListTime; // @synthesize enterMsgListTime=_enterMsgListTime;
@property(retain, nonatomic) UILabel *feedContentLabel; // @synthesize feedContentLabel=_feedContentLabel;
@property(retain, nonatomic) UIImageView *feedImageView; // @synthesize feedImageView=_feedImageView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) UIImageView *likeImg; // @synthesize likeImg=_likeImg;
@property(retain, nonatomic) YNMomentMsgModel *msgModel; // @synthesize msgModel=_msgModel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)onAvatarImageViewClicked;
- (void)onFeedImageViewClicked;
- (id)resultCommonForGestureRecognizer:(id)arg1;
- (void)setLikeCommentModel:(id)arg1;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
@property(retain, nonatomic) UIImageView *videoImgIcon; // @synthesize videoImgIcon=_videoImgIcon;
- (void)setupViewConstraints;

@end

