//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, YNMomentFeedViewModel;

@interface YNMomentFeedReplyMenu : UIView
{
    UIView *_containerView;
    UIImageView *_animationView;
    UIButton *_likeBtn;
    UIButton *_commentBtn;
    _Bool _isAnimating;
    _Bool _showAsLiked;
    _Bool _isShowInView;
    id <YNMomentFeedReplyMenuDelegate> _delegate;
    YNMomentFeedViewModel *_relatedViewModel;
}

- (void).cxx_destruct;
- (void)commentBtnDidTap:(id)arg1;
@property(nonatomic) __weak id <YNMomentFeedReplyMenuDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFixedFrame;
@property(nonatomic) _Bool isShowInView; // @synthesize isShowInView=_isShowInView;
- (void)likeBtnDidTap:(id)arg1;
@property(retain, nonatomic) YNMomentFeedViewModel *relatedViewModel; // @synthesize relatedViewModel=_relatedViewModel;
@property(nonatomic) _Bool showAsLiked; // @synthesize showAsLiked=_showAsLiked;
- (void)showMenu:(_Bool)arg1 animated:(_Bool)arg2 delay:(double)arg3 inView:(id)arg4;
- (void)showMenu:(_Bool)arg1 animated:(_Bool)arg2 inView:(id)arg3;

@end

