//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "YNMomentAvatarViewDelegate.h"
#import "YNMomentLikeCommentDetailViewDelegate.h"
#import "YNMomentLikeCommentViewDelegate.h"

@class NSString, UIButton, UILabel, UIView, YNMomentAvatarView, YNMomentFeedViewModel, YNMomentLikeCommentDetailView, YNMomentLikeCommentView;

@interface YNMomentFeedCell : UITableViewCell <YNMomentAvatarViewDelegate, YNMomentLikeCommentViewDelegate, YNMomentLikeCommentDetailViewDelegate>
{
    UIView *_attachmentView;
    UIView *_bottomLine;
    UIView *_commentView;
    YNMomentAvatarView *_avatarView;
    UIButton *_nicknameBtn;
    UILabel *_timeLabel;
    UIButton *_commentBtn;
    UILabel *_textContentLabel;
    UIButton *_fullTextBtn;
    UIButton *_deleteBtn;
    UIButton *_failedBtn;
    id <YNMomentFeedCellDelegate> _delegate;
    YNMomentFeedViewModel *_viewModel;
    YNMomentLikeCommentView *_replyView;
    YNMomentLikeCommentDetailView *_replyDetailView;
}

- (void).cxx_destruct;
- (void)YNMomentAvatarViewDidTap:(id)arg1;
@property(readonly, nonatomic) YNMomentAvatarView *avatarView; // @synthesize avatarView=_avatarView;
- (void)bindViewModel:(id)arg1;
@property(readonly, nonatomic) UIButton *commentBtn; // @synthesize commentBtn=_commentBtn;
- (void)commentTap:(id)arg1;
- (id)customAttachmentView;
@property(nonatomic) __weak id <YNMomentFeedCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIButton *deleteBtn;
- (void)deleteBtnDidTap:(id)arg1;
- (void)deselectHightText;
@property(readonly, nonatomic) UIButton *failedBtn;
- (void)failedBtnDidTap:(id)arg1;
@property(readonly, nonatomic) UIButton *fullTextBtn;
- (void)fullTextBtnDidTap:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)longPressDidRecognize:(id)arg1;
- (void)nickNameTap:(id)arg1;
@property(readonly, nonatomic) UIButton *nicknameBtn; // @synthesize nicknameBtn=_nicknameBtn;
- (void)onCommentZoneCommonLinkClicked:(id)arg1;
- (void)onCommentZoneLongTap:(id)arg1 tapViewFrame:(struct CGRect)arg2;
- (void)onCommentZoneTap:(id)arg1 tapViewFrame:(struct CGRect)arg2;
- (void)onHeadImgClicked:(id)arg1;
- (void)onLikeCommentDetailViewCommonLinkClicked:(id)arg1;
- (void)onLikeCommentDetailViewLongTap:(id)arg1 tapViewFrame:(struct CGRect)arg2;
- (void)onLikeCommentDetailViewTap:(id)arg1 tapViewFrame:(struct CGRect)arg2;
- (void)onLikeCommentNickNameClicked:(id)arg1;
@property(readonly, nonatomic) YNMomentLikeCommentDetailView *replyDetailView; // @synthesize replyDetailView=_replyDetailView;
@property(readonly, nonatomic) YNMomentLikeCommentView *replyView; // @synthesize replyView=_replyView;
- (struct UIEdgeInsets)separatorInset;
@property(retain, nonatomic) YNMomentFeedViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (_Bool)shouldRespondsToZoneTap:(id)arg1 tapViewFrame:(struct CGRect)arg2;
- (void)tapTextDidRecognize:(id)arg1;
@property(readonly, nonatomic) UILabel *textContentLabel; // @synthesize textContentLabel=_textContentLabel;
@property(readonly, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)willMoveToSuperview:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

