//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSString, YNFriend;

@interface YNMomentFeed : NSObject
{
    long long _ID;
    NSString *_feedId;
    long long _clientId;
    long long _uid;
    YNFriend *_author;
    unsigned long long _timestamp;
    long long _version;
    unsigned long long _type;
    NSString *_text;
    long long _status;
    long long _privateStatus;
    NSDictionary *_location;
    NSString *_thumbnailUrl;
    NSArray *_privateUids;
    NSArray *_mediaList;
    NSArray *_likeList;
    NSArray *_commentList;
    NSMutableDictionary *_info;
    unsigned long long _localStatus;
    NSString *_requestId;
}

+ (id)feedFromJsonValue:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
@property(retain, nonatomic) YNFriend *author; // @synthesize author=_author;
@property(nonatomic) long long clientId; // @synthesize clientId=_clientId;
@property(retain, nonatomic) NSArray *commentList; // @synthesize commentList=_commentList;
- (id)dictionaryValue;
@property(retain, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
@property(retain, nonatomic) NSMutableDictionary *info; // @synthesize info=_info;
- (id)init;
- (id)initWithFBResult:(id)arg1;
- (id)initWithJsonValue:(id)arg1;
- (id)jsonValue;
@property(retain, nonatomic) NSArray *likeList; // @synthesize likeList=_likeList;
@property(nonatomic) unsigned long long localStatus; // @synthesize localStatus=_localStatus;
@property(retain, nonatomic) NSDictionary *location; // @synthesize location=_location;
@property(retain, nonatomic) NSArray *mediaList; // @synthesize mediaList=_mediaList;
- (long long)mediaTypeWithFeedType:(unsigned long long)arg1;
- (_Bool)needUploadResource;
@property(nonatomic) long long privateStatus; // @synthesize privateStatus=_privateStatus;
@property(retain, nonatomic) NSArray *privateUids; // @synthesize privateUids=_privateUids;
@property(retain, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(nonatomic) long long version; // @synthesize version=_version;

@end

