//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YNMomentPostMediaPreviewController;

@protocol YNMomentPostMediaPreviewControllerDelegate <NSObject>
- (void)previewController:(YNMomentPostMediaPreviewController *)arg1 didDeleteImageAtIndex:(unsigned long long)arg2;
- (void)previewControllerDidDeleteVideo:(YNMomentPostMediaPreviewController *)arg1;
@end

