//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNMomentFeedReply.h"

@interface YNMomentFeedLike : YNMomentFeedReply
{
}

+ (id)feedReplyFromJsonValue:(id)arg1;
- (id)dictionaryValue;
- (id)initWithFBResult:(id)arg1;
- (id)initWithJsonValue:(id)arg1;

@end

