//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNMomentFeedCellDelegate.h"

@class YNMomentFeedCell;

@protocol YNMomentFeedWebCellDelegate <YNMomentFeedCellDelegate>
- (void)YNMomentFeedCellDidTapWebInfo:(YNMomentFeedCell *)arg1;
@end

