//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "YNMomentImagePostPreviewCellDelegate.h"
#import "ZMVAVPlayerDelegate.h"

@class NSMutableArray, NSString, UICollectionView, UIImageView, ZMVAVPlayer;

@interface YNMomentPostMediaPreviewController : YNBaseViewController <UICollectionViewDataSource, UICollectionViewDelegate, YNMomentImagePostPreviewCellDelegate, ZMVAVPlayerDelegate>
{
    _Bool _topBarsHidden;
    _Bool _didLayoutSubviews;
    id <YNMomentPostMediaPreviewControllerDelegate> _delegate;
    ZMVAVPlayer *_playerView;
    UIImageView *_thumbnailImageView;
    id _video;
    UICollectionView *_collectionView;
    NSMutableArray *_images;
    unsigned long long _currentIndex;
    unsigned long long _totalCount;
}

- (void).cxx_destruct;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
- (void)dealloc;
@property(nonatomic) __weak id <YNMomentPostMediaPreviewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteCurrentImage;
- (void)deleteCurrentVideo;
@property(nonatomic) _Bool didLayoutSubviews; // @synthesize didLayoutSubviews=_didLayoutSubviews;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images=_images;
- (id)initWithPostModel:(id)arg1 currentIndex:(unsigned long long)arg2;
@property(retain, nonatomic) ZMVAVPlayer *playerView; // @synthesize playerView=_playerView;
- (void)previewCellDidSingleTapped:(id)arg1;
- (void)resetTitle;
- (void)rightNavBarButtonAction:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
@property(retain, nonatomic) UIImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
@property(nonatomic) _Bool topBarsHidden; // @synthesize topBarsHidden=_topBarsHidden;
@property(nonatomic) unsigned long long totalCount; // @synthesize totalCount=_totalCount;
@property(retain, nonatomic) id video; // @synthesize video=_video;
- (void)singleTapAction:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

