//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YNMomentFeedReply : NSObject
{
    NSString *_replyId;
    NSString *_fromId;
    NSString *_nickName;
    unsigned long long _timestamp;
    NSString *_feedId;
}

+ (id)feedReplyFromJsonValue:(id)arg1;
+ (id)safeString:(id)arg1;
- (void).cxx_destruct;
- (id)dictionaryValue;
@property(retain, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
@property(retain, nonatomic) NSString *fromId; // @synthesize fromId=_fromId;
- (id)initWithFBResult:(id)arg1;
- (id)initWithJsonValue:(id)arg1;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *replyId; // @synthesize replyId=_replyId;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;

@end

