//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

@class UIImageView, YNMyBarcodeInfoView;

@interface YNMyBarcodeViewController : YNBaseViewController
{
    UIImageView *navBarHairlineImageView;
    _Bool _pushFromScanController;
    YNMyBarcodeInfoView *_barcodeInfoView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) YNMyBarcodeInfoView *barcodeInfoView; // @synthesize barcodeInfoView=_barcodeInfoView;
- (void)didReceiveMemoryWarning;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)initNaviBarItem;
- (void)moreButtonClicked:(id)arg1;
@property(nonatomic) _Bool pushFromScanController; // @synthesize pushFromScanController=_pushFromScanController;
- (id)screenView;
- (void)setupViewConstraints;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

