//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface YNNewFriendsEmptyView : UIView
{
    UILabel *_hintText;
    UILabel *_subHintText;
    UIButton *_enterNearby;
    UILabel *_detaillabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *detaillabel; // @synthesize detaillabel=_detaillabel;
@property(retain, nonatomic) UIButton *enterNearby; // @synthesize enterNearby=_enterNearby;
@property(retain, nonatomic) UILabel *hintText; // @synthesize hintText=_hintText;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *subHintText; // @synthesize subHintText=_subHintText;

@end

