//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class AFHTTPSessionManager, AFJSONRequestSerializer;

@interface YNNetworkPlugin : CDVPlugin
{
    AFHTTPSessionManager *_sessionManager;
    AFJSONRequestSerializer *_requestSerializer;
}

- (void).cxx_destruct;
- (void)pluginInitialize;
- (void)requestLocalApi:(id)arg1;
- (void)requestLocalApiWithLxServer:(id)arg1;
@property(retain, nonatomic) AFJSONRequestSerializer *requestSerializer; // @synthesize requestSerializer=_requestSerializer;
@property(retain, nonatomic) AFHTTPSessionManager *sessionManager; // @synthesize sessionManager=_sessionManager;

@end

