//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel, UITextView, YNAvatarView, YNBottleInfo;

@interface YNOpenedBottleView : UIView
{
    id <YNOpenedBottleViewDelegate> _delegate;
    YNAvatarView *_avatarView;
    UIImageView *_genderIcon;
    UILabel *_nameLabel;
    UILabel *_subNameLabel;
    UIView *_containerView;
    UIImageView *_textContainerView;
    UITextView *_textView;
    UIImageView *_bubbleImageView;
    UILabel *_audioTimeLabel;
    UIImageView *_iconBackgroudImageView;
    UIImageView *_iconImageView;
    UIButton *_throwToSeaButton;
    UIButton *_replyButton;
    UIButton *_complainButton;
    YNBottleInfo *_bottleInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *audioTimeLabel; // @synthesize audioTimeLabel=_audioTimeLabel;
- (void)avatarImageViewTaped:(id)arg1;
@property(retain, nonatomic) YNAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) YNBottleInfo *bottleInfo; // @synthesize bottleInfo=_bottleInfo;
@property(retain, nonatomic) UIImageView *bubbleImageView; // @synthesize bubbleImageView=_bubbleImageView;
@property(retain, nonatomic) UIButton *complainButton; // @synthesize complainButton=_complainButton;
- (void)complainButtonClicked:(id)arg1;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <YNOpenedBottleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didClickedPlayAudioView:(id)arg1;
@property(retain, nonatomic) UIImageView *genderIcon; // @synthesize genderIcon=_genderIcon;
@property(retain, nonatomic) UIImageView *iconBackgroudImageView; // @synthesize iconBackgroudImageView=_iconBackgroudImageView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIButton *replyButton; // @synthesize replyButton=_replyButton;
- (void)replyButtonClicked:(id)arg1;
@property(retain, nonatomic) UILabel *subNameLabel; // @synthesize subNameLabel=_subNameLabel;
@property(retain, nonatomic) UIImageView *textContainerView; // @synthesize textContainerView=_textContainerView;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIButton *throwToSeaButton; // @synthesize throwToSeaButton=_throwToSeaButton;
- (void)setupViewConstraints;
- (void)throwToSeaButtonClicked:(id)arg1;

@end

