//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, UITableView;

@interface YNPasswordViewController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate, UITextFieldDelegate>
{
    _Bool _isFromPush;
    _Bool _isResetPassword;
    NSString *_originalPassword;
    UITableView *_tableView;
    NSString *_password;
    NSString *_confirmPassword;
}

- (void).cxx_destruct;
- (void)cancelButtonClicked:(id)arg1;
- (void)changePassword;
@property(retain, nonatomic) NSString *confirmPassword; // @synthesize confirmPassword=_confirmPassword;
- (void)dealloc;
- (void)doneButtonClicked:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (id)headerView;
- (id)init;
- (void)initNaviBarItem;
@property(nonatomic) _Bool isFromPush; // @synthesize isFromPush=_isFromPush;
- (_Bool)isPasswordLawful:(id)arg1;
@property(nonatomic) _Bool isResetPassword; // @synthesize isResetPassword=_isResetPassword;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) NSString *originalPassword; // @synthesize originalPassword=_originalPassword;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
- (void)registerKeyboardNotification;
- (void)resetPassword;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)setupViewConstraints;
- (void)showMainView;
- (void)showNetworkErrorAlert;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChange:(id)arg1;
- (void)unRegisterKeyboardNotification;
- (void)updateButtonStatus;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

