//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNSingleChatViewController.h"

@interface YNPalmChatServiceViewController : YNSingleChatViewController
{
}

- (void)addHelpButton;
- (void)helpButtonTapped:(id)arg1;
- (void)userInfoButtonClicked:(id)arg1;
- (void)viewDidLoad;

@end

