//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@interface YNPeopleNearbyTipsHeaderView : UITableViewHeaderFooterView
{
    id <YNPeopleNearbyTipsHeaderViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <YNPeopleNearbyTipsHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)onViewClicked;

@end

