//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNTableViewCell.h"

@class YNAvatarView;

@interface YNPersonalInfoSettingAvatarCell : YNTableViewCell
{
    id <YNPersonalInfoSettingAvatarCellDelegate> _delegate;
    YNAvatarView *_avatarImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) YNAvatarView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) id <YNPersonalInfoSettingAvatarCellDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)myAvatarImageClicked:(id)arg1;
- (void)setupViewConstraints;

@end

