//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNPersonalMomentBaseCell.h"

@class UIImageView;

@interface YNPersonalMomentTextCell : YNPersonalMomentBaseCell
{
    UIImageView *_failedImageView;
}

- (void).cxx_destruct;
- (void)configureWithFeedSource:(id)arg1;
@property(retain, nonatomic) UIImageView *failedImageView; // @synthesize failedImageView=_failedImageView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)jumpToDetail;
- (void)setupConstraints;

@end

