//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, YNChatMessage, YNVideoStatusView, ZMVAVPlayer;

@interface YNPersonalMomentVideoPreviewView : UIView
{
    YNChatMessage *_message;
    ZMVAVPlayer *_player;
    UIImageView *_imvThumbnail;
    YNVideoStatusView *_statusView;
}

- (void).cxx_destruct;
- (void)configureUI;
@property(retain, nonatomic) UIImageView *imvThumbnail; // @synthesize imvThumbnail=_imvThumbnail;
- (id)initWithMessage:(id)arg1;
@property(retain, nonatomic) YNChatMessage *message; // @synthesize message=_message;
@property(retain, nonatomic) ZMVAVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) YNVideoStatusView *statusView; // @synthesize statusView=_statusView;
- (void)startDownloadMediaFile:(CDUnknownBlockType)arg1;

@end

