//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSString, UIView, YNFriend, YNImageScrollView;

@interface YNPersonalPictureViewController : YNBaseViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIScrollViewDelegate>
{
    _Bool _zoomOut_In;
    YNFriend *_me;
    UIView *_imageDisplayBackgroundView;
    YNImageScrollView *_scrollerView;
}

- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
@property(retain, nonatomic) UIView *imageDisplayBackgroundView; // @synthesize imageDisplayBackgroundView=_imageDisplayBackgroundView;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (id)init;
- (void)initNaviBarItem;
- (void)longPressGesture:(id)arg1;
@property(retain, nonatomic) YNFriend *me; // @synthesize me=_me;
- (void)moreButtonClicked:(id)arg1;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)saveImageToAlbulm:(id)arg1;
- (void)saveImages;
@property(retain, nonatomic) YNImageScrollView *scrollerView; // @synthesize scrollerView=_scrollerView;
@property(nonatomic) _Bool zoomOut_In; // @synthesize zoomOut_In=_zoomOut_In;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

