//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString, UISearchBar, UISearchDisplayController, UITableView, UITapGestureRecognizer;

@interface YNPersonListViewController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, UISearchDisplayDelegate>
{
    NSObject<OS_dispatch_queue> *_listReloadQueue;
    UITapGestureRecognizer *_tapGesture;
    unsigned long long _style;
    UITableView *_tableView;
    UISearchBar *_searchBar;
    NSMutableArray *_sectionIndexs;
    NSMutableArray *_sectionItems;
    NSMutableArray *_searchedItems;
    UISearchDisplayController *_searchDisplayController;
}

- (void).cxx_destruct;
- (_Bool)canEditRows;
- (void)commitEditingStyleForObject:(id)arg1;
- (void)didSelectCellWithObject:(id)arg1;
- (_Bool)filterObject:(id)arg1 withSearchString:(id)arg2;
- (id)init;
- (void)initTableView;
- (id)initWithStyle:(unsigned long long)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)prepareDataSource;
- (void)reloadData;
- (void)reloadTableView;
- (id)rightButtonTitle;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController=_searchDisplayController;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
@property(retain, nonatomic) NSMutableArray *searchedItems; // @synthesize searchedItems=_searchedItems;
- (id)sectionIndexTitlesForTableView:(id)arg1;
@property(retain, nonatomic) NSMutableArray *sectionIndexs; // @synthesize sectionIndexs=_sectionIndexs;
@property(retain, nonatomic) NSMutableArray *sectionItems; // @synthesize sectionItems=_sectionItems;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

