//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class UILabel, UIView;

@interface YNPhotoListReusableView : UICollectionReusableView
{
    UIView *_backgroudView;
    UILabel *_titleLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *backgroudView; // @synthesize backgroudView=_backgroudView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setupViewConstraints;

@end

