//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, YNPhotoLibraryViewController;

@protocol YNPhotoLibraryViewControllerDelegate <NSObject>

@optional
- (void)photoLibrary:(YNPhotoLibraryViewController *)arg1 didSelectOriginal:(_Bool)arg2;
- (void)photoLibrary:(YNPhotoLibraryViewController *)arg1 didSelectPhotos:(NSArray *)arg2;
- (void)photoLibraryDidCancel:(YNPhotoLibraryViewController *)arg1;
- (void)photoLibraryDidStartTranscodeVideo:(YNPhotoLibraryViewController *)arg1;
- (void)photoLibraryDidTranscodeVideoFailed:(YNPhotoLibraryViewController *)arg1;
@end

