//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, PHFetchResult;

@interface YNPhotoGroup : NSObject
{
    NSString *_title;
    PHFetchResult *_result;
}

+ (id)allGroups;
+ (id)allGroupsWithNoVideos:(_Bool)arg1;
+ (id)defaultGroup;
+ (id)defaultGroupWithNoVideos:(_Bool)arg1;
+ (id)fillGroupWithType:(long long)arg1 withNoVideos:(_Bool)arg2;
+ (id)items;
- (void).cxx_destruct;
- (void)getCoverImage:(CDUnknownBlockType)arg1;
- (unsigned long long)itemCount;
- (id)items;
@property(retain, nonatomic) PHFetchResult *result; // @synthesize result=_result;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;

@end

