//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "RegisterCountryCodePickerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "YNWOARegsterManagerDelegate.h"

@class NSString, UITableView, UITextField;

@interface YNPhoneChangeController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, YNWOARegsterManagerDelegate, RegisterCountryCodePickerDelegate>
{
    UITableView *_tableView;
    UITextField *_phoneTextField;
    NSString *_countryName;
    NSString *_countryCode;
}

- (void).cxx_destruct;
- (void)cancelButtonClicked:(id)arg1;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(retain, nonatomic) NSString *countryName; // @synthesize countryName=_countryName;
- (void)doneButtonClicked:(id)arg1;
- (void)enterCountryCodePickerPage;
- (id)formatNumber:(id)arg1;
- (id)headerView;
- (id)init;
- (void)initNaviBarItem;
- (void)loadView;
- (void)mobileReceiveSMSLoginFaileWithError:(id)arg1 message:(id)arg2;
- (void)mobileReceiveSMSLoginSuccessSmsid:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) __weak UITextField *phoneTextField; // @synthesize phoneTextField=_phoneTextField;
- (void)registerCountryCodePicker:(id)arg1 didSelectedWithCountryName:(id)arg2 countryCode:(id)arg3;
- (void)registerCountryCodePickerDidSelectedCancel:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)signANewAccountWithPhone;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

