//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, YNBaseViewController;

@protocol YNPickBottleViewControllerDelegate <NSObject>
- (void)pickBottleViewControllerEndUse:(YNBaseViewController *)arg1;
- (void)pickBottleViewControllerNotTimes:(YNBaseViewController *)arg1;
- (void)pickBottleViewControllerOpenUrl:(YNBaseViewController *)arg1 withUrl:(NSString *)arg2;
- (void)pickBottleViewControllerPickFail:(YNBaseViewController *)arg1 withAlertMsg:(NSString *)arg2;
@end

