//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIImage;

@interface YNPreviewChatImageController : UIViewController
{
    UIImage *_previewImage;
    id <YNPreviewChatImageControllerDelegate> _delegate;
    id _context;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id context; // @synthesize context=_context;
@property(nonatomic) __weak id <YNPreviewChatImageControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
@property(readonly, nonatomic) UIImage *image;
- (id)initWithImage:(id)arg1;
- (void)loadView;
- (id)previewActionItems;
- (void)viewDidLoad;

@end

