//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YNQRCodeGenerator : NSObject
{
}

+ (id)barCodeImageForText:(id)arg1;
+ (id)resizeImage:(id)arg1 withQuality:(int)arg2 rate:(double)arg3;

@end

