//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface YNRedPacketRecordViewModel : NSObject
{
    _Bool _isEnd;
    NSString *_amount;
    long long _count;
    long long _mvpTimes;
    long long _indexTs;
    NSMutableArray *_redArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *amount; // @synthesize amount=_amount;
- (void)configureWithDic:(id)arg1;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(nonatomic) long long indexTs; // @synthesize indexTs=_indexTs;
@property(nonatomic) _Bool isEnd; // @synthesize isEnd=_isEnd;
@property(nonatomic) long long mvpTimes; // @synthesize mvpTimes=_mvpTimes;
@property(retain, nonatomic) NSMutableArray *redArray; // @synthesize redArray=_redArray;

@end

