//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "YNBaseChatViewControllerDelegate.h"

@class CDVInvokedUrlCommand, NSString, YNBaseChatViewController;

@interface YNReportPluginUserInfo : CDVPlugin <YNBaseChatViewControllerDelegate>
{
    YNBaseChatViewController *_chatViewController;
    CDVInvokedUrlCommand *_urlCommond;
}

- (void).cxx_destruct;
- (void)addToBlackList:(id)arg1;
- (void)chatVX:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) YNBaseChatViewController *chatViewController; // @synthesize chatViewController=_chatViewController;
- (void)chatViewControllerDidPreloadMessageCompleted:(id)arg1;
- (void)closeWindow:(id)arg1;
- (void)getChatInfo:(id)arg1;
- (void)getReportInfo:(id)arg1;
- (void)jumpToChat:(id)arg1;
@property(retain, nonatomic) CDVInvokedUrlCommand *urlCommond; // @synthesize urlCommond=_urlCommond;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

