//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UILabel;

@interface YNRedPacketLoadMoreView : UIView
{
    UILabel *_infoLabel;
    UIActivityIndicatorView *_indicatorView;
}

+ (double)heightForState:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setState:(unsigned long long)arg1;

@end

