//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UIImageView, UILabel, YNAvatarView, YNRecommendFriendSubModel;

@interface YNRecommendFriendCollectCell : UICollectionViewCell
{
    YNAvatarView *_photoImageView;
    UIButton *_selectButton;
    UILabel *_nameLabel;
    UIButton *_genderView;
    UIImageView *_momentIcon;
    YNRecommendFriendSubModel *_subModel;
    id <YNRecommendFriendCollectCellDelegate> _delegate;
}

+ (double)cellHeightByWidth:(double)arg1;
+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(nonatomic) __weak id <YNRecommendFriendCollectCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didClickedImageView:(id)arg1;
@property(retain, nonatomic) UIButton *genderView; // @synthesize genderView=_genderView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIImageView *momentIcon; // @synthesize momentIcon=_momentIcon;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) YNAvatarView *photoImageView; // @synthesize photoImageView=_photoImageView;
@property(retain, nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
- (void)selectButtonClick:(id)arg1;
@property(retain, nonatomic) YNRecommendFriendSubModel *subModel; // @synthesize subModel=_subModel;
- (void)setupViewConstraints;

@end

