//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, UIImageView, UILabel;

@interface YNRedPacketPromotionTemplateView : UIView
{
    NSDictionary *_data;
    UILabel *_label1;
    UILabel *_label2;
    UILabel *_label3;
    UILabel *_label4;
    UILabel *_label5;
    UILabel *_label6;
    UIImageView *_qrCodeImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (id)initWithData:(id)arg1;
- (void)initialize;
@property(retain, nonatomic) UILabel *label1; // @synthesize label1=_label1;
@property(retain, nonatomic) UILabel *label2; // @synthesize label2=_label2;
@property(retain, nonatomic) UILabel *label3; // @synthesize label3=_label3;
@property(retain, nonatomic) UILabel *label4; // @synthesize label4=_label4;
@property(retain, nonatomic) UILabel *label5; // @synthesize label5=_label5;
@property(retain, nonatomic) UILabel *label6; // @synthesize label6=_label6;
@property(retain, nonatomic) UIImageView *qrCodeImageView; // @synthesize qrCodeImageView=_qrCodeImageView;

@end

