//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MJRefreshHeader.h"

@class UIActivityIndicatorView;

@interface YNRefreshHeader : MJRefreshHeader
{
    UIActivityIndicatorView *_indicatorView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
- (void)placeSubviews;
- (void)prepare;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)setState:(long long)arg1;

@end

