//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "YNChatCenterDelegate.h"
#import "YNChatRoomCreateFriendsPickerViewControllerDelegate.h"
#import "YNForwardAlertControllerDelegate.h"
#import "YNRecentSearchContactControllerDelegate.h"

@class NSArray, NSMutableArray, NSString, UISearchBar, YNRecentSearchContactController, YNTableView;

@interface YNRecentChatPickerViewController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, YNRecentSearchContactControllerDelegate, UISearchBarDelegate, YNChatRoomCreateFriendsPickerViewControllerDelegate, YNChatCenterDelegate, YNForwardAlertControllerDelegate>
{
    _Bool _isDismissForRevoke;
    _Bool _sendNewMessage;
    id <YNRecentChatPickerViewControllerDelegate> _delegate;
    NSString *_disEnableConversationId;
    YNTableView *_tableView;
    NSArray *_chatConversations;
    UISearchBar *_searchBar;
    YNRecentSearchContactController *_mySearchDisplayController;
    NSMutableArray *_forwardMessagesArray;
    NSMutableArray *_forwardTargetsArray;
    unsigned long long _selectType;
}

- (void).cxx_destruct;
- (void)cancelPickerRecentChatClicked:(id)arg1;
- (void)chatCenter:(id)arg1 didRevokeMessageWithRevokeMessage:(id)arg2;
@property(retain, nonatomic) NSArray *chatConversations; // @synthesize chatConversations=_chatConversations;
- (void)dealloc;
@property(nonatomic) __weak id <YNRecentChatPickerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didClickedCancelInPicker:(id)arg1;
- (void)didFinishedPicker:(id)arg1 withChatRoom:(id)arg2;
- (void)didFinishedPicker:(id)arg1 withFriends:(id)arg2 withRequstId:(id)arg3;
- (void)didReceiveMemoryWarning;
@property(retain, nonatomic) NSString *disEnableConversationId; // @synthesize disEnableConversationId=_disEnableConversationId;
- (id)disabledConversationBizTypes;
- (id)disabledConversationIds;
- (void)dismissControllerAfterRevoke;
- (_Bool)executeRevokeMessage:(id)arg1;
- (void)forwardAlertDidCancel;
- (void)forwardAlertDidDismissWithMessage:(id)arg1;
@property(retain, nonatomic) NSMutableArray *forwardMessagesArray; // @synthesize forwardMessagesArray=_forwardMessagesArray;
@property(retain, nonatomic) NSMutableArray *forwardTargetsArray; // @synthesize forwardTargetsArray=_forwardTargetsArray;
- (id)init;
- (void)initNaviBarItem;
- (id)initWithForwardMessages:(id)arg1;
- (void)loadChatConversationList;
@property(retain, nonatomic) YNRecentSearchContactController *mySearchDisplayController; // @synthesize mySearchDisplayController=_mySearchDisplayController;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchDisplayControllerDidSelectedChatRoom:(id)arg1;
- (void)searchDisplayControllerDidSelectedFriend:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
@property(nonatomic) unsigned long long selectType; // @synthesize selectType=_selectType;
@property(nonatomic) _Bool sendNewMessage; // @synthesize sendNewMessage=_sendNewMessage;
@property(retain, nonatomic) YNTableView *tableView; // @synthesize tableView=_tableView;
- (void)setupViewConstraints;
- (void)showForwardAlert;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

