//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class YNInputTextView;

@interface YNRemarkInputTextViewCell : UITableViewCell
{
    YNInputTextView *_textView;
}

+ (id)cellIdentifier;
+ (double)heightForInputInfo:(id)arg1;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) YNInputTextView *textView; // @synthesize textView=_textView;
- (void)setupViewConstraints;

@end

