//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class UIActivityIndicatorView, UILabel, UIView;

@interface YNRedPacketRecordFooterView : UITableViewHeaderFooterView
{
    UILabel *_infoLabel;
    UIActivityIndicatorView *_indicatorView;
    UIView *_bottomView;
}

+ (double)heightForState:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)setState:(unsigned long long)arg1;

@end

