//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YNRedPacketRecordInfo : NSObject
{
    NSString *_from;
    long long _type;
    double _ts;
    NSString *_timeString;
    NSString *_amount;
    NSString *_number;
    NSString *_redId;
    long long _redStatus;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *amount; // @synthesize amount=_amount;
- (void)configureWithDic:(id)arg1;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
@property(retain, nonatomic) NSString *number; // @synthesize number=_number;
@property(retain, nonatomic) NSString *redId; // @synthesize redId=_redId;
@property(nonatomic) long long redStatus; // @synthesize redStatus=_redStatus;
@property(retain, nonatomic) NSString *timeString; // @synthesize timeString=_timeString;
@property(nonatomic) double ts; // @synthesize ts=_ts;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

