//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSString, UIImage;

@interface YNRichTextItem : NSObject <NSCopying>
{
    _Bool _line;
    int _showType;
    int _width;
    int _height;
    int _statusBarStyle;
    NSString *_title;
    NSString *_cover;
    NSString *_url;
    NSString *_digest;
    unsigned long long _pubTime;
    NSString *_topBarColor;
    NSString *_topBarTextColor;
    UIImage *_coverImg;
    NSString *_appIcon;
    NSString *_appName;
    NSString *_acode;
    NSString *_amount;
    NSString *_label;
    NSArray *_list;
    NSArray *_adsList;
    struct CGSize _itemSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *acode; // @synthesize acode=_acode;
@property(retain, nonatomic) NSArray *adsList; // @synthesize adsList=_adsList;
@property(retain, nonatomic) NSString *amount; // @synthesize amount=_amount;
@property(retain, nonatomic) NSString *appIcon; // @synthesize appIcon=_appIcon;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) UIImage *coverImg; // @synthesize coverImg=_coverImg;
@property(retain, nonatomic) NSString *digest; // @synthesize digest=_digest;
@property(nonatomic) int height; // @synthesize height=_height;
- (_Bool)isAds;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(nonatomic) _Bool line; // @synthesize line=_line;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(nonatomic) unsigned long long pubTime; // @synthesize pubTime=_pubTime;
@property(nonatomic) int showType; // @synthesize showType=_showType;
@property(nonatomic) int statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *topBarColor; // @synthesize topBarColor=_topBarColor;
@property(retain, nonatomic) NSString *topBarTextColor; // @synthesize topBarTextColor=_topBarTextColor;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) int width; // @synthesize width=_width;

@end

