//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class YNRichTextItem;

@interface YNRichTextBaseItemView : UIImageView
{
    YNRichTextItem *_item;
}

+ (double)heightForTextView:(id)arg1 font:(id)arg2 width:(double)arg3 line:(int)arg4;
+ (double)viewHeight:(id)arg1 width:(double)arg2;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) YNRichTextItem *item; // @synthesize item=_item;
- (double)viewHeight;

@end

