//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, YNRichTextFooter, YNRichTextHeader, YNRichTextSource;

@interface YNRichTextMsg : NSObject <NSCopying>
{
    int _forwardable;
    YNRichTextHeader *_header;
    YNRichTextFooter *_footer;
    YNRichTextSource *_source;
    NSArray *_items;
}

+ (id)parseFromDictionary:(id)arg1;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) YNRichTextFooter *footer; // @synthesize footer=_footer;
@property(nonatomic) int forwardable; // @synthesize forwardable=_forwardable;
@property(retain, nonatomic) YNRichTextHeader *header; // @synthesize header=_header;
- (_Bool)isBubbleStyle;
- (_Bool)isCustomSize;
- (_Bool)isMiniPrograms;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (_Bool)maskRequired;
@property(retain, nonatomic) YNRichTextSource *source; // @synthesize source=_source;
- (id)toDictionary;
- (void)toDictionary:(id)arg1;

@end

