//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseChatViewController.h"

#import "YNChatRoomInfoViewControllerDelegate.h"
#import "YNSelectRemindPeopleViewControllerDelegate.h"

@class NSString;

@interface YNRoomChatViewController : YNBaseChatViewController <YNSelectRemindPeopleViewControllerDelegate, YNChatRoomInfoViewControllerDelegate>
{
}

- (void)cancelSelectMember;
- (void)chatRoomInfoButtonClicked:(id)arg1;
- (void)configureNavigation;
- (void)conversationCancelButtonClicked;
- (void)conversationOkButtonClicked;
- (void)didAddNewFriend:(id)arg1;
- (void)didChangeShowChatMemberName;
- (void)didChangedChatRoomList;
- (void)didDeleteChatRoomChatRecord;
- (void)didEditedFriend:(id)arg1;
- (void)didSelectMember:(id)arg1;
- (id)getChatInputSwitchViewTypes;
- (void)initNaviBarItem;
- (_Bool)isChinese:(id)arg1;
- (_Bool)isEndStringMeetStandard:(id)arg1 textViewText:(id)arg2;
- (void)refreshCellsForRoomChange;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)updateChatCellViewModelWithFriend:(id)arg1;
- (void)updateNavigationTitleViewLayout;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

