//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface YNScanNotFoundView : UIView
{
    UILabel *_notFountPromtLabel;
    UILabel *_tapScanLabel;
    id <YNScanNotFoundViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <YNScanNotFoundViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleScanNotFoundTap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *notFountPromtLabel; // @synthesize notFountPromtLabel=_notFountPromtLabel;
@property(retain, nonatomic) UILabel *tapScanLabel; // @synthesize tapScanLabel=_tapScanLabel;
- (void)setupViewConstraints;

@end

