//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YNSecurityManager : NSObject
{
    _Bool _isLoadingDesKey;
    NSString *_pk;
    NSString *_ck;
    NSString *_sk;
    NSString *_iv;
    NSString *_desKey;
    NSString *_ticket;
    NSString *_token;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (_Bool)checkTokenValid;
@property(retain, nonatomic) NSString *ck; // @synthesize ck=_ck;
@property(retain, nonatomic) NSString *desKey; // @synthesize desKey=_desKey;
- (id)generateCK;
- (id)init;
@property(nonatomic) _Bool isLoadingDesKey; // @synthesize isLoadingDesKey=_isLoadingDesKey;
@property(retain, nonatomic) NSString *iv; // @synthesize iv=_iv;
@property(readonly, nonatomic) NSString *liv;
@property(readonly, nonatomic) NSString *lpk;
@property(retain, nonatomic) NSString *pk; // @synthesize pk=_pk;
- (void)save;
@property(retain, nonatomic) NSString *sk; // @synthesize sk=_sk;
@property(retain, nonatomic) NSString *ticket; // @synthesize ticket=_ticket;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;

@end

