//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITextFieldDelegate.h"

@class NSArray, NSString, UIViewController, YNTextInputHelper;

@interface YNSendFriendApplyManage : NSObject <UITextFieldDelegate>
{
    UIViewController *_showController;
    NSString *_defaultApplyStr;
    NSArray *_uidsArray;
    long long _applyFromType;
    long long _subType;
    NSString *_subTypes;
    YNTextInputHelper *_textInputHelper;
}

- (void).cxx_destruct;
@property(nonatomic) long long applyFromType; // @synthesize applyFromType=_applyFromType;
@property(retain, nonatomic) NSString *defaultApplyStr; // @synthesize defaultApplyStr=_defaultApplyStr;
- (id)init;
- (void)sendFriendApplyWithText:(id)arg1;
@property(retain, nonatomic) UIViewController *showController; // @synthesize showController=_showController;
@property(nonatomic) long long subType; // @synthesize subType=_subType;
@property(retain, nonatomic) NSString *subTypes; // @synthesize subTypes=_subTypes;
@property(retain, nonatomic) YNTextInputHelper *textInputHelper; // @synthesize textInputHelper=_textInputHelper;
@property(retain, nonatomic) NSArray *uidsArray; // @synthesize uidsArray=_uidsArray;
- (void)showApplyFromController:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

