//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNUserProfileViewController.h"

@interface YNSepcialProfileViewController : YNUserProfileViewController
{
}

- (void)chatWithFriend:(id)arg1;
- (void)didChangedSwitchTalbleViewCell:(id)arg1 switchView:(id)arg2;
- (void)initNaviBarItem;
- (id)initWithFriend:(id)arg1;
- (id)initWithFriend:(id)arg1 withConversation:(id)arg2;
- (void)refreshBottomView;
- (void)refreshDataSource;
- (void)refreshHeaderView;
- (void)viewDidLoad;

@end

