//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNSendFriendApplyViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, YNTextInputHelper;

@interface YNSendNearbyFriendApplyViewController : YNSendFriendApplyViewController <UITextFieldDelegate>
{
    YNTextInputHelper *_textInputHelper;
}

- (void).cxx_destruct;
- (void)configRecommendText;
- (void)didReceiveMemoryWarning;
- (void)initNaviBarItem;
@property(retain, nonatomic) YNTextInputHelper *textInputHelper; // @synthesize textInputHelper=_textInputHelper;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

