//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface YNSexZoneView : UIView
{
    _Bool _isSelected;
    UIImageView *_sexImgView;
    UIImageView *_selectedImg;
    UILabel *_sexLabel;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) UIImageView *selectedImg; // @synthesize selectedImg=_selectedImg;
- (void)setSex:(int)arg1;
@property(retain, nonatomic) UIImageView *sexImgView; // @synthesize sexImgView=_sexImgView;
@property(retain, nonatomic) UILabel *sexLabel; // @synthesize sexLabel=_sexLabel;

@end

