//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol YNSendFriendApplyViewControllerDelegate <NSObject>

@optional
- (void)cancelApplyUserUidsArray:(NSArray *)arg1;
- (void)clickSendButtonUserUidsArray:(NSArray *)arg1;
- (void)didSendFriendApplyForUserUid:(NSString *)arg1;
- (void)didSendFriendApplyForUserUidsArray:(NSArray *)arg1;
@end

