//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YNShareManager : NSObject
{
}

+ (void)clearUrlAndFiles;
+ (id)defaultManager;
+ (void)openUrl:(id)arg1;
+ (id)readFileShareInfo;
+ (id)readImgPathShareInfo;
+ (id)readImgShareInfo;
+ (id)readUrlShareInfo;
- (id)init;

@end

