//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "YNBaseSwitchTableViewCellDelegate.h"
#import "YNChatCenterDelegate.h"
#import "YNChatInfoMembersCellDelegate.h"
#import "YNChatRoomCreateFriendsPickerViewControllerDelegate.h"

@class NSArray, NSString, YNChatConversation, YNFriend, YNTableView;

@interface YNSingleChatInfoSettingViewController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, YNChatRoomCreateFriendsPickerViewControllerDelegate, YNChatCenterDelegate, YNChatInfoMembersCellDelegate, YNBaseSwitchTableViewCellDelegate>
{
    id <YNSingleChatInfoSettingViewControllerDelegate> _delegate;
    YNFriend *_myFriend;
    YNChatConversation *_conversation;
    YNTableView *_tableView;
    NSArray *_memberItems;
    NSArray *_addFailFriendArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *addFailFriendArray; // @synthesize addFailFriendArray=_addFailFriendArray;
- (void)chatInfoMembersCellDidTapItem:(id)arg1;
@property(retain, nonatomic) YNChatConversation *conversation; // @synthesize conversation=_conversation;
- (void)dealloc;
@property(nonatomic) __weak id <YNSingleChatInfoSettingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didChangedSwitchTalbleViewCell:(id)arg1 switchView:(id)arg2;
- (void)didClickedCancelInPicker:(id)arg1;
- (void)didEditedFriend:(id)arg1;
- (void)didFinishedPicker:(id)arg1 withFriends:(id)arg2 withRequstId:(id)arg3;
- (void)initMemberItems;
- (void)initNaviBarItem;
@property(retain, nonatomic) NSArray *memberItems; // @synthesize memberItems=_memberItems;
@property(retain, nonatomic) YNFriend *myFriend; // @synthesize myFriend=_myFriend;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) YNTableView *tableView; // @synthesize tableView=_tableView;
- (void)setupViewConstraints;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

