//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ZMRTCCameraOutput.h"

@class CALayer, NSString, ZMRTCCamera;

@interface YNSmallVideoRecoder : NSObject <ZMRTCCameraOutput>
{
    ZMRTCCamera *_camera;
    struct CGSize _videoSize;
    NSString *_currentRecodeFilePath;
    id <YNSmallVideoRecoderDelegate> _delegate;
    CALayer *_previewLayer;
}

- (void).cxx_destruct;
- (void)addNotificationCenterObserver;
- (void)backgroundNotify:(id)arg1;
- (void)camera:(id)arg1 adjustingFocus:(_Bool)arg2 focusPoint:(struct CGPoint)arg3;
- (void)cancelRecoding;
- (void)closeCamera;
- (void)dealloc;
@property(nonatomic) __weak id <YNSmallVideoRecoderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finishRecording;
- (void)foregroundNotify:(id)arg1;
- (id)getVideoThumImage;
- (id)init;
@property(readonly, nonatomic) _Bool isCapturing;
- (void)openCamera;
- (void)openCameraCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) CALayer *previewLayer; // @synthesize previewLayer=_previewLayer;
- (void)setFocusPointOfInterest:(struct CGPoint)arg1;
- (void)startRecordingWithVideoPath:(id)arg1;
- (void)stopRecoding;
- (void)switchCamera;
- (void)swithcVideoZoom;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

