//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YNStickerStorage : NSObject
{
}

+ (void)deleteSticker:(id)arg1;
+ (long long)insertSticker:(id)arg1;
+ (id)loadCustomStickerArray;
+ (void)updateSticker:(id)arg1;

@end

