//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "YNPhotoLibraryViewControllerDelegate.h"

@class NSMutableArray, NSString, UICollectionView, YNStickerManagerBottomView;

@interface YNStickerManagerViewController : YNBaseViewController <UICollectionViewDataSource, UICollectionViewDelegate, YNPhotoLibraryViewControllerDelegate>
{
    _Bool _editMode;
    id <YNStickerManagerViewControllerDelegate> _delegate;
    UICollectionView *_collectionView;
    NSMutableArray *_customStickerArray;
    YNStickerManagerBottomView *_bottomView;
    NSMutableArray *_selectedArray;
}

- (void).cxx_destruct;
- (void)addSticker:(id)arg1;
@property(retain, nonatomic) YNStickerManagerBottomView *bottomView; // @synthesize bottomView=_bottomView;
- (void)cancelButtonClicked:(id)arg1;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(retain, nonatomic) NSMutableArray *customStickerArray; // @synthesize customStickerArray=_customStickerArray;
@property(nonatomic) __weak id <YNStickerManagerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteButtonClicked:(id)arg1;
- (void)deleteSelectedSticker;
@property(nonatomic) _Bool editMode; // @synthesize editMode=_editMode;
- (id)init;
- (void)initNaviBarItem;
- (void)loadStciker;
- (void)navigationtTitleTextAttributes;
- (void)photoLibrary:(id)arg1 didSelectPhotos:(id)arg2;
- (void)photoLibraryDidCancel:(id)arg1;
- (void)rightButtonClicked:(id)arg1;
@property(retain, nonatomic) NSMutableArray *selectedArray; // @synthesize selectedArray=_selectedArray;
- (void)setupViewConstraints;
- (void)updateBottomViewStatus;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

