//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary;

@interface YNStorageManager : NSObject
{
    NSDictionary *_configInfo;
    NSMutableDictionary *_infoDic;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *configInfo; // @synthesize configInfo=_configInfo;
- (void)dealloc;
- (void)handleEnteredBackground:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *infoDic; // @synthesize infoDic=_infoDic;
- (id)init;
- (_Bool)isConfigExist;
- (id)objectForKey:(id)arg1;
- (id)pathForConfig;
- (id)pathForInfoDic;
- (void)removeObjectForKey:(id)arg1;
- (void)saveStorageData;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)switchUser;
- (void)updateConfig:(id)arg1;

@end

