//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YNTextInputHelper : NSObject
{
    NSString *_lastInputText;
    long long _limitLength;
}

- (void).cxx_destruct;
- (void)cleanInputedText;
- (id)disableEmoji:(id)arg1;
- (id)initWithText:(id)arg1 limitLegnth:(long long)arg2;
@property(readonly, nonatomic) NSString *lastInputText; // @synthesize lastInputText=_lastInputText;
@property(nonatomic) long long limitLength; // @synthesize limitLength=_limitLength;
- (long long)textCountDidChanged:(id)arg1;
- (_Bool)textInput:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textInput:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3 isChineseSpecialHandle:(_Bool)arg4;

@end

