//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNChatCellViewModel.h"

@class NSString;

@interface YNTimeNodeViewModel : YNChatCellViewModel
{
    NSString *_time;
}

+ (Class)cellForClass;
+ (id)cellForIdentifier;
- (void).cxx_destruct;
- (double)heightForChatCell;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;

@end

