//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, YNUploadTask;

@protocol YNUploadManagerDelegate <NSObject>

@optional
- (void)didFailedUploadForKey:(NSString *)arg1 error:(NSString *)arg2 withChunkUploadInfo:(YNUploadTask *)arg3;
- (void)didFinishedUploadForKey:(NSString *)arg1 withChunkUploadInfo:(YNUploadTask *)arg2;
- (void)didProgressUploadForKey:(NSString *)arg1 progress:(double)arg2 totalBytesWretten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4 withChunkUploadInfo:(YNUploadTask *)arg5;
@end

