//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface YNURLPreviewBannerView : UIView
{
    id <YNURLPreviewBannerViewDelegate> _delegate;
    UIImageView *_iconView;
    UILabel *_titleLabel;
    UILabel *_briefLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *briefLabel; // @synthesize briefLabel=_briefLabel;
- (void)closeButtonAction:(id)arg1;
@property(nonatomic) __weak id <YNURLPreviewBannerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (id)init;
- (void)reloadWithWebsiteInfo:(id)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

