//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, YNDataDetector, YNWebsiteIconParser, YNWebsiteInfo;

@interface YNURLPreviewHandler : NSObject
{
    id <YNURLPreviewHandlerDelegate> _delegate;
    YNWebsiteInfo *_websiteInfo;
    NSString *_currentUrl;
    YNDataDetector *_urlDetector;
    YNWebsiteIconParser *_iconParser;
    NSMutableDictionary *_itemCaches;
    NSObject<OS_dispatch_queue> *_handlerQueue;
}

- (void).cxx_destruct;
- (void)cancelRequest;
- (void)clearCurrentWebsiteInfo;
@property(retain, nonatomic) NSString *currentUrl; // @synthesize currentUrl=_currentUrl;
- (void)dealloc;
@property(nonatomic) __weak id <YNURLPreviewHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)doRequest;
- (void)fetchContentWithUrl:(id)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *handlerQueue; // @synthesize handlerQueue=_handlerQueue;
@property(retain, nonatomic) YNWebsiteIconParser *iconParser; // @synthesize iconParser=_iconParser;
- (id)init;
- (_Bool)isValidUrl:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *itemCaches; // @synthesize itemCaches=_itemCaches;
- (void)previewContentWithUrl:(id)arg1;
@property(retain, nonatomic) YNDataDetector *urlDetector; // @synthesize urlDetector=_urlDetector;
@property(retain, nonatomic) YNWebsiteInfo *websiteInfo; // @synthesize websiteInfo=_websiteInfo;

@end

