//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNTableViewCell.h"

@class MASConstraint, UILabel;

@interface YNUserSignatureShowCell : YNTableViewCell
{
    UILabel *_tagLabel;
    UILabel *_infoLabel;
    MASConstraint *_infoLabelLConstraint;
}

+ (id)cellIdentifier;
+ (double)heightForSignature:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain) MASConstraint *infoLabelLConstraint; // @synthesize infoLabelLConstraint=_infoLabelLConstraint;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setAccessoryType:(long long)arg1;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
- (void)setupViewConstraints;

@end

