//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, UITableView, YNFriend, YNTextInputHelper;

@interface YNUserNameSettingViewController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    id <YNUserNameSettingViewControllerDelegate> _delegate;
    UITableView *_tableView;
    YNFriend *_me;
    YNTextInputHelper *_textInputHelper;
}

- (void).cxx_destruct;
- (void)cancelChangeNameButtonClicked:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <YNUserNameSettingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (void)handleTextViewDidChange:(id)arg1;
- (id)init;
- (void)initNaviBarItem;
@property(retain, nonatomic) YNFriend *me; // @synthesize me=_me;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)saveNameDone;
- (void)saveUserNameButtonClicked:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) YNTextInputHelper *textInputHelper; // @synthesize textInputHelper=_textInputHelper;
- (void)setupViewConstraints;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

