//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "YNBaseChatViewControllerDelegate.h"
#import "YNBaseSwitchTableViewCellDelegate.h"
#import "YNDefaultMediaContainerViewControllerDelegate.h"
#import "YNFriendsManagerDelagete.h"
#import "YNGreetChatTableViewCellDelegate.h"
#import "YNShowPhoneNumberCellDelegate.h"
#import "YNUserPorfileHeaderViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIButton, UIView, YNChatConversation, YNChatRoomMember, YNDefaultMediaContainerViewController, YNFriend, YNSingleChatViewController, YNTableView, YNTextInputHelper, YNUserPorfileHeaderView;

@interface YNUserProfileViewController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, YNFriendsManagerDelagete, YNUserPorfileHeaderViewDelegate, YNDefaultMediaContainerViewControllerDelegate, YNShowPhoneNumberCellDelegate, YNGreetChatTableViewCellDelegate, UITextFieldDelegate, YNBaseChatViewControllerDelegate, YNBaseSwitchTableViewCellDelegate>
{
    YNTableView *_tableView;
    YNUserPorfileHeaderView *_headerView;
    UIView *_bottomView;
    UIButton *_chatButton;
    UIButton *_blackListButton;
    UIButton *_complainButton;
    YNFriend *_myFriend;
    NSMutableArray *_viewModleArray;
    NSString *currentPhoneNumber;
    _Bool _shouldDeleteScanVC;
    _Bool _showChatMemberReport;
    _Bool _showChatChannalReport;
    _Bool _hideChatBtn;
    _Bool _didAddSuccess;
    _Bool _isViewDisappear;
    _Bool _isFromNearbyShake;
    _Bool _isPhoneInCalling;
    int _type;
    long long _applyFromType;
    UIView *_topBackgroudView;
    UIButton *_videoCallButton;
    YNDefaultMediaContainerViewController *_singleImgageDisplayVC;
    YNSingleChatViewController *_singleChatVC;
    YNChatRoomMember *_chatRoomMember;
    YNChatConversation *_friendConversation;
    NSString *_distanceInfo;
    NSString *_recommendTag;
    NSArray *_greetChatMessageArray;
    YNTextInputHelper *_textInputHelper;
}

+ (Class)getUserProfileClass:(id)arg1;
- (void).cxx_destruct;
- (void)addBlackListButtonClick:(id)arg1;
- (void)addFriendAgreeApplyButtonClicked:(id)arg1;
- (void)addToMyContactButtonClicked:(id)arg1;
@property(nonatomic) long long applyFromType; // @synthesize applyFromType=_applyFromType;
@property(retain, nonatomic) UIButton *blackListButton; // @synthesize blackListButton=_blackListButton;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIButton *chatButton; // @synthesize chatButton=_chatButton;
- (void)chatCenter:(id)arg1 didReceiveNewFriendMessage:(id)arg2;
@property(retain, nonatomic) YNChatRoomMember *chatRoomMember; // @synthesize chatRoomMember=_chatRoomMember;
- (void)chatViewControllerDidPreloadMessageCompleted:(id)arg1;
- (void)chatWithFriend:(id)arg1;
@property(retain, nonatomic) UIButton *complainButton; // @synthesize complainButton=_complainButton;
- (void)dealloc;
@property(nonatomic) _Bool didAddSuccess; // @synthesize didAddSuccess=_didAddSuccess;
- (void)didChangedSwitchTalbleViewCell:(id)arg1 switchView:(id)arg2;
- (void)didEditedFriend:(id)arg1;
- (void)didFinishedLoadFriends:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)didTapedDefaultMediaContainerView:(id)arg1;
@property(retain, nonatomic) NSString *distanceInfo; // @synthesize distanceInfo=_distanceInfo;
- (void)drawView;
- (void)editingSelfProfile:(id)arg1;
@property(retain, nonatomic) YNChatConversation *friendConversation; // @synthesize friendConversation=_friendConversation;
- (void)getFriendInfoForServer;
@property(retain, nonatomic) NSArray *greetChatMessageArray; // @synthesize greetChatMessageArray=_greetChatMessageArray;
- (void)greetChatTableViewCellReplyButtonClick:(id)arg1;
- (void)handleReport:(id)arg1;
@property(retain, nonatomic) YNUserPorfileHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool hideChatBtn; // @synthesize hideChatBtn=_hideChatBtn;
- (void)initNaviBarItem;
- (id)initWithChatRoomMember:(id)arg1 withConversation:(id)arg2;
- (id)initWithFriend:(id)arg1;
- (id)initWithFriend:(id)arg1 withConversation:(id)arg2;
- (id)initWithFriend:(id)arg1 withDistanceInfo:(id)arg2 withRecommendTagArray:(id)arg3;
- (_Bool)isFriendHavePhoneNumber:(id)arg1;
@property(nonatomic) _Bool isFromNearbyShake; // @synthesize isFromNearbyShake=_isFromNearbyShake;
@property(nonatomic) _Bool isPhoneInCalling; // @synthesize isPhoneInCalling=_isPhoneInCalling;
@property(nonatomic) _Bool isViewDisappear; // @synthesize isViewDisappear=_isViewDisappear;
@property(retain, nonatomic) YNFriend *myFriend; // @synthesize myFriend=_myFriend;
- (void)networkStatusDidChange:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)pushBrow:(id)arg1;
@property(retain, nonatomic) NSString *recommendTag; // @synthesize recommendTag=_recommendTag;
- (void)refreshBottomView;
- (void)refreshDataSource;
- (void)refreshFriendType;
- (void)refreshHeaderView;
- (void)removeBlackListButtonClick:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)sendAddFriendApplyByFriend:(id)arg1;
- (void)sendFriendApplyWithText:(id)arg1;
@property(nonatomic) _Bool shouldDeleteScanVC; // @synthesize shouldDeleteScanVC=_shouldDeleteScanVC;
@property(nonatomic) _Bool showChatChannalReport; // @synthesize showChatChannalReport=_showChatChannalReport;
@property(nonatomic) _Bool showChatMemberReport; // @synthesize showChatMemberReport=_showChatMemberReport;
@property(retain, nonatomic) YNSingleChatViewController *singleChatVC; // @synthesize singleChatVC=_singleChatVC;
@property(retain, nonatomic) YNDefaultMediaContainerViewController *singleImgageDisplayVC; // @synthesize singleImgageDisplayVC=_singleImgageDisplayVC;
@property(retain, nonatomic) YNTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) YNTextInputHelper *textInputHelper; // @synthesize textInputHelper=_textInputHelper;
@property(retain, nonatomic) UIView *topBackgroudView; // @synthesize topBackgroudView=_topBackgroudView;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) UIButton *videoCallButton; // @synthesize videoCallButton=_videoCallButton;
@property(retain, nonatomic) NSMutableArray *viewModleArray; // @synthesize viewModleArray=_viewModleArray;
- (void)setupViewConstraints;
- (_Bool)shouldShowAddSource;
- (void)showPhoneNumberCellDidClickPhoneNumberButton:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)userPorfileHeaderViewDidTapedAvatar:(id)arg1;
- (void)userProfileMoreButtonClicked:(id)arg1;
- (void)videoCallAction:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

