//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, UITableView, YNFriend, YNProgressHUD, YNTextInputHelper;

@interface YNUserSignatureSettingViewController : YNBaseViewController <UITableViewDataSource, UITableViewDelegate, UITextViewDelegate>
{
    UITableView *_tableView;
    YNFriend *_me;
    YNProgressHUD *_loadingProgressView;
    YNTextInputHelper *_textInputHelper;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)handleTextViewDidChange:(id)arg1;
- (void)hideDelayed;
- (id)init;
- (void)initNaviBarItem;
@property(retain, nonatomic) YNProgressHUD *loadingProgressView; // @synthesize loadingProgressView=_loadingProgressView;
@property(retain, nonatomic) YNFriend *me; // @synthesize me=_me;
- (void)reachabilityChanged:(id)arg1;
- (void)saveSiginatureButtonClicked:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) YNTextInputHelper *textInputHelper; // @synthesize textInputHelper=_textInputHelper;
- (void)setupViewConstraints;
- (void)signatureBackButtonClicked:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

