//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel, YNAvatarView, YNChatRoomMember, YNFriend;

@interface YNUserInfoHeaderView : UIView
{
    id <YNUserInfoHeaderViewDelegate> _delegate;
    YNAvatarView *_avatarImageView;
    UILabel *_nameLabel;
    UILabel *_realNickNameLabel;
    UILabel *_chatRoomMemberLabel;
    UILabel *_accountNameLabel;
    UIImageView *_userSexIconImageView;
    YNFriend *_myFrined;
    YNChatRoomMember *_chatRoomMember;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *accountNameLabel; // @synthesize accountNameLabel=_accountNameLabel;
@property(retain, nonatomic) YNAvatarView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) YNChatRoomMember *chatRoomMember; // @synthesize chatRoomMember=_chatRoomMember;
@property(retain, nonatomic) UILabel *chatRoomMemberLabel; // @synthesize chatRoomMemberLabel=_chatRoomMemberLabel;
@property(nonatomic) __weak id <YNUserInfoHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) YNFriend *myFrined; // @synthesize myFrined=_myFrined;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *realNickNameLabel; // @synthesize realNickNameLabel=_realNickNameLabel;
@property(retain, nonatomic) UIImageView *userSexIconImageView; // @synthesize userSexIconImageView=_userSexIconImageView;
- (void)setupViewConstraints;
- (void)useProfileHeaderHandleAvatarTap:(id)arg1;
- (void)userUid:(id)arg1 nickName:(id)arg2 location:(id)arg3;

@end

