//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, YNUserBirthdayPickerView;

@protocol YNUserBirthdayPickerViewDelegate <NSObject>
- (void)userBirthdayPickerView:(YNUserBirthdayPickerView *)arg1 didSelectdBirthday:(NSString *)arg2;
@end

