//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNPhotoItem.h"

@class NSURL;

@interface YNVideoItem : YNPhotoItem
{
    NSURL *_URL;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (unsigned long long)fileSize;
- (void)getICloudThumbnailImageSynchronous:(_Bool)arg1 comletion:(CDUnknownBlockType)arg2;
- (id)getOriginalImageData;
- (id)getVideoSourceURL;
- (_Bool)isIniCloud;
- (unsigned long long)mediaType;
- (int)requestPHAssetInfoAsync:(CDUnknownBlockType)arg1 result:(CDUnknownBlockType)arg2;
- (int)requestVideoFromCloud:(CDUnknownBlockType)arg1 result:(CDUnknownBlockType)arg2;
- (void)transcodeVideoToURL:(id)arg1 handler:(CDUnknownBlockType)arg2;

@end

