//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YNBaseViewController.h"

#import "ZMVClipViewControllerDelegate.h"

@class NSString, NSURL;

@interface YNVideoClipViewController : YNBaseViewController <ZMVClipViewControllerDelegate>
{
    id <YNVideoClipViewControllerDelegate> _delegate;
    NSURL *_videoPathURL;
}

- (void).cxx_destruct;
- (void)clipVC:(id)arg1 videoCompleteWithVideoPath:(id)arg2 imagePath:(id)arg3;
- (void)clipViewControllerDidCancel:(id)arg1;
- (void)clipViewControllerError:(id)arg1 localizedDescription:(id)arg2 localizedFailureReason:(id)arg3 error:(id)arg4;
@property(nonatomic) __weak id <YNVideoClipViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithVideoPathURL:(id)arg1;
@property(retain, nonatomic) NSURL *videoPathURL; // @synthesize videoPathURL=_videoPathURL;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

