//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YNLocalVideoItem, YNVideoClipViewController;

@protocol YNVideoClipViewControllerDelegate <NSObject>

@optional
- (void)clipViewController:(YNVideoClipViewController *)arg1 didCompleteWithLocalVideo:(YNLocalVideoItem *)arg2;
- (void)clipViewControllerDidCancel:(YNVideoClipViewController *)arg1;
- (void)clipViewControllerDidClipFailed:(YNVideoClipViewController *)arg1;
@end

