//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ZMRtcMediaEngineDelegate.h"

@class CTCallCenter, GCDMulticastDelegate<YNVoipCenterDelegate>, NSObject<OS_dispatch_queue>, NSString, NSTimer, YNVoipSession, ZMRtcMediaEngine;

@interface YNVoipCenter : NSObject <ZMRtcMediaEngineDelegate>
{
    NSObject<OS_dispatch_queue> *_voipMessageQueue;
    double _callingDuration;
    NSTimer *_callingTimer;
    NSTimer *_chattingTimer;
    _Bool _isCalling;
    _Bool _isAudioChangeEnable;
    _Bool _isAudioRouteSpeaker;
    _Bool _isVoipEnabled;
    GCDMulticastDelegate<YNVoipCenterDelegate> *_multicastDelegate;
    YNVoipSession *_voipSession;
    ZMRtcMediaEngine *_voipEngine;
    long long _accountId;
    CTCallCenter *_callCenter;
    NSString *_ctCallState;
}

+ (id)sharedCenter;
- (void).cxx_destruct;
@property(nonatomic) long long accountId; // @synthesize accountId=_accountId;
- (void)accpetCall;
- (void)addDelegate:(id)arg1;
@property(retain, nonatomic) CTCallCenter *callCenter; // @synthesize callCenter=_callCenter;
- (void)callToFriend:(long long)arg1 callType:(unsigned long long)arg2;
- (void)callingTimerAction:(id)arg1;
- (void)cancelVoipStatusMessageForVoipCommandMessage:(id)arg1;
- (void)chattingTimerAction:(id)arg1;
- (void)collectionVoipLog;
@property(copy, nonatomic) NSString *ctCallState; // @synthesize ctCallState=_ctCallState;
- (id)currentCTCallState;
- (void)disableLocalAudio;
- (void)disableLocalVideo;
- (_Bool)enableAudioRouteToSpeaker:(_Bool)arg1;
- (void)enableLocalAudio;
- (void)enableLocalVideo;
- (void)finishSession;
- (void)hangUpCall;
- (void)incomingVoipMessage:(id)arg1;
- (id)init;
- (void)insertVoipStatusMessageForVoipSession:(id)arg1;
- (void)interruptionNotification:(id)arg1;
@property(nonatomic) _Bool isAudioChangeEnable; // @synthesize isAudioChangeEnable=_isAudioChangeEnable;
@property(nonatomic) _Bool isAudioRouteSpeaker; // @synthesize isAudioRouteSpeaker=_isAudioRouteSpeaker;
@property(nonatomic) _Bool isCalling; // @synthesize isCalling=_isCalling;
- (_Bool)isFriendCancelCallMessage:(id)arg1;
@property(nonatomic) _Bool isVoipEnabled; // @synthesize isVoipEnabled=_isVoipEnabled;
- (void)mediaEngine:(id)arg1 callee:(unsigned long long)arg2 didAcceptResponseStatus:(long long)arg3;
- (void)mediaEngine:(id)arg1 didCallFinish:(unsigned long long)arg2 roomId:(unsigned long long)arg3;
- (void)mediaEngine:(id)arg1 didDisconnectWithErrorCode:(long long)arg2;
- (void)mediaEngine:(id)arg1 didJoinRoom:(unsigned long long)arg2 withUser:(unsigned long long)arg3;
- (void)mediaEngine:(id)arg1 didReceiveRemoteVideo:(unsigned long long)arg2;
- (void)mediaEngine:(id)arg1 didReceiveUser:(unsigned long long)arg2 data:(long long)arg3;
- (void)mediaEngine:(id)arg1 didVideoClose:(_Bool)arg2 userId:(unsigned long long)arg3;
- (void)mediaEngine:(id)arg1 failedJoinRoom:(unsigned long long)arg2 withUser:(unsigned long long)arg3 errorCode:(long long)arg4;
- (void)mediaEngine:(id)arg1 myself:(unsigned long long)arg2 acceptResponseStatus:(long long)arg3;
- (void)mediaEngine:(id)arg1 otherUser:(unsigned long long)arg2 didJoinRoom:(unsigned long long)arg3;
- (void)mediaEngine:(id)arg1 remoteDidClose:(unsigned long long)arg2;
- (void)mediaEngine:(id)arg1 reportNetStatus:(long long)arg2;
- (void)mediaEngine:(id)arg1 room:(unsigned long long)arg2 didHangupByUser:(unsigned long long)arg3;
- (void)mediaEngine:(id)arg1 roomDidDestroy:(unsigned long long)arg2;
- (void)mediaEngine:(id)arg1 shouldSendKeepLiveMessage:(id)arg2;
- (void)mediaEngine:(id)arg1 shouldSendUpdateMessage:(id)arg2;
- (void)mediaEngine:(id)arg1 user:(unsigned long long)arg2 didCallToUser:(unsigned long long)arg3 responseStatus:(long long)arg4;
- (void)mediaEngine:(id)arg1 userOnCalling:(unsigned long long)arg2 calleeId:(unsigned long long)arg3 callType:(long long)arg4;
- (void)mediaEngine:(id)arg1 userOnCalling:(unsigned long long)arg2 calleeId:(unsigned long long)arg3 callType:(long long)arg4 curSessionId:(unsigned int)arg5 newSessionId:(unsigned int)arg6;
- (void)mediaEngineDidChangeAudioRoute:(id)arg1;
@property(retain, nonatomic) GCDMulticastDelegate<YNVoipCenterDelegate> *multicastDelegate; // @synthesize multicastDelegate=_multicastDelegate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onCallingAction;
- (void)refuseCall;
- (void)removeDelegate:(id)arg1;
- (void)resetTimerStatus;
- (void)sendVoipMessageForCommand:(id)arg1;
- (_Bool)setRemoteUserVideoView:(id)arg1;
@property(retain, nonatomic) ZMRtcMediaEngine *voipEngine; // @synthesize voipEngine=_voipEngine;
@property(retain, nonatomic) YNVoipSession *voipSession; // @synthesize voipSession=_voipSession;
- (void)startCTMonitor;
- (void)startPreviewOnView:(id)arg1;
- (void)stopPreview;
- (void)switchCamera;
- (void)switchToVoice;
- (void)switchUser;
- (void)updatePreview:(id)arg1;
- (void)voipDidJoinRoom:(unsigned long long)arg1 withUser:(unsigned long long)arg2;
- (void)willStartVoipCallHandle;
- (void)writeVoipLogForSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

