//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSDictionary, UIButton, UILabel;

@interface YNWebpageCollectionViewCell : UICollectionViewCell
{
    id <YNWebpageCollectionViewCellDelegate> _delegate;
    NSDictionary *_dataSoureDic;
    UIButton *_actionButton;
    UILabel *_actionTitleLabel;
}

+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
- (void)actionButtonClick:(id)arg1;
@property(retain, nonatomic) UILabel *actionTitleLabel; // @synthesize actionTitleLabel=_actionTitleLabel;
@property(retain, nonatomic) NSDictionary *dataSoureDic; // @synthesize dataSoureDic=_dataSoureDic;
@property(nonatomic) __weak id <YNWebpageCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;

@end

