//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YNWebsiteInfo : NSObject
{
    NSString *_originalUrl;
    NSString *_url;
    NSString *_iconUrl;
    NSString *_title;
    NSString *_brief;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *brief; // @synthesize brief=_brief;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
- (id)initWithUrl:(id)arg1;
- (_Bool)isValid;
@property(retain, nonatomic) NSString *originalUrl; // @synthesize originalUrl=_originalUrl;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;

@end

