//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "woaDelegate.h"

@class NSString, WoaOpenApi;

@interface YNWOARegisterManager : NSObject <woaDelegate>
{
    _Bool _isRegisterForSimulator;
    id <YNWOARegsterManagerDelegate> _delegate;
    WoaOpenApi *_woa;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)checkVerificationCodeResult:(id)arg1;
- (void)checkVerificationCodeResult:(long long)arg1 msg:(id)arg2;
@property(nonatomic) id <YNWOARegsterManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
@property(nonatomic) _Bool isRegisterForSimulator; // @synthesize isRegisterForSimulator=_isRegisterForSimulator;
- (void)mobileReceiveSMSLoginForPhoneNumber:(id)arg1;
- (void)mobileReceiveSMSLoginResult:(long long)arg1 msg:(id)arg2;
- (void)onSuccess:(long long)arg1 result:(id)arg2;
@property(retain, nonatomic) WoaOpenApi *woa; // @synthesize woa=_woa;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

