//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UITextField;

@interface YNZhangxinIDSettingCell : UITableViewCell
{
    UILabel *_tagLabel;
    UITextField *_textField;
}

+ (id)reuseIdentifier;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void)setupViewConstraints;

@end

