//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZMRtcMediaEngineUtil : NSObject
{
}

+ (struct CGSize)adjustResolutionForPreset:(long long)arg1;
+ (int)bitRateFromPreset:(long long)arg1;
+ (int)frameRateFromPreset:(long long)arg1;
+ (id)hardwareModelName;
+ (int)intIPAddressFromString:(id)arg1;
+ (struct CGSize)resolutionFromPreset:(long long)arg1;
+ (id)stringIPAddressFromInt:(int)arg1;

@end

