//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UISlider, ZMVAVPlayer;

@protocol ZMVAVPlayerDelegate <NSObject>

@optional
- (void)avplayerView:(ZMVAVPlayer *)arg1 bufferDuration:(double)arg2;
- (void)avplayerView:(ZMVAVPlayer *)arg1 didStart:(_Bool)arg2 avplayerDuration:(double)arg3;
- (void)avplayerView:(ZMVAVPlayer *)arg1 isPlayback:(_Bool)arg2;
- (void)avplayerView:(ZMVAVPlayer *)arg1 sliderValuechange:(UISlider *)arg2;
@end

