//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureAudioDataOutputSampleBufferDelegate.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureAudioDataOutput, AVCaptureConnection, AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, CALayer, CMMotionManager, NSObject<OS_dispatch_queue>, NSString, ZMVMp4Writer;

@interface ZMVCamera : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
{
    AVCaptureDevice *_inputCamera;
    NSObject<OS_dispatch_queue> *_cameraOutputQueue;
    NSObject<OS_dispatch_queue> *_cameraSessionQueue;
    AVCaptureVideoDataOutput *_videoOutput;
    AVCaptureAudioDataOutput *_audioOut;
    AVCaptureConnection *_audioConnection;
    AVCaptureConnection *_videoConnection;
    struct __CVBuffer *_pixelBuffer1;
    struct __CVBuffer *_pixelBuffer2;
    struct __CVBuffer *_pixelBuffer3;
    struct __CVBuffer *_firstBuffer;
    struct __CVBuffer *_lastBuffer;
    int _frameRate;
    unsigned long long _count;
    unsigned long long _num;
    NSString *_cameraPreset;
    ZMVMp4Writer *_mp4Writer;
    _Bool _isCapturing;
    unsigned long long _preWidth;
    unsigned long long _preHeight;
    unsigned long long _scalewidth;
    unsigned long long _scaleheight;
    unsigned long long _width;
    unsigned long long _height;
    int _sampleRate;
    int _channel;
    NSString *_url;
    int _nType;
    long long angle;
    long long imageRotate;
    AVCaptureVideoPreviewLayer *_previewLayer;
    _Bool _allowWriteAudio;
    long long pixelCount;
    _Bool _isVideo;
    _Bool _autoRatio;
    AVCaptureSession *_captureSession;
    id <ZMVCameraOutput> _cameraOutput;
    AVCaptureStillImageOutput *_captureStillImageOutput;
    double _lastScale;
    AVCaptureDeviceInput *_videoInput;
    CMMotionManager *_motionManager;
}

+ (id)defaultBackCameraWithOutput:(id)arg1;
+ (id)defaultFrontCameraWithOutput:(id)arg1;
- (void).cxx_destruct;
- (id)_captureDeviceWithPosition:(long long)arg1;
- (void)addFocusObserverOnCurrentCamera;
@property(nonatomic) _Bool autoRatio; // @synthesize autoRatio=_autoRatio;
@property(nonatomic) __weak id <ZMVCameraOutput> cameraOutput; // @synthesize cameraOutput=_cameraOutput;
@property(readonly, nonatomic) long long cameraPosition;
@property(retain, nonatomic) NSString *cameraPreset;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(retain, nonatomic) AVCaptureStillImageOutput *captureStillImageOutput; // @synthesize captureStillImageOutput=_captureStillImageOutput;
- (void)closeCamera;
- (void)dealloc;
- (void)enableContinuousAutoExposure;
- (void)enableContinuousAutoFocus;
- (void)enableContinuousAutoWhiteBalance;
@property(nonatomic) int frameRate;
- (id)getLastPicture;
- (id)getPicture;
- (void)handleDeviceMotion:(id)arg1;
- (id)imageFromImageBuffer:(struct __CVBuffer *)arg1;
- (void)initMotionManager;
- (id)initUsingDefaultSettingsWithPosition:(long long)arg1 output:(id)arg2;
- (id)initWithPosition:(long long)arg1 cameraSessionPreset:(id)arg2 pixelFormatType:(unsigned int)arg3 frameRate:(int)arg4 cameraOutput:(id)arg5;
@property(retain, nonatomic) AVCaptureDevice *inputCamera; // @synthesize inputCamera=_inputCamera;
@property _Bool isCapturing; // @synthesize isCapturing=_isCapturing;
@property(nonatomic) _Bool isVideo; // @synthesize isVideo=_isVideo;
@property(nonatomic) double lastScale; // @synthesize lastScale=_lastScale;
- (void)lockExposureAndFocusAtPointOfInterest:(struct CGPoint)arg1;
- (void)lockExposureAtPointOfInterest:(struct CGPoint)arg1;
- (void)lockFocusAtPointOfInterest:(struct CGPoint)arg1;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)openCamera;
- (void)openCameraCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) CALayer *previewLayer;
- (void)processCameraSettingsTask:(CDUnknownBlockType)arg1;
- (void)removeFocusObserverOnCurrentCamera;
- (void)removeMotionManager;
- (id)rotate:(long long)arg1 WithSimple:(id)arg2;
- (void)setAudioInfo:(int)arg1 andchannel:(int)arg2;
- (void)setFileUrl:(id)arg1 andType:(int)arg2;
- (void)setPictureNum:(unsigned long long)arg1;
- (void)setTorchMode:(long long)arg1;
- (void)setVideoInfo:(unsigned long long)arg1 andheight:(unsigned long long)arg2;
@property(retain, nonatomic) AVCaptureDeviceInput *videoInput; // @synthesize videoInput=_videoInput;
- (void)startCapture;
- (void)stopCapture;
- (void)stopCaptureWithCompletion:(CDUnknownBlockType)arg1;
- (void)switchCamera;
- (void)toggleRampVideoZoom;
- (void)toggleRampVideoZoomWithScale:(double)arg1;
- (void)toggleVideoZoom;
- (long long)torchMode;
- (void)updateCameraMirrorStatus;
- (void)updateVideoImageSize:(unsigned long long)arg1 andheight:(unsigned long long)arg2;
- (void)updatepixelBuffer:(struct opaqueCMSampleBuffer *)arg1 andcount:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

