//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZMVMediaManager : NSObject
{
}

+ (unsigned long long)degressFromVideoFileWithURL:(id)arg1;
+ (id)getCoverImage:(id)arg1 atTime:(double)arg2 isKeyImage:(_Bool)arg3 WithScale:(double)arg4;
+ (id)getCoverImage:(id)arg1 atTime:(double)arg2 isKeyImage:(_Bool)arg3 WithScale:(double)arg4 WithSize:(struct CGSize)arg5;
+ (double)getVideoTimeWithURL:(id)arg1;

@end

