//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ZMVProgressView;

@protocol ZMVProgressViewDelegate <NSObject>

@optional
- (void)maxTimeWithZMVProgressView:(ZMVProgressView *)arg1;
- (void)zmvProgressView:(ZMVProgressView *)arg1 currentTime:(double)arg2;
@end

