//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVMutableComposition, AVMutableVideoComposition, NSMutableArray, ZMVMovieTranscoder;

@interface ZMVWatermarkTool : NSObject
{
    AVMutableComposition *mixComposition;
    AVMutableVideoComposition *mainCompositionInst;
    struct CGSize naturalSize;
    ZMVMovieTranscoder *_transcoder;
    NSMutableArray *_layerArr;
}

- (void).cxx_destruct;
- (void)ExportAndSavedPhotosAlbumWithPath:(id)arg1;
- (void)addImage:(id)arg1 rect:(struct CGRect)arg2;
- (void)addTitle:(id)arg1 titleColor:(id)arg2 backgroundColor:(id)arg3 rect:(struct CGRect)arg4;
- (void)addWatermarkWithVideoPath:(id)arg1;
- (void)applyVideoEffectsToComposition:(id)arg1 size:(struct CGSize)arg2;
- (long long)degressFromVideoFileWithAsset:(id)arg1;
- (struct CGSize)fixRenderSizeWithAsset:(id)arg1;
- (struct CGAffineTransform)fixVideoTransformFromAssert:(id)arg1;
@property(retain, nonatomic) NSMutableArray *layerArr; // @synthesize layerArr=_layerArr;

@end

